SELECT
decode(NF.CD_MULTI_EMPRESA,1,'MADRE REGINA PROTMANN',
			   3,'CASA DE SAUDE SAO JOSE',
                           4,'HOSPITAL SANTA TEREZA',
                           7,'HOSPITAL SANTA CATARINA',
                           10,'HOSPITAL SAO JOSE',
                           25,'HOSPITAL DE CLINICAS NOSSA SENHORA DA CONCEICAO')CASA,
rem.cd_remessa,
NF.NR_ID_NOTA_FISCAL NF_MV,
NF.NR_NOTA_FISCAL_NFE NF_PREFEITURA,
NF.CD_STATUS,
CONV.CD_CONVENIO,
CONV.NM_CONVENIO,
NF.NM_CLIENTE,
INF.CD_REG_FAT CONTA_INT,
INF.CD_REG_AMB CONTA_AMB,
CR.CD_CON_REC CONTA_RECEBER,
NF.NR_CGC_CPF CPF_CNPJ,
NF.DT_EMISSAO,
REM.DT_PREVISTA_PARA_PGTO,
CR.VL_PREVISTO VL_BRUTO_NOTA,
NF.VL_TOTAL_NOTA VL_LIQ_NOTA,
SUM(INF.VL_ITFAT_NF)VL_TOTAL_REMESSA
FROM
NOTA_FISCAL NF
LEFT JOIN ITFAT_NOTA_FISCAL INF ON INF.CD_NOTA_FISCAL = NF.CD_NOTA_FISCAL
LEFT JOIN REMESSA_FATURA REM ON REM.CD_REMESSA = INF.CD_REMESSA
LEFT JOIN CONVENIO CONV ON CONV.CD_CONVENIO = NF.CD_CONVENIO
LEFT JOIN CON_REC CR ON CR.CD_NOTA_FISCAL = NF.CD_NOTA_FISCAL
WHERE NF.DT_EMISSAO BETWEEN TO_DATE ('01/06/2021','dd/mm/yyyy') AND TO_DATE ('31/10/2021','dd/mm/yyyy')
AND NF.CD_STATUS in ('E','C')
AND NF.CD_MULTI_EMPRESA in ('3','4','7','10','25')
--AND NF.CD_NOTA_FISCAL = 252320
--AND NF.NR_ID_NOTA_FISCAL = 108812
AND (CONV.TP_CONVENIO = 'C' OR CONV.TP_CONVENIO IS NULL)
GROUP BY
NF.CD_MULTI_EMPRESA,
rem.cd_remessa,
NF.NR_ID_NOTA_FISCAL,
NF.NR_NOTA_FISCAL_NFE,
NF.CD_STATUS,
CONV.CD_CONVENIO,
CONV.NM_CONVENIO,
NF.NM_CLIENTE,
INF.CD_REG_FAT,
INF.CD_REG_AMB,
CR.CD_CON_REC,
NF.NR_CGC_CPF,
NF.DT_EMISSAO,
REM.DT_PREVISTA_PARA_PGTO,
CR.VL_PREVISTO ,
NF.VL_TOTAL_NOTA
ORDER BY 1,3
