SELECT
      ITPRE_MED.CD_ITPRE_MED,
      DECODE(ITPRE_MED.DS_NPADRONIZADO,NULL,ITPRE_MED.DS_ITPRE_MED,'N.P.' || ITPRE_MED.DS_NPADRONIZADO) DS_ITPRE_MED,
      ITPRE_MED.CD_TIP_ESQ,
      TIP_ESQ.DS_TIP_ESQ,
      TIP_PRESC.CD_TIP_PRESC,
      DECODE(ITPRE_MED.DS_NPADRONIZADO,NULL, TIP_PRESC.DS_TIP_PRESC,'N.P.' || ITPRE_MED.DS_NPADRONIZADO) DS_TIP_PRESC,
      tip_presc.cd_pro_fat PROCEDIMENTO,
      pro_fat.ds_pro_fat NOME_PROCEDIMENTO,
      ITPRE_MED.CD_PRE_MED,
      ITPRE_MED.CD_SET_EXA,
      SET_EXA.NM_SET_EXA,
      ITPRE_MED.CD_TIP_FRE,
      TIP_FRE.DS_TIP_FRE,
      ITPRE_MED.CD_FOR_APL,
      FOR_APL.DS_FOR_APL,
      ITPRE_MED.QT_ITPRE_MED,
      ITPRE_MED.TP_SITUACAO,
      ITPRE_MED.SN_CANCELADO,
      Nvl(UNI_PRO.DS_UNIDADE, UNIDADE.DS_UNIDADE) DS_UNIDADE,
      ITPRE_MED.DH_FINAL,
      ITPRE_MED.DH_CANCELADO,
      ITPRE_MED.CD_PREST_CANC,
      PRE_MED.CD_ATENDIMENTO,
      PRE_MED.CD_PRESTADOR,
      PRESTADOR.NM_PRESTADOR,
      PRE_MED.CD_UNID_INT,
      UNID_INT.DS_UNID_INT,
      PRE_MED.CD_SETOR,
      SETOR.NM_SETOR,
      PRE_MED.DT_PRE_MED,
      PRE_MED.HR_PRE_MED,
      PRE_MED.TP_PRE_MED,
      PRE_MED.NM_USUARIO,
      ITPRE_MED.CD_ITPRE_MED_JUSTIFICATIVA,
      ITPRE_MED.DS_JUSTIFICATIVA,
      ITPRE_MED.TP_JUSTIFICATIVA,
      ITPRE_MED.TP_DET_JUSTIFICATIVA,
      ITPRE_MED.QT_DIAS,
      PACIENTE.NM_PACIENTE

 FROM DBAMV.ITPRE_MED,
      DBAMV.PRE_MED,
      DBAMV.TIP_ESQ,
      DBAMV.TIP_PRESC,
      DBAMV.SET_EXA,
      DBAMV.TIP_FRE,
      DBAMV.FOR_APL,
      DBAMV.UNIDADE,
      DBAMV.UNI_PRO,
      DBAMV.PRESTADOR,
      DBAMV.SETOR,
      DBAMV.UNID_INT,
      DBAMV.ATENDIME,
      DBAMV.PACIENTE,
      DBAMV.PRO_FAT
 
  WHERE
       ITPRE_MED.CD_PRE_MED = PRE_MED.CD_PRE_MED
       AND ITPRE_MED.CD_TIP_ESQ = TIP_ESQ.CD_TIP_ESQ
       --AND ITPRE_MED.CD_TIP_ESQ = 'MVO' --TIP_ESQ.CD_TIP_ESQ
       AND ITPRE_MED.CD_TIP_PRESC = TIP_PRESC.CD_TIP_PRESC
       --AND ITPRE_MED.CD_TIP_PRESC = 53199 --TIP_PRESC.CD_TIP_PRESC
       AND TIP_PRESC.CD_TIP_ESQ = TIP_ESQ.CD_TIP_ESQ
       AND ITPRE_MED.CD_SET_EXA = SET_EXA.CD_SET_EXA(+)
       AND ITPRE_MED.CD_TIP_FRE = TIP_FRE.CD_TIP_FRE(+)
       AND ITPRE_MED.CD_FOR_APL = FOR_APL.CD_FOR_APL(+)
       AND ITPRE_MED.CD_UNIDADE = UNIDADE.CD_UNIDADE(+)
       AND ITPRE_MED.CD_UNI_PRO = UNI_PRO.CD_UNI_PRO(+)
       AND PRE_MED.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR(+)
       AND PRE_MED.CD_UNID_INT = UNID_INT.CD_UNID_INT(+)
       --AND PRE_MED.CD_UNID_INT = 3 --UNID_INT.CD_UNID_INT(+)
       AND PRE_MED.CD_SETOR = SETOR.CD_SETOR(+)
       AND PACIENTE.CD_PACIENTE = ATENDIME.CD_PACIENTE
       AND ATENDIME.CD_ATENDIMENTO = PRE_MED.CD_ATENDIMENTO
       AND TIP_PRESC.CD_PRO_FAT = PRO_FAT.CD_PRO_FAT
--       AND (dt_pre_med BETWEEN  to_date('01/01/2021 00:00:00', 'dd/mm/yyyy hh24:mi:ss') AND  to_date('15/06/2021 00:00:00', 'dd/mm/yyyy hh24:mi:ss'))
       --AND TIP_PRESC.DS_TIP_PRESC like '%VISITA%'
       AND (ITPRE_MED.CD_TIP_ESQ = 'VIS' OR ITPRE_MED.CD_TIP_PRESC IN (81550,81551,81552,81553,81554,81555,81556,81557,81558,81559))
       AND PRE_MED.CD_PRESTADOR = 12729
    --   and pre_med.cd_atendimento = 2731087
       --AND ATENDIME.CD_MULTI_EMPRESA = 7
       order by PRE_MED.CD_PRE_MED asc
