SELECT DISTINCT  
       AC.CD_AVISO_CIRURGIA NR_AVISO,
       AC.CD_ATENDIMENTO ATENDIMENTO,
       --AC.DT_INICIO_CIRURGIA,
       --AC.DT_FIM_CIRURGIA,
       AC.DT_REALIZACAO DT_CIRURGIA,
       P.NM_PACIENTE,
       --CA.CD_CIRURGIA,
       C.DS_CIRURGIA CIRURGIA,
       --CA.CD_CONVENIO,
       --CON.NM_CONVENIO,
       P.NM_PRESTADOR
       --A.CD_PRESTADOR,
      -- TRUNC(AC.DT_REALIZACAO) DT_REAL,
       --AC.CD_CEN_CIR
  FROM DBAMV.AVISO_CIRURGIA AC,
       DBAMV.CIRURGIA_AVISO CA,
       DBAMV.CIRURGIA       C,
       DBAMV.ATENDIME       A,
       DBAMV.PACIENTE       P,
       DBAMV.CONVENIO       CON,
       DBAMV.PRESTADOR P
 WHERE CA.CD_AVISO_CIRURGIA = AC.CD_AVISO_CIRURGIA
   AND CA.CD_CIRURGIA = C.CD_CIRURGIA
   AND AC.CD_ATENDIMENTO = A.CD_ATENDIMENTO
   AND A.CD_PACIENTE = P.CD_PACIENTE
   AND A.CD_CONVENIO = CON.CD_CONVENIO
   AND CA.CD_CONVENIO = CON.CD_CONVENIO
   AND A.CD_PRESTADOR = P.CD_PRESTADOR
   AND CA.CD_CIRURGIA IN (5047,899,5087)
   AND AC.CD_CEN_CIR = 02 --(02 C.O / 01 C.C HMSJ  -- 04 - CC/CO PMP )
   AND A.CD_PRESTADOR IN (7926,9257) -- (7926 SERV.VANGUARDA , 9257 SERV.VANGUARDA 2) 
   and AC.CD_MULTI_EMPRESA = 1
   AND TRUNC(AC.DT_REALIZACAO)BETWEEN '01/11/2015' AND '30/11/2015'
   order by 3,4 
