--<DS_SCRIPT>
-- OP/PDA.....: SUP-48039
-- DESCRIÇÃO..: CRIAÇÃO DA COLUNA DT_COMPETENCIA
-- RESPONSAVEL: Claudecy
-- DATA.......: 15/02/2018
-- APLICAÇÃO..: FNCP
--</DS_SCRIPT>
--<USUARIO=DBAMV>

ALTER TABLE DBAMV.RATCON_PAG
ADD dt_competencia DATE NOT NULL
/