SELECT ATENDIME.CD_MOT_ALT ,ATENDIME.NM_USUARIO_ALTA, ATENDIME.NM_USUARIO_ALTA_MEDICA, ATENDIME.NR_DECLARACAO_OBITO,
       ATENDIME.DT_DIAG, ATENDIME.DT_ALTA, ATENDIME.HR_ALTA, ATENDIME.DT_ALTA_MEDICA, ATENDIME.HR_ALTA_MEDICA,
       MOV_INT.DT_MOV_INT, MOV_INT.HR_MOV_INT, MOV_INT.DT_LIB_MOV, MOV_INT.HR_LIB_MOV, MOV_INT.cd_leito, MOV_INT.cd_leito_anterior
FROM   ATENDIME, MOV_INT
WHERE  ATENDIME.CD_ATENDIMENTO = MOV_INT.CD_ATENDIMENTO
AND    ATENDIME.CD_ATENDIMENTO = 789544   -- Alterar a Data e Hora de Alta


SELECT ATENDIME.CD_PACIENTE, ATENDIME.CD_MOT_ALT ,ATENDIME.NM_USUARIO_ALTA, ATENDIME.NM_USUARIO_ALTA_MEDICA, ATENDIME.NR_DECLARACAO_OBITO,
       ATENDIME.DT_DIAG, ATENDIME.DT_ALTA, ATENDIME.HR_ALTA, ATENDIME.DT_ALTA_MEDICA, ATENDIME.HR_ALTA_MEDICA, ATENDIME.CD_ATENDIMENTO,
       ATENDIME.DT_ATENDIMENTO, ATENDIME.HR_ATENDIMENTO, ATENDIME.CD_MULTI_EMPRESA, ATENDIME.CD_LEITO
FROM   DBAMV.ATENDIME
WHERE ATENDIME.CD_ATENDIMENTO In (787105,789544)   -- Alterar a Data e Hora de Alta


SELECT CD_LEITO, CD_ATENDIMENTO, DT_ATENDIMENTO, HR_ATENDIMENTO, DT_ALTA, HR_ALTA, NR_DECLARACAO_OBITO, ATENDIME.DT_DIAG
     , DT_ALTA_MEDICA, HR_ALTA_MEDICA FROM ATENDIME WHERE CD_ATENDIMENTO in (738366) -- Alterar a Data e Hora de Internação

SELECT CD_MOV_INT, DT_MOV_INT, HR_MOV_INT, DT_LIB_MOV, HR_LIB_MOV, CD_ATENDIMENTO FROM MOV_INT WHERE cd_leito = 1086
ORDER BY DT_MOV_INT DESC


SELECT CD_MOV_INT, DT_MOV_INT, HR_MOV_INT, DT_LIB_MOV, HR_LIB_MOV, CD_ATENDIMENTO, CD_LEITO FROM MOV_INT WHERE CD_ATENDIMENTO = 789544
ORDER BY HR_MOV_INT DESC



SELECT * FROM MOV_INT WHERE cd_leito = 974

alter session set nls_date_format = 'dd/mm/yyyy hh24:mi:ss' --- Alterar o formato da data.


Begin
  Pkg_Mv2000.Atribui_Empresa(2);  -->> Trocar a empresa e rodar uma vez para cada empresa (Caso seja Multi-Empresa
End;

alter trigger dbamv.trg_chk_dt_mov enable
alter trigger dbamv.trg_chk_dt_mov disable

alter trigger dbamv.trg_atendime_alt_paciente enable
alter trigger dbamv.trg_atendime_alt_paciente disable



SELECT * FROM DBAMV.MOV_INT WHERE CD_ATENDIMENTO = 410804
