SELECT 
       CD_PROTOCOLO,
       DT_SAIDA,
       HR_SAIDA,
       CD_PORTADOR,
       CD_PORTADOR_DESTINO,
       DS_MOTIVO,
       DS_SOLICITANTE,
       DT_PREV_RETORNO,
       DT_RETORNO,
       NM_USUARIO
  FROM DBAMV.PROTOCOLOS
 WHERE CD_PROTOCOLO IN
       (SELECT CD_PROTOCOLO
          FROM DBAMV.IT_SAME_PROTOCOLOS IT_SAME_PROTOCOLOS)
         --WHERE IT_SAME_PROTOCOLOS.CD_CAD_SAME = 2)
   and cd_protocolo = 8681
 order by CD_PROTOCOLO DESC for update
