---Sempre executar com o sistema de Nutrição aberto para ter certeza do status a ser alterado

SELECT * FROM MOV_CARDAPIO WHERE DT_MOV_CARDAPIO > '11/12/2007 10:51:55' AND CD_TIPO_REFEICAO = '9' --- MOVIMENTAÇÃO
DELETE FROM MOV_CARDAPIO WHERE DT_MOV_CARDAPIO > '11/12/2007 10:51:55' AND CD_TIPO_REFEICAO = '9' --- DELETE AS MOVIMENTAÇÕES

SELECT * FROM STATUS_REFEICAO WHERE CD_STATUS = 3845  -- STATUS
DELETE FROM STATUS_REFEICAO WHERE CD_STATUS = 3845 -- DELETE O STATUS

SELECT * FROM STATUS_REFEICAO WHERE CD_STATUS = 3844  -- STATUS ANTERIOR
SELECT TP_STATUS FROM STATUS_REFEICAO  WHERE CD_STATUS = 3844  -- ALTERAR O TP_STATUS (ABERTO = 'A' FECHADO = 'F')
