UPDATE ITORD_PRO SET QT_ATENDIDA = '170' WHERE QT_ATENDIDA IS NULL AND QT_CANCELADA = 0 AND QT_COMPRADA = '170'
AND QT_RECEBIDA = '170' AND CD_ORD_COM IN (
SELECT  ITORD_PRO.cd_ord_com 
FROM DBAMV.ITORD_PRO WHERE QT_ATENDIDA IS NULL 
AND QT_RECEBIDA IS NOT NULL
AND CD_ORD_COM IN (SELECT CD_ORD_COM FROM DBAMV.ORD_COM WHERE TP_SITUACAO = 'T'))
-------------------------------------------------------------------------------------------------

SELECT  cd_ord_com, cd_produto, qt_comprada, qt_recebida, qt_atendida, qt_cancelada
FROM    DBAMV.ITORD_PRO 
WHERE   QT_ATENDIDA IS NULL 
AND     QT_RECEBIDA IS NOT NULL
AND     CD_ORD_COM IN (SELECT CD_ORD_COM FROM DBAMV.ORD_COM WHERE TP_SITUACAO = 'T')
ORDER BY QT_RECEBIDA DESC

