SELECT * FROM DBAMV.CON_PAG WHERE CD_CON_PAG = 45235

SELECT CD_CON_PAG, CD_REDUZIDO,CD_ITEM_RES FROM DBAMV.RATCON_PAG WHERE CD_ITEM_RES = 295
AND CD_REDUZIDO <> 1645

UPDATE DBAMV.RATCON_PAG SET CD_REDUZIDO = 1645 WHERE CD_REDUZIDO <> 1645 AND CD_ITEM_RES = 295
