SELECT CD_MOV_INT, cd_leito, DT_MOV_INT, HR_MOV_INT, DT_LIB_MOV, HR_LIB_MOV FROM MOV_INT WHERE CD_ATENDIMENTO = 300922

SELECT DT_ATENDIMENTO, HR_ATENDIMENTO, CD_MOT_ALT ,NM_USUARIO_ALTA, NM_USUARIO_ALTA_MEDICA,
       DT_DIAG, DT_ALTA, HR_ALTA, DT_ALTA_MEDICA, HR_ALTA_MEDICA  FROM ATENDIME WHERE CD_ATENDIMENTO In ( 300922 ) -- Alterar a Data e Hora de Alta

SELECT DT_ATENDIMENTO, HR_ATENDIMENTO, cd_multi_empresa FROM ATENDIME WHERE CD_ATENDIMENTO = 130331 -- Alterar a Data e Hora de Internação

SELECT CD_PRO_INT_PROCEDIMENTO_ENTRAD FROM ATENDIME WHERE CD_ATENDIMENTO IN (2,3)

SELECT * FROM MVTO_ESTOQUE WHERE CD_ATENDIMENTO = 3304

SELECT * FROM MOV_INT WHERE CD_ATENDIMENTO = 91610

SELECT * FROM MOV_INT WHERE CD_LEITO = 1325 ORDER BY DT_MOV_INT DESC-- Alterar Data e Hora da Movimentação do Leito

SELECT DT_MOV_INT, HR_MOV_INT, DT_LIB_MOV, HR_LIB_MOV FROM MOV_INT WHERE CD_ATENDIMENTO = 91074

SELECT CD_MOV_INT,  DT_MOV_INT, HR_MOV_INT, DT_LIB_MOV, HR_LIB_MOV FROM MOV_INT WHERE CD_LEITO = 1325 ORDER BY CD_MOV_INT DESC

SELECT * FROM ATENDIME WHERE CD_ATENDIMENTO = 300922
alter session set nls_date_format = 'dd/mm/yyyy hh24:mi:ss'

UPDATE MOV_INT SET DT_LIB_MOV = '14/03/2007 00:00:00' WHERE CD_MOV_INT IN (17125,17127,17129,17132,17136)

select cd_atendimento, cd_convenio, cd_con_pla from atendime where cd_atendimento in (35353,35600) --- Convênio e Plano

SELECT TP_OCUPACAO FROM LEITO WHERE CD_LEITO = 56

DELETE FROM MOV_INT WHERE CD_ATENDIMENTO = 14936
DELETE  FROM ATENDIME WHERE CD_ATENDIMENTO = 14936
DELETE FROM LOG_DIARIA_AUTOMATICA WHERE CD_ATENDIMENTO = 14936
SELECT * FROM MVTO_GASES WHERE CD_ATENDIMENTO = 14936
DELETE LIGACAO_PACIENTE WHERE CD_ATENDIMENTO = 14936

Begin
  Pkg_Mv2000.Atribui_Empresa( 1 );  -->> Trocar a empresa e rodar uma vez para cada empresa
End;

select * from con_pla where cd_con_pla = 1

select * from atendime_pro_int

select * from atendime where cd_atendimento in (929932)for update

select * from atendime where cd_paciente in (59862, 156421)


select * from paciente where cd

SELECT * FROM REG_FAT WHERE CD_ATENDIMENTO = 85154


select cd_pro_int, cd_pro_int_procedimento_entrad, cd_ssm_cih from atendime where cd_atendimento IN (138973, 141725) -- ALTERAR O PROCEDIMENTO CIH
