SELECT UPPER(TRIM(UPPER(DBMS_LOB.SUBSTR(RC.LO_VALOR, 4000, 1)))), DC.CD_DOCUMENTO_CLINICO, ED.CD_DOCUMENTO, R.CD_REGISTRO, RC.CD_CAMPO, C.DS_IDENTIFICADOR /*INTO v_ds_resposta*/
  FROM DBAMV.EDITOR_REGISTRO R
 INNER JOIN DBAMV.EDITOR_REGISTRO_CAMPO RC
    ON R.CD_REGISTRO = RC.CD_REGISTRO
 INNER JOIN DBAMV.EDITOR_CAMPO C
    ON RC.CD_CAMPO = C.CD_CAMPO
 INNER JOIN DBAMV.PW_EDITOR_CLINICO EC
    ON R.CD_REGISTRO = EC.CD_EDITOR_REGISTRO
 INNER JOIN DBAMV.PW_DOCUMENTO_CLINICO DC
    ON EC.CD_DOCUMENTO_CLINICO = DC.CD_DOCUMENTO_CLINICO
 INNER JOIN DBAMV.PW_TIPO_DOCUMENTO PD
    ON DC.CD_TIPO_DOCUMENTO = PD.CD_TIPO_DOCUMENTO
 INNER JOIN DBAMV.EDITOR_DOCUMENTO ED
    ON EC.CD_DOCUMENTO = ED.CD_DOCUMENTO
 INNER JOIN DBAMV.ATENDIME AM
    ON AM.CD_ATENDIMENTO = DC.CD_ATENDIMENTO
 INNER JOIN DBAMV.PACIENTE PM
    ON PM.CD_PACIENTE  = AM.CD_PACIENTE
 WHERE AM.CD_ATENDIMENTO = 1488836--P_CD_ATENDIMENTO
   AND ED.CD_DOCUMENTO = 165--P_CD_DOCUMENTO -- PARÂMETRO QUAL DOCUMENTO
 /* AND TRIM(UPPER(C.DS_IDENTIFICADOR)) = TRIM(UPPER('DS_ANATOMIA_1'\*P_DS_IDENTIFICADOR*\)) -- PARÂMETRO QUAL ESPECIALIDADE
   AND DC.TP_STATUS = 'FECHADO'*/
   ;
   
select * from editor_registro_campo t
WHERE T.CD_CAMPO IN (/*49711,49742,49728,*/49724/*,49729*/) -- 49711(TRUE), 49724(1||NÃO), 49728(VAZIO), 49742(VAZIO)
--AND   T.CD_REGISTRO = 141335
FOR UPDATE
