SELECT * FROM DBAMV.PRODUTO WHERE DS_PRODUTO LIKE '%Õ%'


UPDATE PACIENTE SET NM_PACIENTE = REPLACE(NM_PACIENTE,' AD II ', ' AD IIG ')  WHERE NM_PACIENTE LIKE '%AD II %'


UPDATE DBAMV.PRODUTO SET PRODUTO.DS_PRODUTO = REPLACE(PRODUTO.DS_PRODUTO,'Õ', 'A')  WHERE PRODUTO.DS_PRODUTO LIKE '%Õ%'


Begin
  Pkg_Mv2000.Atribui_Empresa( 1 );  -->> Trocar a empresa e rodar uma vez para cada empresa
End;

