SELECT DS_ESPECIE,
       CD_PRODUTO,
       DS_PRODUTO,
       SUM(QT_ESTOQUE_INICIAL) QT_ESTOQUE_INICIAL,
       SUM(QT_ESTOQUE_INICIAL_SEM_TRANSF) QT_ESTOQUE_INICIAL_SEM_TRANSF,
       SUM(QT_ESTOQUE_FINAL) QT_ESTOQUE_FINAL,
       SUM(QT_ESTOQUE_FINAL_SEM_TRANSF) QT_ESTOQUE_FINAL_SEM_TRANSF,
       SUM(QT_ENTRADA) QT_ENTRADA,
       SUM(QT_ENTRADA_TRANSFERIDO) QT_ENTRADA_TRANSFERIDO,
       SUM(QT_SAIDA_SETOR) QT_SAIDA_SETOR,
       SUM(QT_SAIDA_PACIENTE) QT_SAIDA_PACIENTE,
       SUM(QT_BAIXA) QT_BAIXA,
       SUM(QT_VENDA) QT_VENDA,
       SUM(QT_EMPRESTIMO) QT_EMPRESTIMO,
       SUM(QT_EMPRESTIMO_entrada) QT_EMPRESTIMO_entrada,
       SUM(QT_ENT_EMPRESTIMO_RECEB) QT_ENT_EMPRESTIMO_RECEB,
       SUM(QT_SAI_PAG_EMPRESTIMO) QT_SAI_PAG_EMPRESTIMO,
       SUM(QT_ENT_PAG_EMPRESTIMO) QT_ENT_PAG_EMPRESTIMO,
       SUM(QT_SAI_EMPRESTIMO_CON) QT_SAI_EMPRESTIMO_CON,
       SUM(QT_DEVOLUCAO_SETOR) QT_DEVOLUCAO_SETOR,
       SUM(QT_DEVOLUCAO_PACIENTE) QT_DEVOLUCAO_PACIENTE,
       SUM(QT_DEVOLUCAO_VENDA) QT_DEVOLUCAO_VENDA,
       SUM(QT_DEMANDA) QT_DEMANDA,
       SUM(QT_TRANSFERENCIA_SAIDA) QT_TRANSFERENCIA_SAIDA,
       SUM(QT_DOACAO) QT_DOACAO,
       SUM(QT_MANIPULADA_ENTRADA) QT_MANIPULADA_ENTRADA,
       SUM(QT_MANIPULADA_SAIDA) QT_MANIPULADA_SAIDA,
       SUM(Decode(:p_tp_contagem,
                  'M',
                  qt_contagem_entrada,
                  Decode(Sign(nvl(QT_CONTAGEM_ENTRADA, 0) -
                              nvl(QT_CONTAGEM_SAIDA, 0)),
                         1,
                         nvl(QT_CONTAGEM_ENTRADA, 0) -
                         nvl(QT_CONTAGEM_SAIDA, 0),
                         0))) QT_CONTAGEM_ENTRADA,
       SUM(Decode(:p_tp_contagem,
                  'M',
                  qt_contagem_saida,
                  Decode(Sign(nvl(QT_CONTAGEM_SAIDA, 0) -
                              nvl(QT_CONTAGEM_ENTRADA, 0)),
                         1,
                         nvl(QT_CONTAGEM_SAIDA, 0) -
                         nvl(QT_CONTAGEM_ENTRADA, 0),
                         0))) QT_CONTAGEM_SAIDA,
       SUM(QT_DEVOLVIDA_FORNEC) QT_DEVOLVIDA_FORNEC,
       SUM(QT_VALE) QT_VALE,
       SUM(QT_TRANSF_EMP_SAI) QT_TRANSF_EMP_SAI,
       SUM(QT_TRANSF_EMP_ENT) QT_TRANSF_EMP_ENT,
       SUM(QT_NF_NAO_COBRADA) QT_NF_NAO_COBRADA,
       SUM(Decode(Sign(nvl(QT_ENTRADA_AJUSTE, 0) - nvl(QT_SAIDA_AJUSTE, 0)),
                  1,
                  nvl(QT_ENTRADA_AJUSTE, 0) - nvl(QT_SAIDA_AJUSTE, 0),
                  0)) QT_ENTRADA_AJUSTE,
       SUM(Decode(Sign(nvl(QT_SAIDA_AJUSTE, 0) - nvl(QT_ENTRADA_AJUSTE, 0)),
                  1,
                  nvl(QT_SAIDA_AJUSTE, 0) - nvl(QT_ENTRADA_AJUSTE, 0),
                  0)) QT_SAIDA_AJUSTE
  FROM (SELECT C_CONEST . CD_PRODUTO,
               ESPECIE . DS_ESPECIE,
               PRODUTO . DS_PRODUTO,
               SUM(decode(produto . sn_consignado,
                          'S',
                          C_CONEST . vl_ESTOQUE_INICIAL_consig,
                          C_CONEST . vl_ESTOQUE_INICIAL)) QT_ESTOQUE_INICIAL,
               SUM(decode(produto . sn_consignado,
                          'S',
                          C_CONEST . vl_ESTOQUE_INICIAL_consig,
                          C_CONEST . vl_ESTOQUE_INICIAL_SEM_TRANSF)) QT_ESTOQUE_INICIAL_SEM_TRANSF,
               SUM(decode(produto . sn_consignado,
                          'S',
                          C_CONEST . vl_ESTOQUE_FINAL_consig,
                          C_CONEST . vl_ESTOQUE_FINAL)) QT_ESTOQUE_FINAL,
               SUM(decode(produto . sn_consignado,
                          'S',
                          C_CONEST . vl_ESTOQUE_FINAL_consig,
                          C_CONEST . vl_ESTOQUE_FINAL_SEM_TRANSF)) QT_ESTOQUE_FINAL_SEM_TRANSF,
               SUM(C_CONEST . vl_ENTRADA) QT_ENTRADA,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_ENTRADA_TRANSFERIDO)) QT_ENTRADA_TRANSFERIDO,
               SUM(C_CONEST . vl_SAIDA_SETOR) QT_SAIDA_SETOR,
               SUM(C_CONEST . vl_SAIDA_PACIENTE) QT_SAIDA_PACIENTE,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_BAIXA)) QT_BAIXA,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_VENDA)) QT_VENDA,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_EMPRESTIMO)) QT_EMPRESTIMO,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_EMPRESTIMO_entrada)) QT_EMPRESTIMO_entrada,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_entrada_emprestimo_recebido)) QT_ENT_EMPRESTIMO_RECEB,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_saida_pag_emprestimo)) QT_SAI_PAG_EMPRESTIMO,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_entrada_pag_emprestimo)) QT_ENT_PAG_EMPRESTIMO,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_saida_emprestimo_concedido)) QT_SAI_EMPRESTIMO_CON,
               SUM(C_CONEST . vl_DEVOLUCAO_SETOR) QT_DEVOLUCAO_SETOR,
               SUM(C_CONEST . vl_DEVOLUCAO_PACIENTE) QT_DEVOLUCAO_PACIENTE,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_DEVOLUCAO_venda)) QT_DEVOLUCAO_VENDA,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_DEMANDA)) QT_DEMANDA,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_TRANSFERENCIA_SAIDA)) QT_TRANSFERENCIA_SAIDA,
               SUM(nvl(C_CONEST . vl_DOACAO, 0)) QT_DOACAO,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_MANIPULADA_ENTRADA)) QT_MANIPULADA_ENTRADA,
               SUM(decode(produto . sn_consignado,
                          'S',
                          0,
                          C_CONEST . vl_MANIPULADA_SAIDA)) QT_MANIPULADA_SAIDA,
               NVL(SUM(decode(produto . sn_consignado,
                              'S',
                              0,
                              nvl(C_CONEST . vl_CONTAGEM_ENTRADA, 0))),
                   0) QT_CONTAGEM_ENTRADA,
               NVL(SUM(decode(produto . sn_consignado,
                              'S',
                              0,
                              nvl(C_CONEST . vl_CONTAGEM_SAIDA, 0))),
                   0) QT_CONTAGEM_SAIDA,
               SUM(NVL(c_conest . vl_nota_fiscal_nao_cobrada, 0)) QT_NF_NAO_COBRADA,
               SUM(C_CONEST . vl_DEVOLVIDA_FORNEC) QT_DEVOLVIDA_FORNEC,
               SUM(nvl(C_CONEST . vl_VALE, 0)) QT_VALE,
               SUM(nvl(c_conest . vl_transf_emp_sai, 0)) QT_TRANSF_EMP_SAI,
               SUM(nvl(c_conest . vl_transf_emp_ent, 0)) QT_TRANSF_EMP_ENT,
               SUM(decode(dbamv .
                          fnc_mges_retorna_processo(to_date(to_char('01/2014') || '/' ||
                                                            to_char('01/2014'),
                                                            'MM/YYYY')),
                          'S',
                          NVL(C_CONEST . VL_ENTRADA_AJUSTE_CONTABIL, 0),
                          decode('51',
                                 '%',
                                 nvl(c_conest . vl_entrada_ajuste_contabil_sem,
                                     0),
                                 NVL(C_CONEST . VL_ENTRADA_AJUSTE_CONTABIL, 0)))) QT_ENTRADA_AJUSTE,
               SUM(decode(dbamv .
                          fnc_mges_retorna_processo(to_date(to_char('01/2014' || '/' ||
                                                            to_char('01/2014'),
                                                            'MM/YYYY')),
                          'S',
                          NVL(C_CONEST . VL_SAIDA_AJUSTE_CONTABIL, 0),
                          decode('51','%',
                                 nvl(c_conest . vl_saida_ajuste_contabil_sem,
                                     0),
                                 NVL(C_CONEST . VL_SAIDA_AJUSTE_CONTABIL, 0)))) QT_SAIDA_AJUSTE
          FROM DBAMV . C_CONEST,
               DBAMV . PRODUTO,
               DBAMV . ESPECIE,
               DBAMV . ESTOQUE
         WHERE C_CONEST . CD_PRODUTO = PRODUTO . CD_PRODUTO
           AND ESPECIE . CD_ESPECIE = PRODUTO . CD_ESPECIE
           AND PRODUTO . SN_MESTRE = 'N'
           AND PRODUTO.CD_ESPECIE = '2'
           AND ESTOQUE . CD_ESTOQUE = C_CONEST . CD_ESTOQUE
           AND PRODUTO.CD_PRODUTO = 50790
--           AND C_CONEST . CD_MES = 
--           AND C_CONEST . CD_ANO = 
--           And Estoque . Cd_Multi_Empresa = :P_Cd_Multi_Empresa
         GROUP BY C_CONEST . CD_PRODUTO, ESPECIE . DS_ESPECIE, DS_PRODUTO)
 Group By DS_ESPECIE, CD_PRODUTO, DS_PRODUTO
having ROUND(SUM(Decode(Sign(nvl(QT_ENTRADA_AJUSTE, 0) - nvl(QT_SAIDA_AJUSTE, 0)), 1, nvl(QT_ENTRADA_AJUSTE, 0) - nvl(QT_SAIDA_AJUSTE, 0), 0)), 2) <> 0 or ROUND(SUM(Decode(Sign(nvl(QT_SAIDA_AJUSTE, 0) - nvl(QT_ENTRADA_AJUSTE, 0)), 1, nvl(QT_SAIDA_AJUSTE, 0) - nvl(QT_ENTRADA_AJUSTE, 0), 0)), 2) <> 0
 ORDER BY 1 ASC, 2 ASC, 3 ASC, 4 ASC, 5 ASC, 6 ASC, 7 ASC, DS_ESPECIE
