------------ ANALISE DE ERROS BABYSAFE ----------------------------------
------------ BUSCAR OS REGISTROS DE ERROS PELO ATENDIMENTO --------------
SELECT * FROM BABYSAFE.REGISTRO_ERROS_PROCESSOS R
WHERE R.CD_ATENDIMENTO_FILHO = 1536955--1536955-- COLOCAR O ATENDIMENTO (ATENDIMENTO PAI)
;
------------ BUSCAR OS REGISTROS DE ERROS NO LOG DA TABELA DO BABYSAFE ------------
------------ VERIFICAR SE UM PROCESSO FOI FEITO ENQUANTO O PALM ESTAVA OFFLINE ----
------------ NORMALMENTE OCORRE ERRO NO PROCESSO 5 (ALTA DA ENFERMAGEM) -----------
SELECT * FROM BABYSAFE.LOG_PROCESSO L
WHERE L.DESCRICAO_LOG LIKE '%1536955%'
;
------------ EXCLUIR LOG INCORRETO ---------------
SELECT * FROM BABYSAFE.REGISTRO_ERROS_PROCESSOS R
WHERE R.ID_LOG_ERROS = 9611 -- DIGITAR A ID_LOG_ERRO
FOR UPDATE
;
