SELECT PACIENTE.CD_PACIENTE                                 
     , ATENDIME.CD_ATENDIMENTO
     , PACIENTE.NM_PACIENTE                                    PACIENTE
     , ATENDIME.DT_ATENDIMENTO        
     , TO_CHAR(ATENDIME.HR_ATENDIMENTO,'HH24:MI')              HORA
     , ATENDIME.CD_ATENDIMENTO_PAI                             PAI
     , ATENDIME.CD_SERVICO
     , ATENDIME.CD_SERVICO_SAIDA                               SER_SAIDA
     , (SELECT MAE.CD_ATENDIMENTO || '  -  ' || PAC.NM_PACIENTE  || '  -  ' || MAE.CD_SERVICO || '  -  ' || SERVICO.DS_SERVICO
        FROM   DBAMV.ATENDIME MAE, DBAMV.PACIENTE PAC, DBAMV.SERVICO
        WHERE  PAC.CD_PACIENTE    = MAE.CD_PACIENTE
        AND    MAE.CD_SERVICO     = SERVICO.CD_SERVICO(+)
        AND    MAE.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO_PAI) MAE     
      
    
        
FROM   DBAMV.PACIENTE
     , DBAMV.ATENDIME

WHERE  PACIENTE.CD_PACIENTE             =            ATENDIME.CD_PACIENTE
AND    ATENDIME.TP_ATENDIMENTO          =   'I'
AND    ATENDIME.CD_ATENDIMENTO_PAI      IS NOT NULL
AND    ATENDIME.CD_SERVICO              IS NULL
AND    ATENDIME.DT_ALTA                 IS NOT NULL
AND    TRUNC(ATENDIME.DT_ATENDIMENTO)   BETWEEN TO_DATE('01/01/2010','DD/MM/YYYY') AND TO_DATE('31/12/2010','DD/MM/YYYY')
ORDER BY DT_ATENDIMENTO, HORA

/*
UPDATE DBAMV.ATENDIME
SET    CD_SERVICO_SAIDA    = 28
WHERE  CD_SERVICO_SAIDA   IS NULL 
AND    CD_SERVICO         IS NULL
AND    CD_ATENDIMENTO_PAI IS NOT NULL
AND    DT_ALTA            IS NOT NULL
AND    TRUNC(ATENDIME.DT_ATENDIMENTO)   BETWEEN TO_DATE('01/01/2010','DD/MM/YYYY') AND TO_DATE('31/12/2010','DD/MM/YYYY')

Begin
  Pkg_Mv2000.Atribui_Empresa( 1 );  -->> Trocar a empresa e rodar uma vez para cada empresa
End;
*/
