SELECT 1 TIPO,
       0 SUBTIPO,
       NULL CD_ITPRE_MED,
       NULL CD_TIP_PRESC,
       TO_DATE(TO_CHAR(PM.DH_IMPRESSAO, 'DD/MM/YYYY HH24:MI'),'DD/MM/YYYY HH24:MI') DT_HR,
       TO_CHAR(PM.DH_IMPRESSAO, 'DD/MM - HH24:MI') DT_HR_EXIBE,
       'PRESCRIÇÃO: ' || PM.CD_PRE_MED || ' --> TIPO: ' || (SELECT CASE WHEN PM.CD_OBJETO IN (21,481) THEN 'PRESCRICAO DE INTERNACAO.' ELSE 'PRESCRIÇÃO MEDICA' END TIPO FROM DUAL) CODIGO ,      
       'DR(A) ' || PR.NM_PRESTADOR DESCRICAO,
       NULL DH_MEDICACAO,
       '' QUANTIDADE,
       NULL UNIDADE,
       NULL COLABORADOR
FROM   DBAMV.PRE_MED PM INNER JOIN DBAMV.PRESTADOR PR ON PR.CD_PRESTADOR = PM.CD_PRESTADOR
WHERE  PM.CD_PRE_MED = #PRESCRICAO#
AND    PM.TP_PRE_MED = 'M'
----------
UNION ALL
----------
SELECT 0 TIPO,
       0 SUBTIPO,
       NULL CD_ITPRE_MED,
       NULL CD_TIP_PRESC,
       NULL DT_HR,
       NULL DT_HR_EXIBE,
       'PACIENTE: ' || PC.NM_PACIENTE || ' ( ATENDIMENTO: ' || AT.CD_ATENDIMENTO || ' )' CODIGO,
       NULL DESCRICAO,
       NULL DH_MEDICACAO,
       '' QUANTIDADE, 
       NULL UNIDADE,
       NULL COLABORADOR
FROM   DBAMV.PRE_MED PM INNER JOIN DBAMV.ATENDIME AT ON AT.CD_ATENDIMENTO = PM.CD_ATENDIMENTO
                        INNER JOIN DBAMV.PACIENTE PC ON PC.CD_PACIENTE    = AT.CD_PACIENTE
WHERE  PM.CD_PRE_MED = #PRESCRICAO#
AND    PM.TP_PRE_MED = 'M'
----------
UNION ALL
----------
SELECT 2 TIPO,
       0 SUBTIPO,
       NULL CD_ITPRE_MED,
       NULL CD_TIP_PRESC,
       NULL DT_HR,
       NULL DT_HR_EXIBE,
       NULL CODIGO,
       'UNIDADE: ' || UI.DS_UNID_INT DESCRICAO,
       NULL DH_MEDICACAO,
       '' QUANTIDADE,
       NULL UNIDADE,
       NULL COLABORADOR
FROM   DBAMV.PRE_MED PM INNER JOIN DBAMV.UNID_INT UI ON Ui.CD_UNID_INT = PM.CD_UNID_INT
WHERE  PM.CD_PRE_MED = #PRESCRICAO#
AND    PM.TP_PRE_MED = 'M'
----------
UNION ALL
----------
SELECT 2.1 TIPO,
       0 SUBTIPO,
       NULL CD_ITPRE_MED,
       NULL CD_TIP_PRESC,
       NULL DT_HR,
       NULL DT_HR_EXIBE,
       NULL CODIGO,
       'VALIDADE: ' || TO_CHAR(PM.DT_VALIDADE, 'DD/MM/YYYY HH24:MI') DESCRICAO,
       NULL DH_MEDICACAO,
       '' QUANTIDADE,
       NULL UNIDADE,
       NULL COLABORADOR
FROM   DBAMV.PRE_MED PM INNER JOIN DBAMV.PRESTADOR PR ON PR.CD_PRESTADOR = PM.CD_PRESTADOR
WHERE  PM.CD_PRE_MED = #PRESCRICAO#
AND    PM.TP_PRE_MED = 'M'
----------
UNION ALL
----------
SELECT 2.2 TIPO,
       0 SUBTIPO,
       NULL CD_ITPRE_MED,
       NULL CD_TIP_PRESC,
       NULL DT_HR,
       NULL DT_HR_EXIBE,
       NULL CODIGO,
       'PROCEDIMENTO: ' || (SELECT C.DS_CIRURGIA FROM DBAMV.AVISO_CIRURGIA AC INNER JOIN DBAMV.CIRURGIA_AVISO CA ON CA.CD_AVISO_CIRURGIA = AC.CD_AVISO_CIRURGIA 
                                                 INNER JOIN DBAMV.CIRURGIA       C  ON CA.CD_CIRURGIA = C.CD_CIRURGIA
                                                 WHERE CA.SN_PRINCIPAL = 'S'
                                                 AND   AC.CD_ATENDIMENTO = (SELECT DISTINCT PM1.CD_ATENDIMENTO FROM DBAMV.PRE_MED PM1 
                                                                             WHERE PM1.CD_PRE_MED = PM.CD_PRE_MED)
                                                 AND AC.CD_AVISO_CIRURGIA = (SELECT MAX(AC1.CD_AVISO_CIRURGIA) FROM DBAMV.AVISO_CIRURGIA AC1 INNER JOIN DBAMV.CIRURGIA_AVISO CA1 ON CA1.CD_AVISO_CIRURGIA = AC1.CD_AVISO_CIRURGIA 
                                                 INNER JOIN DBAMV.CIRURGIA       C1  ON CA1.CD_CIRURGIA = C1.CD_CIRURGIA
                                                 WHERE CA1.SN_PRINCIPAL = 'S'
                                                 AND   AC1.CD_ATENDIMENTO = (SELECT DISTINCT PM1.CD_ATENDIMENTO FROM DBAMV.PRE_MED PM1 
                                                                             WHERE PM1.CD_PRE_MED = PM.CD_PRE_MED))) DESCRICAO,                                                                                                                         
       NULL DH_MEDICACAO,
       '' QUANTIDADE,
       NULL UNIDADE,
       NULL COLABORADOR
FROM   DBAMV.PRE_MED PM INNER JOIN DBAMV.PRESTADOR PR ON PR.CD_PRESTADOR = PM.CD_PRESTADOR
WHERE  PM.CD_PRE_MED = #PRESCRICAO#
AND    PM.TP_PRE_MED = 'M'
----------
UNION ALL
----------

SELECT 3 TIPO,
       0 SUBTIPO,
       NULL CD_ITPRE_MED,
       NULL CD_TIP_PRESC,
       NULL DT_HR,
       'DH CONCLUÍDO' DT_HR_EXIBE,
       'MOVIMENTAÇÕES DO ATENDIMENTO' CODIGO,
       '' DESCRICAO,       
       NULL DH_MEDICACAO,
       '' QUANTIDADE,
       'AÇÃO GERADA PELA MOVIMENTAÇÃO' UNIDADE,
       'COLABORADOR' COLABORADOR
FROM   DUAL

-----------
UNION ALL
-----------

SELECT 
       4 TIPO,
       0.2 SUBTIPO,
       0.2 CD_ITPRE_MED,
       NULL CD_TIP_PRESC,
       NULL DH_MODIFICACAO,
       TO_CHAR(R.DT_LOG_TRANSF_CC,'DD/MM   -   HH24:MI') DT_HR_EXIBE,
       'ENTRADA NO '||DECODE(LG.CD_SETOR_DESTINO_COCC,14,'C.O.',15,'C.C.',135,'CO/CC')||': '|| LG.CD_AVISO_CIRURGIA  CODIGO,
       '--->     '|| fnc_hmsj_obtem_ds_leito (LG.CD_LEITO_ORIG)|| '     =>>     ' || DECODE(LG.CD_SETOR_DESTINO_COCC,14,'C.O.',15,'C.C.',135,'CO/CC') DESCRICAO,
       
       R.DT_LOG_TRANSF_CC DH_MEDICACAO,
       ''|| DECODE (TO_DATE(fnc_hmsj_setor_dtpresc (p.cd_pre_med, p.Dh_Criacao),'DD/MM/YYYY HH24:MI:SS'),LG.DT_ENTRADA_COCC,'X','') QUANTIDADE,
       DECODE (fnc_hmsj_canc_pm2(LG.CD_SETOR_ORIG, LG.CD_SETOR_DESTINO_COCC),'A','SUBSTITUIR COM BASE NO APRAZ','C','CANCELAR AS SOL EM ABERTO','S','SUBSTITUIR AS SOL EM ABERTO','-') UNIDADE,
       (SELECT US.NM_USUARIO
        FROM   DBASGU.USUARIOS US
        WHERE  US.CD_USUARIO = R.NM_USUARIO) COLABORADOR
       
 FROM 
DBAMV.PRE_MED P, 
DBAMV.MOV_CC_RPA R
,DBAMV.HMSJ_LOG_ENTRADA_COCC LG
WHERE 1=1
AND P.CD_ATENDIMENTO = R.CD_ATENDIMENTO
AND LG.CD_MOV_CC_RPA (+) = R.CD_MOV_CC_RPA
AND LG.CD_ATENDIMENTO (+) = R.CD_ATENDIMENTO
AND P.CD_PRE_MED = #PRESCRICAO#
AND P.TP_PRE_MED = 'M'

----------
UNION ALL
----------
SELECT 
       4 TIPO,
       0.2 SUBTIPO,
       0.2 CD_ITPRE_MED,
       NULL CD_TIP_PRESC,
       NULL DH_MODIFICACAO,
       TO_CHAR(r.dt_log_rpa,'DD/MM   -   HH24:MI') DT_HR_EXIBE,
       'SAIDA DO '||DECODE(LG.CD_SETOR_DESTINO_COCC,14,'C.O.',15,'C.C.',135,'CO/CC')||': '|| LG.CD_AVISO_CIRURGIA CODIGO,
              '--->     '|| DECODE(LG.CD_SETOR_DESTINO_COCC,14,'C.O.',15,'C.C.',135,'CO/CC')|| '     =>>     ' || fnc_hmsj_obtem_ds_leito (LG.CD_LEITO_DESTINO)  DESCRICAO,
       
       r.dt_log_rpa DH_MEDICACAO,
       ''|| DECODE (TO_DATE(fnc_hmsj_setor_dtpresc (p.cd_pre_med, p.Dh_Criacao),'DD/MM/YYYY HH24:MI:SS'),LG.DT_SAIDA_COCC,'X','') QUANTIDADE,
       DECODE (fnc_hmsj_canc_pm2(LG.CD_SETOR_DESTINO_COCC, LG.CD_SETOR_DESTINO_AND),'A','SUBSTITUIR COM BASE NO APRAZ','C','CANCELAR AS SOL EM ABERTO','S','SUBSTITUIR AS SOL EM ABERTO','-') UNIDADE,
       (SELECT US.NM_USUARIO
        FROM   DBASGU.USUARIOS US
        WHERE  US.CD_USUARIO = R.NM_USUARIO) COLABORADOR
       
 FROM 
DBAMV.PRE_MED P, 
DBAMV.MOV_CC_RPA R
,DBAMV.HMSJ_LOG_ENTRADA_COCC LG
WHERE 1=1
AND P.CD_ATENDIMENTO = R.CD_ATENDIMENTO
AND LG.CD_MOV_CC_RPA (+) = R.CD_MOV_CC_RPA
AND LG.CD_ATENDIMENTO (+) = R.CD_ATENDIMENTO
AND P.CD_PRE_MED = #PRESCRICAO#
AND P.TP_PRE_MED = 'M'

----------
UNION ALL
----------

SELECT 4 TIPO,
       0.2 SUBTIPO,
       0.2 CD_ITPRE_MED,
       NULL CD_TIP_PRESC,
       NULL DH_MODIFICACAO,
       TO_CHAR(I.Hr_Mov_Int,'DD/MM   -   HH24:MI')  DT_HR_EXIBE,
       'CÓD. MOV INT: '|| I.CD_MOV_INT ||' - '||DECODE(I.TP_MOV,'O', 'TRANSFERÊNCIA', 'I','INTERNAÇÃO') CODIGO,
       
CASE WHEN I.TP_MOV = 'O' 
     THEN '--->   '|| fnc_hmsj_obtem_ds_leito (I.CD_LEITO_ANTERIOR)|| '  =>>   ' || fnc_hmsj_obtem_ds_leito(I.CD_LEITO)
     
     WHEN I.TP_MOV = 'I'
     THEN '--->   '|| fnc_hmsj_obtem_ds_leito (I.CD_LEITO)
     
     ELSE
       'ERROR'
     
            END   
       DESCRICAO,      
      
       I.HR_MOV_INT DH_MEDICACAO,
       ''|| DECODE (TO_DATE(fnc_hmsj_setor_dtpresc (p.cd_pre_med, p.Dh_Criacao),'DD/MM/YYYY HH24:MI:SS'),I.Hr_Mov_Int,'X','') QUANTIDADE,
       DECODE (fnc_hmsj_canc_pm(I.CD_LEITO_ANTERIOR, I.CD_LEITO),'A','SUBSTITUIR COM BASE NO APRAZ','C','CANCELAR AS SOL EM ABERTO','S','SUBSTITUIR AS SOL EM ABERTO','-') UNIDADE,
       (SELECT US.NM_USUARIO
        FROM   DBASGU.USUARIOS US
        WHERE  US.CD_USUARIO = I.NM_USUARIO) COLABORADOR
FROM 
DBAMV.MOV_INT I,
DBAMV.PRE_MED P
WHERE 1=1
AND I.CD_ATENDIMENTO = P.CD_ATENDIMENTO
AND P.CD_PRE_MED =#PRESCRICAO#
AND P.TP_PRE_MED = 'M'

----------
UNION ALL
----------

SELECT 4 TIPO,
       0 SUBTIPO,
       1 CD_ITPRE_MED,
       1 CD_TIP_PRESC,
       NULL DT_HR,
       'DATA/HORÁRIO' DT_HR_EXIBE,
       'AÇÃO' CODIGO,
       'ITEM' DESCRICAO,
       NULL DH_MEDICACAO,
       'QTD' QUANTIDADE,
       'UNIDADE' UNIDADE,
       'COLABORADOR' COLABORADOR
FROM   DUAL

----------
UNION ALL
----------

SELECT 4 TIPO,
       1 SUBTIPO,
       IT.CD_ITPRE_MED,
       IT.CD_TIP_PRESC,
       NULL DT_HR,
       CASE WHEN NVL(IT.SN_URGENTE, 'N') = 'S' 
            THEN 'URGENTE'
            ELSE ''
       END DT_HR_EXIBE,
       NULL CODIGO,
       TP.DS_TIP_PRESC || ' ( ' || UPPER(TF.DS_TIP_FRE) || ' )' DESCRICAO,
       NULL DH_MEDICACAO,
       TO_CHAR(IT.QT_ITPRE_MED) QUANTIDADE,
       (SELECT UN.DS_UNIDADE
        FROM   DBAMV.UNI_PRO UN
        WHERE  UN.CD_UNI_PRO = IT.CD_UNI_PRO) UNIDADE,
       NULL COLABORADOR
FROM   DBAMV.PRE_MED PM INNER JOIN DBAMV.ITPRE_MED IT ON IT.CD_PRE_MED   = PM.CD_PRE_MED
                        INNER JOIN DBAMV.TIP_PRESC TP ON TP.CD_TIP_PRESC = IT.CD_TIP_PRESC
                        LEFT  JOIN DBAMV.TIP_FRE   TF ON TF.CD_TIP_FRE   = IT.CD_TIP_FRE
                        LEFT  JOIN DBAMV.FOR_APL   FA ON FA.CD_FOR_APL   = IT.CD_FOR_APL
WHERE  PM.CD_PRE_MED = #PRESCRICAO#
AND    PM.TP_PRE_MED = 'M' 
AND    NOT TP.CD_PRODUTO IS NULL
----------
UNION  ALL
----------
SELECT 4 TIPO,
       2 SUBTIPO,
       LG.CD_ITPRE_MED,
       NULL CD_TIP_PRESC,
       LG.DH_MODIFICACAO DT_HR,
       TO_CHAR(LG.DH_MODIFICACAO,'DD/MM   -   HH24:MI') DT_HR_EXIBE,
       'APRAZAMENTO' CODIGO,
       '----->   ' || TO_CHAR(LG.DH_MEDICACAO,'DD/MM - HH24:MI') || '    =>>    ' ||  TO_CHAR(LG.DH_MEDICACAO_NOVA,'DD/MM - HH24:MI')  DESCRICAO,
       LG.DH_MEDICACAO,
       '' QUANTIDADE,
       NULL UNIDADE,
       (SELECT US.NM_USUARIO
        FROM   DBASGU.USUARIOS US
        WHERE  US.CD_USUARIO = LG.CD_ID_USUARIO) COLABORADOR
FROm   DBAMV.LOG_HRITPRE_MED LG INNER JOIN DBAMV.ITPRE_MED IT ON IT.CD_ITPRE_MED = LG.CD_ITPRE_MED
                                INNER JOIN DBAMV.TIP_PRESC TP ON TP.CD_TIP_PRESC = IT.CD_TIP_PRESC
WHERE  IT.CD_PRE_MED = #PRESCRICAO#
AND    NOT TP.CD_PRODUTO IS NULL
AND    LG.CD_ID_USUARIO <> (SELECT PM.NM_USUARIO FROM DBAMV.PRE_MED PM WHERE PM.CD_PRE_MED = IT.CD_PRE_MED)
AND    EXISTS (SELECT 'X' 
               FROM   DBASGU.PAPEL_USUARIOS PU INNER JOIN DBASGU.PAPEL PA ON PA.CD_PAPEL = PU.CD_PAPEL
               WHERE  LG.CD_ID_USUARIO = PU.CD_USUARIO
               AND    PA.DS_PAPEL LIKE '%ENF%' )
----------
UNION ALL
----------
SELECT 4 TIPO,
       3 SUBTIPO,
       AI.CD_ITPRE_MED,
       NULL CD_TIP_PRESC,
       DC.DH_FECHAMENTO DT_HR,
       TO_CHAR(DC.DH_FECHAMENTO,'DD/MM   -   HH24:MI') DT_HR_EXIBE,
       'ANÁLISE FARMACÊUTICA: ' || AP.CD_AVALIACAO_PRE_MED CODIGO,
       '---------->   LIBERAÇÃO ' || CASE WHEN AP.TP_AVALIACAO = 'MAN' THEN 'MANUAL'
                                      WHEN AP.TP_AVALIACAO = 'AUT' THEN 'AUTOMÁTICA'
                                      ELSE ''
                                 END DESCRICAO,                         
       NULL DH_MEDICACAO,
       NULL QUANTIDADE,
       NULL UNIDADE, 
       (SELECT US.NM_USUARIO
        FROM   DBASGU.USUARIOS US
        WHERE  US.CD_USUARIO = DC.CD_USUARIO) COLABORADOR
FROM   DBAMV.PW_AVALIACAO_PRE_MED  AP INNER JOIN DBAMV.PW_AVALIACAO_ITPRE_MED AI ON AI.CD_AVALIACAO_PRE_MED = AP.CD_AVALIACAO_PRE_MED
                                      INNER JOIN DBAMV.PW_DOCUMENTO_CLINICO   DC ON DC.CD_DOCUMENTO_CLINICO = AP.CD_DOCUMENTO_CLINICO
                                      INNER JOIN DBAMV.ITPRE_MED              IT ON IT.CD_ITPRE_MED         = AI.CD_ITPRE_MED
                                      INNER JOIN DBAMV.TIP_PRESC              TP ON TP.CD_TIP_PRESC         = IT.CD_TIP_PRESC
WHERE  AP.CD_PRE_MED = #PRESCRICAO#
AND    NOT TP.CD_PRODUTO IS NULL
----------
UNION ALL
----------
SELECT 4 TIPO,
       4 SUBTIPO,
       LG.CD_ITPRE_MED,
       NULL CD_TIP_PRESC,
       LG.DH_MODIFICACAO DT_HR,
       TO_CHAR(LG.DH_MODIFICACAO,'DD/MM   -   HH24:MI') DT_HR_EXIBE,
       'ANÁLISE FARMACÊUTICA' CODIGO,
       '---------->   ' || TO_CHAR(LG.DH_MEDICACAO,'DD/MM - HH24:MI') || '    =>>    ' ||  TO_CHAR(LG.DH_MEDICACAO_NOVA,'DD/MM - HH24:MI')  DESCRICAO,
       LG.DH_MEDICACAO,
       '' QUANTIDADE,
       NULL UNIDADE,
       (SELECT US.NM_USUARIO
        FROM   DBASGU.USUARIOS US
        WHERE  US.CD_USUARIO = LG.CD_ID_USUARIO) COLABORADOR
FROM   DBAMV.LOG_HRITPRE_MED LG INNER JOIN DBAMV.ITPRE_MED IT ON IT.CD_ITPRE_MED = LG.CD_ITPRE_MED
                                INNER JOIN DBAMV.TIP_PRESC TP ON TP.CD_TIP_PRESC = IT.CD_TIP_PRESC
WHERE  IT.CD_PRE_MED = #PRESCRICAO#
AND    NOT TP.CD_PRODUTO IS NULL
AND    LG.CD_ID_USUARIO <> (SELECT PM.NM_USUARIO FROM DBAMV.PRE_MED PM WHERE PM.CD_PRE_MED = IT.CD_PRE_MED)
AND    EXISTS (SELECT 'X' 
               FROM   DBASGU.PAPEL_USUARIOS PU INNER JOIN DBASGU.PAPEL PA ON PA.CD_PAPEL = PU.CD_PAPEL
               WHERE  LG.CD_ID_USUARIO = PU.CD_USUARIO
               AND    PA.DS_PAPEL LIKE '%FAR%' )
----------
UNION ALL
----------
SELECT 4 TIPO,
       5 SUBTIPO,
       IT.CD_ITPRE_MED,
       IT.CD_TIP_PRESC,
       SP.DT_GRAVACAO DT_HR, 
       TO_CHAR(SP.DT_GRAVACAO,'DD/MM   -   HH24:MI') DT_HR_EXIBE,
       'GERAÇÂO FARMÁCIA ( SOLICITAÇÃO: ' || SP.CD_SOLSAI_PRO || ' )'CODIGO,
       '-------------->   ' || PD.DS_PRODUTO || ' ( TURNO: ' || TO_CHAR(SP.HR_SOLSAI_PRO,'DD/MM - HH24:MI') || ' )' DESCRICAO,     
       NULL DH_MEDICACAO,
       TO_CHAR(IT.QT_SOLICITADO) QUANTIDADE,
       (SELECT UN.DS_UNIDADE
        FROM   DBAMV.UNI_PRO UN
        WHERE  UN.CD_UNI_PRO = IT.CD_UNI_PRO) UNIDADE,     
       NULL COLABORADOR
FROM   DBAMV.SOLSAI_PRO SP INNER JOIN DBAMV.ITSOLSAI_PRO IT ON IT.CD_SOLSAI_PRO = SP.CD_SOLSAI_PRO
                           INNER JOIN DBAMV.TIP_PRESC    TP ON TP.CD_TIP_PRESC  = IT.CD_TIP_PRESC
                           INNER JOIN DBAMV.PRODUTO      PD ON PD.CD_PRODUTO    = IT.CD_PRODUTO
WHERE  SP.CD_PRE_MED = #PRESCRICAO#
AND    NOT TP.CD_PRODUTO IS NULL
----------
UNION ALL
----------
SELECT 4 TIPO,
       6 SUBTIPO,
       EI.CD_ITPRE_MED,
       EI.CD_TIP_PRESC,
       ES.DT_EXCLUSAO DT_HR, 
       TO_CHAR(ES.DT_EXCLUSAO,'DD/MM   -   HH24:MI') DT_HR_EXIBE,
       'EXCLUSÃO FARMÁCIA ( SOLICITAÇÃO: ' || ES.CD_SOLSAI_PRO || ' )'CODIGO,
       '-------------->   ' || PD.DS_PRODUTO DESCRICAO,   
       NULL DH_MEDICACAO,
       TO_CHAR(EI.QT_SOLICITADO) QUANTIDADE,
       (SELECT UN.DS_UNIDADE
        FROM   DBAMV.UNI_PRO UN
        WHERE  UN.CD_UNI_PRO = EI.CD_UNI_PRO) UNIDADE,     
       (SELECT US.NM_USUARIO
        FROM   DBASGU.USUARIOS US
        WHERE  US.CD_USUARIO = EI.NM_USUARIO) COLABORADOR
FROM   DBAMV.EXCLUI_SOLSAI_PRO ES INNER JOIN DBAMV.EXCLUI_ITSOLSAI_PRO EI ON EI.CD_SOLSAI_PRO = ES.CD_SOLSAI_PRO
                                  INNER JOIN DBAMV.TIP_PRESC           TP ON TP.CD_TIP_PRESC  = EI.CD_TIP_PRESC
                                  INNER JOIN DBAMV.PRODUTO             PD ON PD.CD_PRODUTO    = EI.CD_PRODUTO
WHERE  ES.CD_PRE_MED = #PRESCRICAO#
AND    NOT TP.CD_PRODUTO IS NULL
----------
UNION ALL
----------
SELECT DISTINCT
       4 TIPO,
       7 SUBTIPO,
       IT.CD_ITPRE_MED,
       IT.CD_TIP_PRESC,
       ME.HR_MVTO_ESTOQUE DT_HR, 
       TO_CHAR(ME.HR_MVTO_ESTOQUE,'DD/MM   -   HH24:MI') DT_HR_EXIBE,
       'SEPARAÇÃO ESTOQUE ( MOVIMENTAÇÃO: ' || ME.CD_MVTO_ESTOQUE || ' )'CODIGO,       
       '------------------>   ' || PD.DS_PRODUTO || ' (SOLICITAÇÃO:' || SP.CD_SOLSAI_PRO || ' )'DESCRICAO,
       NULL DH_MEDICACAO,
       TO_CHAR(IM.QT_MOVIMENTACAO) QUANTIDADE,
       (SELECT UN.DS_UNIDADE
        FROM   DBAMV.UNI_PRO UN
        WHERE  UN.CD_UNI_PRO = IT.CD_UNI_PRO) UNIDADE,       
        (SELECT US.NM_USUARIO
        FROM   DBASGU.USUARIOS US
        WHERE  US.CD_USUARIO = ME.CD_USUARIO) COLABORADOR 
FROM   DBAMV.SOLSAI_PRO SP INNER JOIN DBAMV.ITSOLSAI_PRO   IT  ON IT.CD_SOLSAI_PRO   = SP.CD_SOLSAI_PRO
                           INNER JOIN DBAMV.MVTO_ESTOQUE   ME  ON ME.CD_SOLSAI_PRO   = SP.CD_SOLSAI_PRO
                           INNER JOIN DBAMV.ITMVTO_ESTOQUE IM  ON IM.CD_MVTO_ESTOQUE = ME.CD_MVTO_ESTOQUE
                                                              AND IM.CD_ITSOLSAI_PRO = IT.CD_ITSOLSAI_PRO
                           INNER JOIN DBAMV.TIP_PRESC      TP  ON TP.CD_TIP_PRESC    = IT.CD_TIP_PRESC
                           INNER JOIN DBAMV.PRODUTO        PD ON PD.CD_PRODUTO       = IT.CD_PRODUTO
WHERE  SP.CD_PRE_MED = #PRESCRICAO#
AND    NOT TP.CD_PRODUTO IS NULL
----------
UNION ALL
----------
SELECT DISTINCT
       4 TIPO,
       8 SUBTIPO,
       IT.CD_ITPRE_MED,
       IT.CD_TIP_PRESC,
       ME.HR_ENTREGA DT_HR, 
       TO_CHAR(ME.HR_ENTREGA,'DD/MM   -   HH24:MI') DT_HR_EXIBE,
       'ENTREGA ( MOVIMENTAÇÃO: ' || ME.CD_MVTO_ESTOQUE || ' )' CODIGO,       
       '---------------------->   ENTREGUE POR ' || (SELECT US.NM_USUARIO
                                                     FROM   DBASGU.USUARIOS US
                                                     WHERE  US.CD_USUARIO = ME.CD_USUARIO_ENTREGA) DESCRICAO,                                             
       NULL DH_MEDICACAO,
       NULL QUANTIDADE,
       NULL UNIDADE,       
       (SELECT US.NM_USUARIO
        FROM   DBASGU.USUARIOS US
        WHERE  US.CD_USUARIO = ME.NM_RECEBIDO) COLABORADOR
FROM   DBAMV.SOLSAI_PRO SP INNER JOIN DBAMV.ITSOLSAI_PRO   IT  ON IT.CD_SOLSAI_PRO   = SP.CD_SOLSAI_PRO
                           INNER JOIN DBAMV.MVTO_ESTOQUE   ME  ON ME.CD_SOLSAI_PRO   = SP.CD_SOLSAI_PRO
                           INNER JOIN DBAMV.ITMVTO_ESTOQUE IM  ON IM.CD_MVTO_ESTOQUE = ME.CD_MVTO_ESTOQUE
                                                              AND IM.CD_ITSOLSAI_PRO = IT.CD_ITSOLSAI_PRO
                           INNER JOIN DBAMV.TIP_PRESC      TP  ON TP.CD_TIP_PRESC    = IT.CD_TIP_PRESC                    
WHERE  SP.CD_PRE_MED = #PRESCRICAO#
AND    NOT TP.CD_PRODUTO IS NULL
AND    NOT ME.HR_ENTREGA IS NULL
ORDER  BY TIPO, CD_ITPRE_MED, SUBTIPO,  DT_HR , DH_MEDICACAO, CODIGO

