Verifica se os objetos est o inv lidos
SELECT OBJECT_TYPE, OBJECT_NAME, STATUS FROM ALL_OBJECTS WHERE STATUS='INVALID' AND OWNER LIKE 'BABY%';

Gera script para compilar objetos
SELECT 'ALTER '|| OBJECT_TYPE ||' '|| OWNER || '.' || OBJECT_NAME ||' COMPILE;' FROM ALL_OBJECTS WHERE STATUS='INVALID' AND OWNER LIKE 'BABY%';

Exemplo:
ALTER FUNCTION BABYSAFE.FNC_RN_GEMELAR COMPILE;
ALTER VIEW BABYSAFE.VIW_SETOR COMPILE;
ALTER VIEW BABYSAFE.VIW_ATENDIMENTO COMPILE;
ALTER VIEW BABYSAFE.VIW_ATENDIMENTO_1 COMPILE;
ALTER FUNCTION BABYSAFE.FNC_SETOR_PAI COMPILE;
ALTER FUNCTION BABYSAFE.FNC_LEITO_PAI COMPILE;
ALTER FUNCTION BABYSAFE.FNC_ATENDIMENTO_PAI COMPILE;
ALTER VIEW BABYSAFE.VIW_ATENDIMENTO_MAE COMPILE;
ALTER VIEW BABYSAFE.VIW_ALTA COMPILE;
ALTER VIEW BABYSAFE.VIW_ATENDIMENTO_AD COMPILE;
ALTER VIEW BABYSAFE.VIW_ATENDIMENTO_RN COMPILE;


Caso n o compile verificar e executar grant na base MV

Grant nas tabelas MV
grant SELECT on DBAMV.LEITO to babysafe;
grant SELECT on DBAMV.UNID_INT to babysafe;
grant SELECT on DBAMV.SETOR to babysafe;
grant SELECT on DBAMV.ATENDIME to babysafe;
grant SELECT on DBAMV.PACIENTE to babysafe;
