SELECT 
       VDIC_ATENDIMENTO.DATA_DO_ATENDIMENTO,
       VDIC_ATENDIMENTO.HORARIO_DO_ATENDIMENTO,
       VDIC_ATENDIMENTO.DESCRICAO_ESPECIALIDADE,
       VDIC_ATENDIMENTO.CODIGO_DO_ATENDIMENTO,
       VDIC_ATENDIMENTO.NOME_PRESTADOR,
       VDIC_ATENDIMENTO.DESCRICAO_CODIGO_CONSELHO,
       VDIC_ATENDIMENTO.NOME_PACIENTE,
       VDIC_CADASTRAR_PACIENTE.DESCRICAO_DO_SEXO,
       VDIC_CADASTRAR_PACIENTE.NUMERO_DA_IDENTIDADE,
       VDIC_CADASTRAR_PACIENTE.NUMERO_DO_CPF,
       VDIC_CADASTRAR_PACIENTE.DATA_DE_NASCIMENTO,
       VDIC_CADASTRAR_PACIENTE.DESCRICAO_DO_ENDERECO,
       VDIC_CADASTRAR_PACIENTE.NUMERO_DO_ENDERECO,
       VDIC_CADASTRAR_PACIENTE.COMPLEMENTO_DO_ENDERECO,
       VDIC_CADASTRAR_PACIENTE.IDADE_PACIENTE,
       VDIC_CADASTRAR_PACIENTE.DESCRICAO_DO_BAIRRO,
       VDIC_CADASTRAR_PACIENTE.NUMERO_DO_TELEFONE,
       VDIC_CADASTRAR_PACIENTE.NUMERO_DO_CEP,
       VDIC_CADASTRAR_PACIENTE.DESCRICAO_DA_CIDADE,
       VDIC_ATENDIMENTO.NOME_CONVENIO,
       VDIC_ATENDIMENTO.CODIGO_DO_CONVENIO,
       DBAMV.ATENDIME.NR_CARTEIRA,
       VDIC_ATENDIMENTO.DESCRICAO_PLANO_DO_CONVENIO DESCRICAO_PLANO_DO_CONVEN,
       VDIC_ATENDIMENTO.NOME_USUARIO

FROM   DBAMV.VDIC_ATENDIMENTO           VDIC_ATENDIMENTO
     , DBAMV.VDIC_CADASTRAR_PACIENTE    VDIC_CADASTRAR_PACIENTE
     , DBAMV.VDIC_PRESTADOR             VDIC_PRESTADOR
     , DBAMV.ATENDIME
WHERE
      VDIC_ATENDIMENTO.CODIGO_DO_PACIENTE        =  VDIC_CADASTRAR_PACIENTE.PRONTUARIO
  AND VDIC_ATENDIMENTO.CODIGO_DO_PRESTADOR       =  VDIC_PRESTADOR.CODIGO_PRESTADOR(+)
  AND VDIC_ATENDIMENTO.CODIGO_DO_ATENDIMENTO     =  ATENDIME.CD_ATENDIMENTO
  AND ATENDIME.CD_PACIENTE                       =  VDIC_ATENDIMENTO.CODIGO_DO_PACIENTE
  AND ATENDIME.CD_CONVENIO                       =  VDIC_ATENDIMENTO.CODIGO_DO_CONVENIO
  AND ATENDIME.CD_CON_PLA                        =  VDIC_ATENDIMENTO.CODIGO_PLANO_DO_CONVENIO
  AND  VDIC_ATENDIMENTO.CODIGO_DO_ATENDIMENTO = 171827

