select a.CD_ATENDIMENTO
,a.DT_ATENDIMENTO
,a.HR_ATENDIMENTO
,a.NM_USUARIO_ALTA_MEDICA
,a.DT_ALTA_MEDICA
,a.HR_ALTA_MEDICA
,a.DT_ALTA
,a.HR_ALTA
,a.NM_USUARIO_ALTA
from dbamv.atendime a where a.CD_ATENDIMENTO = 1115734
