SELECT CD_CIRURGIA, CD_ESPECIALID  FROM CIRURGIA_AVISO WHERE CD_AVISO_CIRURGIA IN (40234) --ALTERAR O CODIGO DA CIRURGIA NA TABELA CIRURGIA_AVISO
SELECT CD_CONVENIO, CD_CON_PLA  FROM CIRURGIA_AVISO WHERE CD_AVISO_CIRURGIA IN (16659) --ALTERAR CONVENIO E PLANO DA CIRURGIA_AVISO
DELETE FROM CIRURGIA_AVISO WHERE CD_ESPECIALID = 73 AND CD_AVISO_CIRURGIA IN (40234)
SELECT * FROM ATENDIME WHERE CD_ATENDIMENTO = 63308 --- ATENDIMENTO DO AVISO

SELECT DT_AVISO_CIRURGIA, DT_INICIO_CIRURGIA, DT_FIM_CIRURGIA, VL_TEMPO_PREVISTO, DT_INICIO_ANESTESIA
     , DT_FIM_ANESTESIA , DT_REALIZACAO, VL_TEMPO_DURACAO, DT_FIM_LIMPEZA, DT_INICIO_LIMPEZA FROM AVISO_CIRURGIA WHERE CD_AVISO_CIRURGIA = 15989

SELECT * FROM AVISO_CIRURGIA

alter session set nls_date_format = 'dd/mm/yyyy hh24:mi:ss'

SELECT CD_CIRURGIA, CD_PRESTADOR FROM PRESTADOR_AVISO WHERE CD_AVISO_CIRURGIA IN (15989) --ALTERAR O CODIGO DA CIRURGIA NA TABELA PRESTADOR_AVISO
SELECT * FROM PRESTADOR_AVISO WHERE CD_AVISO_CIRURGIA IN (15989)

SELECT * FROM SANGUE_AVISO WHERE CD_AVISO_CIRURGIA IN (6385)              --ALTERAR O CODIGO DA CIRURGIA NA TABELA SANGUE_AVISO
SELECT CD_CIRURGIA FROM SANGUE_AVISO WHERE CD_AVISO_CIRURGIA IN (6385)

SELECT CD_CIRURGIA FROM AVISO_EQUIPAMENTOS WHERE CD_AVISO_CIRURGIA IN (6385) -- ALTERAR O CODIGO DA CIRURGIA NA TABELA AVISO_EQUIPAMENTOS
SELECT * FROM AVISO_EQUIPAMENTOS WHERE CD_AVISO_CIRURGIA IN (6385)

UPDATE AVISO_EQUIPAMENTOS SET CD_CIRURGIA = 899 WHERE CD_AVISO_CIRURGIA IN (16659)

SELECT CD_MOT_CANC_ATRASO FROM AVISO_CIRURGIA WHERE CD_AVISO_CIRURGIA IN (16659)
UPDATE AVISO_CIRURGIA SET CD_MOT_CANC_ATRASO = 22 WHERE CD_AVISO_CIRURGIA IN (6385)
