/*select   r.cd_atendimento,
         pac.nm_paciente,
         r.cd_reg_fat
        
from dbamv.reg_fat r
inner join dbamv.itreg_fat i on i.cd_reg_fat = r.cd_reg_fat
inner join dbamv.tip_presc a on a.cd_pro_fat = i.cd_pro_fat
inner join dbamv.pro_FAt pro on pro.cd_pro_fat = i.cd_pro_fat
inner join dbamv.remessa_fatura rem on rem.cd_remessa = r.cd_remessa
inner join dbamv.fatura fat on fat.CD_FATURA = rem.cd_fatura 
inner join dbamv.atendime ate on ate.CD_ATENDIMENTO = r.cd_atendimento
inner join dbamv.paciente pac on pac.cd_paciente = ate.CD_PACIENTE
inner join dbamv.convenio con on con.cd_convenio = r.cd_convenio
where 1 = 1
and   a.cd_exa_lab = 17
--and i.cd_pro_fat = '08064002'
and   fat.cd_multi_empresa  IN (2)--($GEmpresaMV2000$) 
and  to_date (fat.DT_COMPETENCIA) = '01/01/2017'
--and con.tp_convenio
--and con.tp_convenio <> 'P'
--and i.sn_pertence_pacote = 'S'
--and   i.dt_lancamento between  01/01/2017 and  $GDtfim$ 
\*group by 
         to_char(i.dt_lancamento,'mm/yyyy'),
         pro.ds_pro_fat*\
order by r.cd_atendimento, pac.nm_paciente--r.cd_atendimento---to_char(i.dt_lancamento,'mm/yyyy') asc

*/
---------------------------
/*
SELECT SUM(QT_LANCAMENTO)QT_FATURADA,
       Ds_Pro_FaT DESCRICAO
       
from (
SELECT PRO_FAT   . CD_PRO_FAT CD_PRO_FAT,
       PRO_FAT   . DS_PRO_FAT,
       ITREG_FAT . DT_LANCAMENTO DT_LANCAMENTO,
       ATENDIME  . CD_ATENDIMENTO CD_ATENDIMENTO,
       REG_FAT   . CD_REG_FAT CONTA,
       PACIENTE  . NM_PACIENTE NM_PACIENTE,
       ITREG_FAT . QT_LANCAMENTO QT_LANCAMENTO,
       ITREG_FAT . VL_UNITARIO VL_UNITARIO,
       ITREG_FAT . VL_TOTAL_CONTA VALOR_TOTAL,
       ITREG_FAT . CD_LANCAMENTO CD_LANCAMENTO
  FROM DBAMV . REG_FAT REG_FAT,
       DBAMV . CONVENIO CONVENIO,
       DBAMV . ITREG_FAT ITREG_FAT,
       DBAMV . PRO_FAT PRO_FAT,
       DBAMV . REMESSA_FATURA REMESSA,
       DBAMV . FATURA FATURA,
       DBAMV . ATENDIME ATENDIME,
       DBAMV . PACIENTE PACIENTE,
       dbamv . empresa_convenio,
       DBAMV . TIP_PRESC 
       
 Where Empresa_Convenio.Cd_Convenio = Convenio.Cd_Convenio
   And Empresa_Convenio.Cd_Multi_Empresa = 2
   and REG_FAT.CD_REG_FAT = ITREG_FAT.CD_REG_FAT
   AND REG_FAT.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
   AND ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
   AND REG_FAT.CD_CONVENIO = CONVENIO.CD_CONVENIO
   AND REG_FAT.CD_REMESSA = REMESSA.CD_REMESSA(+)
   AND REMESSA.CD_FATURA = FATURA.CD_FATURA(+)
   AND ITREG_FAT.CD_PRO_FAT = PRO_FAT.CD_PRO_FAT
   AND TIP_PRESC . CD_PRO_FAT = ITREG_fAT . Cd_Pro_Fat 
   AND NVL(ITREG_FAT.TP_PAGAMENTO, 'X') <> 'C'
   AND ATENDIME.CD_MULTI_EMPRESA = 2
   AND TO_CHAR(FATURA . DT_COMPETENCIA,'MM/YYYY') =  '01/2017'
   AND TIP_PRESC . CD_EXA_LAB = #CD_EXA_LAB#
   AND Itreg_Fat . Sn_Pertence_Pacote = #SN_PERTENCE_PACOTE#
   --AND ITREG_FAT.CD_PRO_FAT = '08064002'
UNION ALL
SELECT PRO_FAT   . CD_PRO_FAT CD_PRO_FAT,
       PRO_FAT   . DS_PRO_FAT,
       ATENDIME  . DT_ATENDIMENTO DT_LANCAMENTO,
       ATENDIME  . CD_ATENDIMENTO CD_ATENDIMENTO,
       REG_AMB   . CD_REG_AMB CONTA,
       PACIENTE  . NM_PACIENTE NM_PACIENTE,
       ITREG_AMB . QT_LANCAMENTO QT_LANCAMENTO,
       ITREG_AMB . VL_UNITARIO VL_UNITARIO,
       ITREG_AMB . VL_TOTAL_CONTA VALOR_TOTAL,
       0
  FROM DBAMV . REG_AMB REG_AMB,
       DBAMV . CONVENIO CONVENIO,
       DBAMV . ITREG_AMB ITREG_AMB,
       DBAMV . PRO_FAT PRO_FAT,
       DBAMV . REMESSA_FATURA REMESSA,
       DBAMV . FATURA FATURA,
       DBAMV . ATENDIME ATENDIME,
       DBAMV . PACIENTE PACIENTE,
       dbamv . empresa_convenio,
       DBAMV . TIP_PRESC 
      
 Where Empresa_Convenio.Cd_Convenio = Convenio.Cd_Convenio
   And Empresa_Convenio.Cd_Multi_Empresa = 2
   and REG_AMB.CD_REG_AMB = ITREG_AMB.CD_REG_AMB
   AND ITREG_AMB.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
   AND ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
   AND ITREG_AMB.CD_CONVENIO = CONVENIO.CD_CONVENIO
   AND REG_AMB.CD_REMESSA = REMESSA.CD_REMESSA(+)
   AND REMESSA.CD_FATURA = FATURA.CD_FATURA(+)
   AND ITREG_AMB.CD_PRO_FAT = PRO_FAT.CD_PRO_FAT
   AND TIP_PRESC . CD_PRO_FAT = ITREG_AMB . Cd_Pro_Fat 
   AND REG_AMB.CD_MULTI_EMPRESA = 2
   AND ATENDIME.CD_MULTI_EMPRESA = 2
   AND TO_CHAR(FATURA . DT_COMPETENCIA,'MM/YYYY')= '01/2017'
   AND TIP_PRESC . CD_EXA_LAB = = #CD_EXA_LAB#
   --AND ITREG_AMB.CD_PRO_FAT = '08064002'
   AND ITREG_AMB . SN_PERTENCE_PACOTE = #SN_PERTENCE_PACOTE#
)   
GROUP BY 
   Ds_Pro_Fat*/


-----

SELECT SUM(QT_LANCAMENTO)QT_FATURADA,
 Ds_Pro_FaT DESCRICAO
 
from (
SELECT PRO_FAT . CD_PRO_FAT CD_PRO_FAT,
 PRO_FAT . DS_PRO_FAT,
 ITREG_FAT . DT_LANCAMENTO DT_LANCAMENTO,
 ATENDIME . CD_ATENDIMENTO CD_ATENDIMENTO,
 REG_FAT . CD_REG_FAT CONTA,
 PACIENTE . NM_PACIENTE NM_PACIENTE,
 ITREG_FAT . QT_LANCAMENTO QT_LANCAMENTO,
 ITREG_FAT . VL_UNITARIO VL_UNITARIO,
 ITREG_FAT . VL_TOTAL_CONTA VALOR_TOTAL,
 ITREG_FAT . CD_LANCAMENTO CD_LANCAMENTO,
 DECODE(ITREG_FAT . SN_PERTENCE_PACOTE, 'S','DENTRO PACOTE' , 'N','FORA PACOTE')FORMA_LANCAMENTO
 FROM DBAMV . REG_FAT REG_FAT,
 DBAMV . CONVENIO CONVENIO,
 DBAMV . ITREG_FAT ITREG_FAT,
 DBAMV . PRO_FAT PRO_FAT,
 DBAMV . REMESSA_FATURA REMESSA,
 DBAMV . FATURA FATURA,
 DBAMV . ATENDIME ATENDIME,
 DBAMV . PACIENTE PACIENTE,
 dbamv . empresa_convenio,
 DBAMV . TIP_PRESC 
 
 Where Empresa_Convenio.Cd_Convenio = Convenio.Cd_Convenio
 And Empresa_Convenio.Cd_Multi_Empresa IN (2) 
 and REG_FAT.CD_REG_FAT = ITREG_FAT.CD_REG_FAT
 AND REG_FAT.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
 AND ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
 AND REG_FAT.CD_CONVENIO = CONVENIO.CD_CONVENIO
 AND REG_FAT.CD_REMESSA = REMESSA.CD_REMESSA(+)
 AND REMESSA.CD_FATURA = FATURA.CD_FATURA(+)
 AND ITREG_FAT.CD_PRO_FAT = PRO_FAT.CD_PRO_FAT
 AND TIP_PRESC . CD_PRO_FAT = ITREG_fAT . Cd_Pro_Fat 
 AND NVL(ITREG_FAT.TP_PAGAMENTO, 'X') <> 'C'
 AND ATENDIME.CD_MULTI_EMPRESA IN (2) 
 AND ITREG_FAT.DT_LANCAMENTO between '01/01/2017' and '31/01/2017'
 --AND TO_CHAR(FATURA . DT_COMPETENCIA,'MM/YYYY') IN ('01/2017') 
 AND TIP_PRESC . CD_EXA_LAB = '17'
 AND ATENDIME = #CD_ATENDIMENTO#
 --AND Itreg_Fat . Sn_Pertence_Pacote = 'N'
 --AND ITREG_FAT.CD_PRO_FAT = '08064002'
UNION ALL
SELECT PRO_FAT . CD_PRO_FAT CD_PRO_FAT,
 PRO_FAT . DS_PRO_FAT,
 ATENDIME . DT_ATENDIMENTO DT_LANCAMENTO,
 ATENDIME . CD_ATENDIMENTO CD_ATENDIMENTO,
 REG_AMB . CD_REG_AMB CONTA,
 PACIENTE . NM_PACIENTE NM_PACIENTE,
 ITREG_AMB . QT_LANCAMENTO QT_LANCAMENTO,
 ITREG_AMB . VL_UNITARIO VL_UNITARIO,
 ITREG_AMB . VL_TOTAL_CONTA VALOR_TOTAL,
 0,
 DECODE(ITREG_AMB . SN_PERTENCE_PACOTE,'S','DENTRO PACOTE' , 'N','FORA PACOTE')FORMA_LANCAMENTO 
 FROM DBAMV . REG_AMB REG_AMB,
 DBAMV . CONVENIO CONVENIO,
 DBAMV . ITREG_AMB ITREG_AMB,
 DBAMV . PRO_FAT PRO_FAT,
 DBAMV . REMESSA_FATURA REMESSA,
 DBAMV . FATURA FATURA,
 DBAMV . ATENDIME ATENDIME,
 DBAMV . PACIENTE PACIENTE,
 dbamv . empresa_convenio,
 DBAMV . TIP_PRESC 
 
 Where Empresa_Convenio.Cd_Convenio = Convenio.Cd_Convenio
 And Empresa_Convenio.Cd_Multi_Empresa IN (2) 
 and REG_AMB.CD_REG_AMB = ITREG_AMB.CD_REG_AMB
 AND ITREG_AMB.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
 AND ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
 AND ITREG_AMB.CD_CONVENIO = CONVENIO.CD_CONVENIO
 AND REG_AMB.CD_REMESSA = REMESSA.CD_REMESSA(+)
 AND REMESSA.CD_FATURA = FATURA.CD_FATURA(+)
 AND ITREG_AMB.CD_PRO_FAT = PRO_FAT.CD_PRO_FAT
 AND TIP_PRESC . CD_PRO_FAT = ITREG_AMB . Cd_Pro_Fat 
 AND REG_AMB.CD_MULTI_EMPRESA IN (2) 
 AND ATENDIME.CD_MULTI_EMPRESA IN (2) 
 AND ITREG_AMB . HR_LANCAMENTO BETWEEN '01/01/2017' AND '31/01/2017'
 --AND TO_CHAR(FATURA . DT_COMPETENCIA,'MM/YYYY') IN ('01/2017') 
 AND TIP_PRESC . CD_EXA_LAB = '17'
 AND ATENDIME = #CD_ATENDIMENTO#
 --AND ITREG_AMB.CD_PRO_FAT = '08064002'
-- AND ITREG_AMB . SN_PERTENCE_PACOTE = 'N'
ORDER BY NM_PACIENTE
) 
GROUP BY 
 Ds_Pro_Fat
