SELECT  ATENDIME.CD_ATENDIMENTO
     ,  ATENDIME.CD_MULTI_EMPRESA   "EMPRESA DO ATENDIMENTO"
     ,  REG_FAT.CD_REG_FAT
     ,  REG_FAT.CD_REMESSA
     ,  REG_FAT.CD_MULTI_EMPRESA    "EMPRESA DA CONTA"
     ,  REG_FAT.CD_CONVENIO
     ,  CONVENIO.NM_CONVENIO
     ,  FATURA.CD_MULTI_EMPRESA     "EMPRESA DA REMESSA"
FROM   DBAMV.REG_FAT, DBAMV.ATENDIME, CONVENIO, FATURA, REMESSA_FATURA
WHERE /* REG_FAT.CD_ATENDIMENTO IN (267201,267183,267561,267236)
AND */   REG_FAT.CD_CONVENIO IN (379,352,378)
AND    REG_FAT.CD_CONVENIO = CONVENIO.CD_CONVENIO
AND    CONVENIO.CD_CONVENIO = FATURA.CD_CONVENIO
AND    REG_FAT.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
AND    REMESSA_FATURA.CD_REMESSA = REG_FAT.CD_REMESSA
AND    FATURA.CD_FATURA = REMESSA_FATURA.CD_FATURA
AND    FATURA.CD_MULTI_EMPRESA <> ATENDIME.CD_MULTI_EMPRESA


SELECT CD_REMESSA, CD_ATENDIMENTO ,CD_REG_FAT, CD_CONVENIO
FROM REG_FAT
WHERE CD_ATENDIMENTO IN (266980,266863)
AND CD_CONVENIO IN (352,378,379)


DELETE FROM MVTO_GASES WHERE CD_ATENDIMENTO = 264029
