SELECT 
       REG_FAT.CD_ATENDIMENTO,
       PACIENTE.NM_PACIENTE,  
       ATENDIME.DT_ATENDIMENTO,
       ATENDIME.DT_ALTA,
       TRUNC(REG_FAT.DT_INICIO)DT_INICIO_CONTA,
       TRUNC (REG_FAT.DT_FINAL)DT_FINAL_CONTA,
       CONVENIO.NM_CONVENIO,
       REG_FAT.CD_REG_FAT,
       REG_FAT.SN_FECHADA,
       REG_FAT.VL_TOTAL_CONTA,
       LEITO.DS_LEITO,
       --LEITO.CD_UNID_INT,
       UNID_INT.DS_UNID_INT,
      -- REG_FAT.CD_TIP_ACOM,
      -- TIP_ACOM.DS_TIP_ACOM,
       REG_FAT.CD_MULTI_EMPRESA,
       (TRUNC ( SYSDATE - ATENDIME.DT_ATENDIMENTO)+1)DIAS_INTERNADOS
       
        
 
  FROM DBAMV.REG_FAT,
       DBAMV.PACIENTE,
       DBAMV.ATENDIME,
       DBAMV.CONVENIO,
       DBAMV.TIP_ACOM,
       DBAMV.LEITO,
       DBAMV.UNID_INT
          
 WHERE REG_FAT.CD_MULTI_EMPRESA = 1
   AND ATENDIME.CD_ATENDIMENTO = REG_FAT.CD_ATENDIMENTO
   AND ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
   AND REG_FAT.CD_CONVENIO = CONVENIO.CD_CONVENIO
   AND PACIENTE.NM_PACIENTE LIKE 'RN%'
  AND ATENDIME.DT_ATENDIMENTO BETWEEN '01/01/2017' AND '09/06/2017'
  AND CONVENIO.TP_CONVENIO NOT IN ('P')
   AND ATENDIME.DT_ALTA IS NULL
   AND REG_FAT.SN_FECHADA = 'N'
   AND ATENDIME.CD_TIP_ACOM = TIP_ACOM.CD_TIP_ACOM
   AND LEITO.CD_LEITO = ATENDIME.CD_LEITO
   AND LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT
  -- AND REG_FAT.DT_FINAL IS N
   --AND Reg_Fat.Tp_Classificacao_Conta = 'P'
  --and REG_FAT.CD_ATENDIMENTO = 1544921
  GROUP BY 
       REG_FAT.CD_ATENDIMENTO,
       PACIENTE.NM_PACIENTE,  
       REG_FAT.CD_REG_FAT,
       ATENDIME.DT_ATENDIMENTO,
       REG_FAT.DT_INICIO,
       REG_FAT.DT_FINAL,
       CONVENIO.NM_CONVENIO,
       REG_FAT.CD_REMESSA,
       REG_FAT.SN_FECHADA,
       REG_FAT.VL_TOTAL_CONTA,
       DT_FECHAMENTO,
       REG_FAT.CD_TIP_ACOM,
       TIP_ACOM.DS_TIP_ACOM,
       REG_FAT.CD_MULTI_EMPRESA, 
       ATENDIME.DT_ALTA,  
       UNID_INT.DS_UNID_INT,
       LEITO.DS_LEITO,
       LEITO.CD_UNID_INT
 ORDER BY 2,5,6 
       
 
 
