SELECT   TO_CHAR (V.dt_vigencia,'MM/YYYY') VIGENCIA, C.cd_convenio, C.nm_convenio, I.cd_tab_fat, T.ds_tab_fat 
FROM     DBAMV.VAL_PRO V, DBAMV.ITREGRA I, DBAMV.CON_PLA P, DBAMV.TAB_FAT T, DBAMV.REGRA R, DBAMV.CONVENIO C
WHERE    V.CD_TAB_FAT  = I.CD_TAB_FAT
AND      V.CD_TAB_FAT  = T.CD_TAB_FAT
AND      I.CD_TAB_FAT  = T.CD_TAB_FAT
AND      V.CD_TAB_FAT  NOT IN (70)
AND      T.CD_TAB_FAT  NOT IN (1,2,292,294,293,296,355,283,321,412,282)
AND      I.CD_REGRA    = R.CD_REGRA
AND      I.CD_REGRA    = P.CD_REGRA
AND      P.CD_CONVENIO = C.CD_CONVENIO
AND      P.SN_ATIVO    = 'S'
AND      C.SN_ATIVO    = 'S'
AND      TO_CHAR (V.dt_vigencia,'MM/YYYY') = '05/2012'
GROUP BY TO_CHAR (V.dt_vigencia,'MM/YYYY'), C.cd_convenio, C.nm_convenio,  I.CD_TAB_FAT, T.ds_tab_fat
ORDER BY TO_CHAR (V.dt_vigencia,'MM/YYYY'), 2 






--SELECT * FROM DBAMV.VAL_PRO
--SELECT * FROM DBAMV.TAB_FAT
--SELECT * FROM DBAMV.ITREGRA
--SELECT * FROM DBAMV.REGRA
--SELECT * FROM DBAMV.CONVENIO
--SELECT * FROM DBAMV.CON_PLA WHERE CD_CONVENIO = 342 AND SN_ATIVO = 'S' ORDER BY CD_CON_PLA
