SELECT CD_PRODUTO,CD_MULTI_EMPRESA
,QT_ESTOQUE_ATUAL
,VL_ULTIMA_ENTRADA,VL_CUSTO_MEDIO,VL_ULTIMA_CUSTO_REAL
,VL_ULTIMA_COMPRA_IPI
FROM Dbamv.Empresa_Produto
WHERE CD_MULTI_EMPRESA IN (1,2)
AND CD_PRODUTO = 53585

SELECT VL_CUSTO_MEDIO_ANTES, VL_ENTRADA, VL_CUSTO_MEDIO  FROM CUSTO_MEDIO WHERE CD_PRODUTO = 53585
SELECT * FROM CUSTO_MEDIO WHERE CD_PRODUTO = 53585
SELECT * FROM PRODUTO WHERE CD_PRODUTO = 53585

SELECT * FROM ITCONTAGEM WHERE CD_PRODUTO = 53585
SELECT * FROM CONTAGEM WHERE CD_CONTAGEM IN (254,633,2011)
