SELECT  * FROM MVINTEGRA.INTEGRA_SAIDA_CAD_PESSOA
SELECT  * FROM MVINTEGRA.INTEGRA_SAIDA_SOLICITACAO_SADT
SELECT  * FROM MVINTEGRA.INTEGRA_SAIDA_ATENDIMENTO
--SELECT  * FROM MVINTEGRA.INTEGRA_ENTRADA_CAD_PESSOA
--SELECT  * FROM MVINTEGRA.INTEGRA_ENTRADA_SOLIC_SADT

TRUNCATE TABLE MVINTEGRA.INTEGRA_SAIDA_CAD_PESSOA
TRUNCATE TABLE MVINTEGRA.INTEGRA_SAIDA_SOLICITACAO_SADT
TRUNCATE TABLE MVINTEGRA.INTEGRA_SAIDA_ATENDIMENTO
TRUNCATE TABLE MVINTEGRA.INTEGRA_ENTRADA_CAD_PESSOA

COMMIT
