-------------------------------------------------------------Diarias por Serviços------------------------------------------------------------------------

SELECT ATENDIME.CD_ATENDIMENTO, LEITO.CD_LEITO, UNID_INT.CD_UNID_INT, ATENDIME.CD_SERVICO, ITREG_FAT.DT_LANCAMENTO, ITREG_FAT.CD_PRO_FAT
FROM   ITREG_FAT, ATENDIME, REG_FAT, UNID_INT, LEITO
WHERE  ITREG_FAT.CD_GRU_FAT = 1
AND    ATENDIME.CD_SERVICO = 22
AND    ATENDIME.CD_MULTI_EMPRESA = 1
AND    ATENDIME.CD_ATENDIMENTO = REG_FAT.CD_ATENDIMENTO
AND    ATENDIME.CD_LEITO = LEITO.CD_LEITO
AND    LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT
AND    UNID_INT.CD_UNID_INT = 19
AND    REG_FAT.CD_REG_FAT = ITREG_FAT.CD_REG_FAT
AND    dt_lancamento >= '01/04/2009 00:00:00'
AND    dt_lancamento <= '30/04/2009 23:59:59'
--AND    REG_FAT.CD_REG_FAT = 212917
ORDER BY 3,1,5

-------------------------------------------------------------Cirurgias por Serviços--------------------------------------------------------------------

SELECT ATENDIME.CD_ATENDIMENTO, ATENDIME.CD_LEITO, LEITO.CD_UNID_INT, ATENDIME.CD_SERVICO, AVISO_CIRURGIA.CD_CEN_CIR, AVISO_CIRURGIA.DT_REALIZACAO
FROM   DBAMV.AVISO_CIRURGIA, DBAMV.ATENDIME, DBAMV.UNID_INT, DBAMV.LEITO
WHERE AVISO_CIRURGIA.CD_CEN_CIR <> 0
AND   AVISO_CIRURGIA.CD_ATENDIMENTO =  ATENDIME.CD_ATENDIMENTO
AND   ATENDIME.CD_SERVICO = 22
AND   ATENDIME.CD_MULTI_EMPRESA = 1
AND   ATENDIME.CD_LEITO = LEITO.CD_LEITO
AND   LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT
AND   UNID_INT.CD_UNID_INT = 19
AND   AVISO_CIRURGIA.TP_SITUACAO = 'R'
--AND   ATENDIME.CD_ATENDIMENTO IN (245013,245024,246180,246185,253794)
AND   DT_REALIZACAO >= '01/04/2009 00:00:00'
AND   DT_REALIZACAO <= '30/04/2009 23:59:59'
ORDER BY CD_UNID_INT






alter session set nls_date_format = 'dd/mm/yyyy hh24:mi:ss'

Begin
   Pkg_Mv2000.Atribui_Empresa( 1 );  -->> Trocar a empresa e rodar uma vez para cada empresa
End;



--SELECT * FROM DBAMV.ATENDIME
--SELECT * FROM DBAMV.ITREG_FAT
--SELECT * FROM DBAMV.REG_FAT
--SELECT * FROM DBAMV.LEITO
--SELECT * FROM DBAMV.UNID_INT
--SELECT * FROM DBAMV.AVISO_CIRURGIA WHERE CD_ATENDIMENTO IN (245013,245024,246180,246185,253794)






