SELECT * FROM ITREG_FAT, ATENDIME, REG_FAT, UNID_INT, LEITO
WHERE ITREG_FAT.CD_GRU_FAT = 1
AND   ATENDIME.CD_SERVICO = 22
AND   ATENDIME.CD_ATENDIMENTO = REG_FAT.CD_ATENDIMENTO
AND   ATENDIME.CD_LEITO = LEITO.CD_LEITO
AND   LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT
AND   UNID_INT.CD_UNID_INT = 18
AND   REG_FAT.CD_REG_FAT = ITREG_FAT.CD_REG_FAT
AND   REG_FAT.SN_FECHADA = 'S'
AND   TO_CHAR (ITREG_FAT.DT_LANCAMENTO, 'DD/MM/YY')>= '01/04/09'
AND   TO_CHAR (ITREG_FAT.DT_LANCAMENTO,'DD/MM/YY') < '31/04/09'



--alter session set nls_date_format = 'dd/mm/yyyy hh24:mi:ss'

Begin
  Pkg_Mv2000.Atribui_Empresa( 1 );  -->> Trocar a empresa e rodar uma vez para cada empresa
End;



--SELECT * FROM DBAMV.ATENDIME
--SELECT * FROM DBAMV.ITREG_FAT
--SELECT * FROM DBAMV.REG_FAT
--SELECT * FROM DBAMV.LEITO
--SELECT * FROM DBAMV.UNID_INT
