SELECT 

FROM   DBAMV.REG_FAT,
       DBAMV.ITREG_FAT ,
       DBAMV.CONVENIO ,
       DBAMV.REMESSA_FATURA,
       DBAMV.TB_ATENDIME,
       DBAMV.FATURA

WHERE REG_FAT.CD_REG_FAT = ITREG_FAT.CD_REG_FAT
AND       






SELECT REG_AMB.CD_REG_AMB CONTA,
       ITREG_AMB.CD_ATENDIMENTO ATENDIMENTO,
       REG_AMB.CD_CONVENIO CD_CONVENIO,
       CONVENIO.NM_CONVENIO NM_CONVENIO,
      -- TB_ATENDIME.TP_ATENDIMENTO,
       DECODE(TB_ATENDIME.TP_ATENDIMENTO,'U','CONTAS AMBULATORIAIS','E','CONTAS AMBULATORIAIS')TP_CONTA,
     --  REMESSA_FATURA.CD_AGRUPAMENTO,
       SUM(ITREG_AMB.VL_TOTAL_CONTA)VL_TOTAL_CONTA,
       ITREG_AMB.DT_FECHAMENTO DT_FECHAMENTO,
       TO_CHAR(ITREG_AMB.DT_FECHAMENTO,'MM/YYYY')COMP_FECHAM,
       ITREG_AMB.NM_USUARIO_FECHOU USUARIO_FECH,
       TO_CHAR(FATURA.DT_COMPETENCIA,'MM/YYYY')COMP_REMESSA,
       REG_AMB.CD_REMESSA REMESSA ,
       REG_AMB.CD_MULTI_EMPRESA EMPRESA


FROM 
DBAMV.REG_AMB ,
DBAMV.ITREG_AMB ,
DBAMV.CONVENIO,
DBAMV.REMESSA_FATURA,
DBAMV.TB_ATENDIME,
DBAMV.FATURA

WHERE REG_AMB.CD_REG_AMB = ITREG_AMB.CD_REG_AMB 
AND ITREG_AMB.CD_ATENDIMENTO IN(1744696,1688043,1712275)
AND ITREG_AMB.SN_PERTENCE_PACOTE = 'N'
AND ITREG_AMB.SN_FECHADA = 'S'
AND REG_AMB.CD_CONVENIO = CONVENIO.CD_CONVENIO
AND REG_AMB.CD_REMESSA = REMESSA_FATURA.CD_REMESSA (+)
AND REMESSA_FATURA.CD_FATURA = FATURA.CD_FATURA (+)
AND TB_ATENDIME.CD_ATENDIMENTO = ITREG_AMB.CD_ATENDIMENTO
GROUP BY 
       REG_AMB.CD_REG_AMB,
       ITREG_AMB.CD_ATENDIMENTO,
       REG_AMB.CD_CONVENIO,
       CONVENIO.NM_CONVENIO,
       TB_ATENDIME.TP_ATENDIMENTO,
       TB_ATENDIME.TP_ATENDIMENTO,
       REMESSA_FATURA.CD_AGRUPAMENTO,
       ITREG_AMB.DT_FECHAMENTO,
       ITREG_AMB.NM_USUARIO_FECHOU,
       FATURA.DT_COMPETENCIA,
       REG_AMB.CD_REMESSA,
       REG_AMB.CD_MULTI_EMPRESA
