DELETE
--CD_AVISO_CIRURGIA, CD_APARELHO_EQUIPAMENTO
FROM   DBAMV.AVISO_EQUIPAMENTOS
WHERE  CD_APARELHO_EQUIPAMENTO IN (604)
AND    CD_AVISO_CIRURGIA IN (SELECT AE.CD_AVISO_CIRURGIA
                             FROM   DBAMV.AVISO_EQUIPAMENTOS AE
                             WHERE  AE.CD_APARELHO_EQUIPAMENTO IN (596)
                             AND    AE.CD_AVISO_CIRURGIA = AVISO_EQUIPAMENTOS.CD_AVISO_CIRURGIA)
ORDER BY CD_AVISO_CIRURGIA  -- APARELHO NO AVISO



SELECT * FROM DBAMV.AVISO_EQUIPAMENTOS WHERE CD_APARELHO_EQUIPAMENTO IN (543,63) AND CD_AVISO_CIRURGIA = 11979

SELECT CD_AGE_CIR, CD_APARELHO_EQUIPAMENTO FROM DBAMV.AGE_CIR_EQUIPTO WHERE CD_APARELHO_EQUIPAMENTO = 604 --- APARELHOS NO AGENDAMENTO


DELETE
FROM  DBAMV.APARELHO_CIRURGIA
WHERE CD_APARELHO_EQUIPAMENTO in (512)
AND   CD_CIRURGIA IN ( SELECT AC.CD_CIRURGIA
                     FROM   DBAMV.APARELHO_CIRURGIA AC
                     WHERE  AC.CD_APARELHO_EQUIPAMENTO IN (3)
                     AND    AC.CD_CIRURGIA = APARELHO_CIRURGIA.CD_CIRURGIA)
ORDER BY CD_CIRURGIA  --- APARELHOS NA CIRURGIAS




UPDATE DBAMV.APARELHO_CIRURGIA SET  CD_APARELHO_EQUIPAMENTO = 604 WHERE CD_APARELHO_EQUIPAMENTO = 603
