SELECT ATENDIME.CD_ATENDIMENTO, ATENDIME.DT_ALTA, MOV_CC_RPA.CD_AVISO_CIRURGIA, MOV_CC_RPA.CD_MOV_CC_RPA
FROM DBAMV.MOV_CC_RPA, DBAMV.ATENDIME
WHERE DS_LOCAL_TRANSF_POS_CIR = 'U'
AND MOV_CC_RPA. CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
AND ATENDIME.DT_ALTA IS NOT NULL
AND DT_SAIDA_RPA > '03/04/09'
ORDER BY DT_CENTRO_CIRURGICO DESC
