SELECT *
FROM DBAMV.TISS_NR_GUIA WHERE CD_CODIGO_CONTRATADO = 1
ORDER BY CD_REG_FAT DESC


SELECT * FROM DBAMV.PRES_CON WHERE CD_CONVENIO IN (21,388,39)

SELECT * FROM DBAMV.EMPRESA_CONVENIO WHERE CD_MULTI_EMPRESA = 4 AND CD_CONVENIO IN (21,388,39)

SELECT CD_PRESTADOR_CONVENIADO FROM DBAMV.PRES_CON WHERE CD_PRESTADOR = 625 AND CD_CONVENIO IN (21,388,39)

SELECT * FROM PRESTADOR WHERE DS_CODIGO_CONSELHO = '63810'   


SELECT * FROM DBAMV.PRESTADOR_MEIO_MAG

SELECT * FROM DBAMV.PRESTADOR_EXTERNO -WHERE NR_CPF_CGC = '1'
