--- (Todas as Contas Abertas/fechadas sem remessa do dia 01/08/2018 a 01/11/2021) ---
--- CSSJ 
--- CONVENIOS , PARTICULARES
--- (RAF) = RECEITAS A FATURAR 
---- 
SELECT 
*
FROM
(
SELECT 
A.CD_ATENDIMENTO,
'INTERNADO'TP_CONTA,
B.CD_CONVENIO||' - '||C.NM_CONVENIO NM_CONVENIO,
A.DT_ATENDIMENTO,
B.CD_REG_FAT CONTA,
SUM(B1.VL_TOTAL_CONTA)VL_TOTAL_CONTA,
CASE WHEN B.SN_FECHADA = 'S' THEN 'FECHADA' ELSE 'ABERTA' END SITUACAO_CONTA
FROM 
DBAMV.ATENDIME A 
INNER JOIN DBAMV.REG_FAT B ON B.CD_ATENDIMENTO = A.CD_ATENDIMENTO
INNER JOIN DBAMV.ITREG_FAT B1 ON B1.CD_REG_FAT = B.CD_REG_FAT
INNER JOIN DBAMV.CONVENIO C ON C.CD_CONVENIO = B.CD_CONVENIO
WHERE A.DT_ATENDIMENTO BETWEEN '01/08/2018' AND '01/11/2021'
AND A.CD_MULTI_EMPRESA = 3 
AND B.TP_CLASSIFICACAO_CONTA <> 'O'
AND B1.SN_PERTENCE_PACOTE = 'N'
--AND B.CD_REG_FAT IN (343164,364956)
AND B.CD_REMESSA IS NULL
GROUP BY 
A.CD_ATENDIMENTO,
B.CD_CONVENIO,
C.NM_CONVENIO,
A.DT_ATENDIMENTO,
B.CD_REG_FAT,
B.SN_FECHADA


UNION ALL

SELECT 
A1.CD_ATENDIMENTO,
'AMBULATORIAL'TP_CONTA,
B2.CD_CONVENIO||' - '||C1.NM_CONVENIO NM_CONVENIO,
A1.DT_ATENDIMENTO,
B2.CD_REG_AMB CONTA,
SUM(B2.VL_TOTAL_CONTA)VL_TOTAL_CONTA,
CASE WHEN B2.SN_FECHADA = 'S' THEN 'FECHADA' ELSE 'ABERTA' END SITUACAO_CONTA

FROM 
DBAMV.ATENDIME A1
INNER JOIN ITREG_AMB B2 ON B2.CD_ATENDIMENTO = A1.CD_ATENDIMENTO
INNER JOIN REG_AMB B3 ON B3.CD_REG_AMB = B2.CD_REG_AMB
INNER JOIN CONVENIO C1 ON C1.CD_CONVENIO = B2.CD_CONVENIO AND B3.CD_CONVENIO = B2.CD_CONVENIO
WHERE A1.CD_MULTI_EMPRESA = 3
AND A1.DT_ATENDIMENTO BETWEEN '01/08/2018' AND '01/11/2021'
--AND A1.CD_ATENDIMENTO = 3261879
AND B2.SN_PERTENCE_PACOTE = 'N'
AND B3.VL_TOTAL_CONTA <> 0
AND B3.CD_REMESSA IS NULL
GROUP BY 
A1.CD_ATENDIMENTO,
B2.CD_CONVENIO,
C1.NM_CONVENIO,
A1.DT_ATENDIMENTO,
B2.CD_REG_AMB,
B2.SN_FECHADA
) ORDER BY NM_CONVENIO , DT_ATENDIMENTO

/*;


SELECT 
*
FROM
(
SELECT 
A.CD_ATENDIMENTO,
'INTERNADO'TP_CONTA,
B.CD_CONVENIO||' - '||C.NM_CONVENIO NM_CONVENIO,
A.DT_ATENDIMENTO,
B.CD_REG_FAT CONTA,
SUM(B1.VL_TOTAL_CONTA)VL_TOTAL_CONTA,
CASE WHEN B.SN_FECHADA = 'S' THEN 'FECHADA' ELSE 'ABERTA' END SITUACAO_CONTA
FROM 
DBAMV.ATENDIME A 
INNER JOIN DBAMV.REG_FAT B ON B.CD_ATENDIMENTO = A.CD_ATENDIMENTO
INNER JOIN DBAMV.ITREG_FAT B1 ON B1.CD_REG_FAT = B.CD_REG_FAT
INNER JOIN DBAMV.CONVENIO C ON C.CD_CONVENIO = B.CD_CONVENIO
WHERE A.DT_ATENDIMENTO BETWEEN '01/08/2018' AND '01/11/2021'
AND A.CD_MULTI_EMPRESA = 3 
AND B.TP_CLASSIFICACAO_CONTA <> 'O'
AND B1.SN_PERTENCE_PACOTE = 'N'
--AND B.CD_REG_FAT IN (343164,364956)
AND B.CD_REMESSA IS NULL
GROUP BY 
A.CD_ATENDIMENTO,
B.CD_CONVENIO,
C.NM_CONVENIO,
A.DT_ATENDIMENTO,
B.CD_REG_FAT,
B.SN_FECHADA


UNION ALL

SELECT 
A1.CD_ATENDIMENTO,
'AMBULATORIAL'TP_CONTA,
B2.CD_CONVENIO||' - '||C1.NM_CONVENIO NM_CONVENIO,
A1.DT_ATENDIMENTO,
B2.CD_REG_AMB CONTA,
SUM(B2.VL_TOTAL_CONTA)VL_TOTAL_CONTA,
CASE WHEN B2.SN_FECHADA = 'S' THEN 'FECHADA' ELSE 'ABERTA' END SITUACAO_CONTA

FROM 
DBAMV.ATENDIME A1
INNER JOIN ITREG_AMB B2 ON B2.CD_ATENDIMENTO = A1.CD_ATENDIMENTO
INNER JOIN REG_AMB B3 ON B3.CD_REG_AMB = B2.CD_REG_AMB
INNER JOIN CONVENIO C1 ON C1.CD_CONVENIO = B2.CD_CONVENIO AND B3.CD_CONVENIO = B2.CD_CONVENIO
WHERE A1.CD_MULTI_EMPRESA = 3
AND A1.DT_ATENDIMENTO BETWEEN '01/08/2018' AND '01/11/2021'
--AND A1.CD_ATENDIMENTO = 3261879
AND B2.SN_PERTENCE_PACOTE = 'N'
AND B3.VL_TOTAL_CONTA <> 0
AND B3.CD_REMESSA IS NULL
GROUP BY 
A1.CD_ATENDIMENTO,
B2.CD_CONVENIO,
C1.NM_CONVENIO,
A1.DT_ATENDIMENTO,
B2.CD_REG_AMB,
B2.SN_FECHADA
)ORDER BY DT_ATENDIMENTO

*/
