DELETE
FROM DBAMV.TUSS
WHERE CD_CONVENIO = 41
AND CD_TIP_TUSS IN (19,00)
AND CD_TUSS = '82010021'
AND DT_INICIO_VIGENCIA NOT IN ('01/06/2022','01/10/2022')
AND TUSS.CD_PRO_FAT IN (SELECT 
PF.CD_PRO_FAT
FROM 
DBAMV.PRO_FAT PF 
INNER JOIN DBAMV.GRU_PRO GP ON GP.CD_GRU_PRO = PF.CD_GRU_PRO
WHERE GP.TP_GRU_PRO IN ('MT','OP'));
COMMIT 
