SELECT 
DISTINCT
CD_EXAME,
NM_EXAME,
PROCEDIMENTO_CONVENIO,
PROCEDIMENTO_SUS_SIH,
PROCEDIMENTO_SUS_SIA
FROM
(
SELECT X.CD_EXA_LAB CD_EXAME, 
       X.NM_EXA_LAB NM_EXAME,
       X.CD_PRO_FAT PROCEDIMENTO_CONVENIO,
       X.CD_PROCEDIMENTO_SIH PROCEDIMENTO_SUS_SIH,
       X.CD_PROCEDIMENTO_SIA PROCEDIMENTO_SUS_SIA
FROM EXA_LAB X 
LEFT JOIN PROCEDIMENTO_SUS PS ON PS.CD_PROCEDIMENTO = X.CD_PROCEDIMENTO_SIH OR 
PS.CD_PROCEDIMENTO = X.CD_PROCEDIMENTO_SIA
WHERE X.SN_ATIVO = 'S'
AND PS.SN_ATIVO = 'S'


UNION ALL 

SELECT RX.CD_EXA_RX CD_EXAME,
       RX.DS_EXA_RX NM_EXAME,
       RX.EXA_RX_CD_PRO_FAT PROCEDIMENTO_CONVENIO,
       RX.CD_PROCEDIMENTO_SIH PROCEDIMENTO_SUS_SIH,
       RX.CD_PROCEDIMENTO_SIA PROCEDIMENTO_SUS_SIA
FROM EXA_RX RX 
LEFT JOIN PROCEDIMENTO_SUS PS ON PS.CD_PROCEDIMENTO = RX.CD_PROCEDIMENTO_SIH OR 
PS.CD_PROCEDIMENTO = RX.CD_PROCEDIMENTO_SIA
WHERE RX.SN_ATIVO = 'S'
AND PS.SN_ATIVO = 'S'
)
ORDER BY 1 


/*SELECT * FROM PROCEDIMENTO_SUS WHERE CD_PROCEDIMENTO IN ('0202031217',
'0202040119',
'0202060276',
'0202060322')

SELECT * FROM EXA_LAB RXX WHERE RXX.CD_PROCEDIMENTO_SIA IN (
'0202031217',
'0202040119',
'0202060276',
'0202060322')*/
