begin 
DBAMV.PKG_MV2000.atribui_empresa (7);
END;
/
INSERT INTO dbamv.itreg_fat  ( 
                         CD_REG_FAT                        
                ,CD_LANCAMENTO                     
                        ,DT_LANCAMENTO 
                        ,HR_LANCAMENTO                              
                        ,QT_LANCAMENTO                     
                        ,VL_PERCENTUAL_MULTIPLA            
                        ,VL_UNITARIO                       
                        ,VL_FILME_UNITARIO                         
                        ,VL_ACRESCIMO                              
                        ,VL_DESCONTO                               
                        ,CD_GRU_FAT                        
                        ,CD_PRO_FAT                        
                        ,CD_PRESTADOR                      
                        ,NR_PADRAO                         
                        ,VL_HONORARIO_UNITARIO                     
                        ,VL_OPERACIONAL_UNITARIO                   
                        ,CD_PRES_CON                       
                        ,VL_PERCENTUAL_PACIENTE            
                        ,VL_TOTAL_CONTA                            
                        ,CD_IMPORTA_REG_FAT                
                        ,CD_GUIA                           
                        ,SN_PERTENCE_PACOTE                
                        ,VL_BASE_REPASSADO                         
                        ,CD_MOTIVO_GLOSA                       
                        ,QT_CH_UNITARIO                        
                        ,TP_PAGAMENTO                          
                        ,CD_SETOR_PRODUZIU                     
                        ,CD_SETOR                              
                        ,CD_PADRAO                                 
                        ,SN_HORARIO_ESPECIAL                       
                        ,QT_PONTOS                                 
                        ,SN_PROCED_AUTORIZADO                      
                        ,TP_ALTA_UTI_NEO                           
                        ,QT_PESO_RN                                
                        ,QT_MES_GESTACAO                           
                        ,CD_SUS                                    
                        ,CD_TIPO_VINCULO                           
                        ,CD_ATI_MED                                
                        ,VL_SP                                     
                        ,VL_SH                                     
                        ,VL_SD                                     
                        ,VL_ATO                                    
                        ,CD_SUS_AUXILIAR                           
                        ,CD_REG_FAT_PAI                            
                        ,CD_LANCAMENTO_PAI                         
                        ,SN_PROCED_REALIZADO                       
                        ,CD_FRANQUIA                       
                        ,CD_REGRA_ACOPLAMENTO              
                        ,VL_PERC_ACOPLAMENTO               
                        ,SN_PACIENTE_PAGA                  
                        ,CD_REGRA_ATENDIMENTO              
                        ,CD_REGRA_ATENDIMENTO_PRO_FAT      
                        ,CD_REG_FAT_REL                    
                        ,CD_LANCAMENTO_REL                 
                        ,CD_USUARIO                        
                        ,CD_MVTO                           
                        ,TP_MVTO                           
                        ,HR_LANCAMENTO_FINAL                       
                        ,VL_DESCONTO_CONTA                 
                        ,SN_REPASSOU_VIRTUAL               
--                        ,VL_NOTA                                   
                        ,SN_IMP_LAUDO_ALTERACAO                    
                        ,VL_PONTO_REPASSADO                        
                        ,CD_ITMVTO                                 
                        ,SN_REPASSADO                              
                        ,FATOR_RELACIONADO                         
                        ,NR_SEQ_PREIMPRE                           
                        ,CD_CONTA_PAI
                        ,CD_MULTI_EMPRESA                          
                        ,CD_CONTA_KIT                              
                        ,TP_RESULTADO_EXAME_ACH                    
                        ,TP_SITUACAO_ACH                           
                        ,CD_GERACAO_ACH_AUTORIZADO                 
                        ,CD_LANCAMENTO_REG_LANC                    
                        ,CD_REGRA_LANCAMENTO                       
                        ,CD_CONTA_PACOTE                           
                        ,SN_CALC_DIFERENCA_ACOMODACAO              
                        ,NR_DIFEP                                  
                        ,NR_GUIA_ENVIO                             
                        ,ID_IT_ENVIO   )
 (                        SELECT
                         272102 --colocar conta nova
                        ,CD_LANCAMENTO                     
                        ,DT_LANCAMENTO 
                        ,HR_LANCAMENTO                              
                        ,QT_LANCAMENTO                     
                        ,VL_PERCENTUAL_MULTIPLA            
                        ,VL_UNITARIO                       
                        ,VL_FILME_UNITARIO                         
                        ,VL_ACRESCIMO                              
                        ,VL_DESCONTO                               
                        ,CD_GRU_FAT                        
                        ,CD_PRO_FAT                        
                        ,CD_PRESTADOR                      
                        ,NR_PADRAO                         
                        ,VL_HONORARIO_UNITARIO                     
                        ,VL_OPERACIONAL_UNITARIO                   
                        ,CD_PRES_CON                       
                        ,VL_PERCENTUAL_PACIENTE            
                        ,VL_TOTAL_CONTA                            
                        ,CD_IMPORTA_REG_FAT                
                        ,CD_GUIA                           
                        ,SN_PERTENCE_PACOTE                
                        ,VL_BASE_REPASSADO                         
                        ,CD_MOTIVO_GLOSA                       
                        ,QT_CH_UNITARIO                        
                        ,TP_PAGAMENTO                          
                        ,CD_SETOR_PRODUZIU                     
                        ,CD_SETOR                              
                        ,CD_PADRAO                                 
                        ,SN_HORARIO_ESPECIAL                       
                        ,QT_PONTOS                                 
                        ,SN_PROCED_AUTORIZADO                      
                        ,TP_ALTA_UTI_NEO                           
                        ,QT_PESO_RN                                
                        ,QT_MES_GESTACAO                           
                        ,CD_SUS                                    
                        ,CD_TIPO_VINCULO                           
                        ,CD_ATI_MED                                
                        ,VL_SP                                     
                        ,VL_SH                                     
                        ,VL_SD                                     
                        ,VL_ATO                                    
                        ,CD_SUS_AUXILIAR                           
                        ,CD_REG_FAT_PAI                            
                        ,CD_LANCAMENTO_PAI                         
                        ,SN_PROCED_REALIZADO                       
                        ,CD_FRANQUIA                       
                        ,CD_REGRA_ACOPLAMENTO              
                        ,VL_PERC_ACOPLAMENTO               
                        ,SN_PACIENTE_PAGA                  
                        ,CD_REGRA_ATENDIMENTO              
                        ,CD_REGRA_ATENDIMENTO_PRO_FAT      
                        ,CD_REG_FAT_REL                    
                        ,CD_LANCAMENTO_REL                 
                        ,CD_USUARIO                        
                        ,CD_MVTO                           
                        ,TP_MVTO                           
                        ,HR_LANCAMENTO_FINAL                       
                        ,VL_DESCONTO_CONTA                 
                        ,SN_REPASSOU_VIRTUAL               
--                        ,'' --VL_NOTA                                    
                        ,SN_IMP_LAUDO_ALTERACAO                    
                        ,VL_PONTO_REPASSADO                        
                        ,CD_ITMVTO                                 
                        ,SN_REPASSADO                              
                        ,FATOR_RELACIONADO                         
                        ,NR_SEQ_PREIMPRE                           
                        ,CD_CONTA_PAI
                        ,CD_MULTI_EMPRESA                          
                        ,CD_CONTA_KIT                              
                        ,TP_RESULTADO_EXAME_ACH                    
                        ,TP_SITUACAO_ACH                           
                        ,CD_GERACAO_ACH_AUTORIZADO                 
                        ,CD_LANCAMENTO_REG_LANC                    
                        ,CD_REGRA_LANCAMENTO                       
                        ,CD_CONTA_PACOTE                           
                        ,SN_CALC_DIFERENCA_ACOMODACAO              
                        ,NR_DIFEP                                  
                        ,NR_GUIA_ENVIO                             
                        ,ID_IT_ENVIO                               
                        FROM dbamv.ITREG_FAT I
                        WHERE I.cd_reg_fat= 113475 --colocar conta espelho
                        );
commit;
