INSERT INTO COD_PRO  (CD_PRO_FAT,CD_CONVENIO,DS_CODIGO_COBRANCA,DS_NOME_COBRANCA,DS_UNIDADE_COBRANCA,TP_ATENDIMENTO,CD_MULTI_EMPRESA,CD_COD_PRO)
(SELECT CD_PRO_FAT,213,DS_CODIGO_COBRANCA,DS_NOME_COBRANCA,DS_UNIDADE_COBRANCA,TP_ATENDIMENTO,7,SEQ_COD_PRO.NEXTVAL FROM COD_PRO  WHERE CD_CONVENIO = 48 AND CD_PRO_FAT NOT IN (10000036,10000061));
COMMIT;

