-----------------------------PRODUCAO----------------------------------------------------------------
SELECT
*
FROM
(SELECT
'HOSPITALAR'TIPO_CONTA,
RF.CD_ATENDIMENTO,
PCT.NM_PACIENTE,
RF.CD_REG_FAT CONTA,
RF.CD_CONVENIO,
CONV.NM_CONVENIO,
RF.VL_TOTAL_CONTA

FROM 
REG_FAT RF
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = RF.CD_CONVENIO
INNER JOIN ATENDIME ATEND ON ATEND.CD_ATENDIMENTO = RF.CD_ATENDIMENTO
INNER JOIN PACIENTE PCT ON PCT.CD_PACIENTE = ATEND.CD_PACIENTE
WHERE TRUNC(RF.DT_INICIO)BETWEEN '01/01/2021' AND SYSDATE
AND RF.CD_MULTI_EMPRESA = 7
AND CONV.TP_CONVENIO NOT IN ('P')
AND RF.SN_FECHADA = 'N'
AND RF.TP_CLASSIFICACAO_CONTA NOT IN ('O')

UNION ALL

SELECT 
DISTINCT
'AMBULATORIAL'TIPO_CONTA,
IRAMB.CD_ATENDIMENTO,
PCT1.NM_PACIENTE,
RAMB.CD_REG_AMB CONTA,
IRAMB.CD_CONVENIO,
CONV1.NM_CONVENIO,
RAMB.VL_TOTAL_CONTA
FROM
ITREG_AMB IRAMB 
INNER JOIN REG_AMB RAMB ON RAMB.CD_REG_AMB = IRAMB.CD_REG_AMB
INNER JOIN CONVENIO CONV1 ON CONV1.CD_CONVENIO = IRAMB.CD_CONVENIO
INNER JOIN ATENDIME ATEND1 ON ATEND1.CD_ATENDIMENTO = IRAMB.CD_ATENDIMENTO
INNER JOIN PACIENTE PCT1 ON PCT1.CD_PACIENTE = ATEND1.CD_PACIENTE
WHERE TRUNC(IRAMB.HR_LANCAMENTO) BETWEEN '01/01/2021' AND SYSDATE
AND RAMB.CD_MULTI_EMPRESA = 7
AND CONV1.TP_CONVENIO NOT IN ('P')
AND IRAMB.SN_FECHADA = 'N'
AND RAMB.VL_TOTAL_CONTA <> '0'
)X
ORDER BY X.NM_CONVENIO
;


--------------------------FATURADO --------------------------------------------------------------
SELECT
*
FROM
(
SELECT
'HOSPITALAR'TIPO_CONTA,
RF.CD_ATENDIMENTO,
PCT.NM_PACIENTE,
RF.CD_REG_FAT CONTA,
RF.CD_CONVENIO,
CONV.NM_CONVENIO,
RF.VL_TOTAL_CONTA

FROM 
REG_FAT RF
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = RF.CD_CONVENIO
INNER JOIN ATENDIME ATEND ON ATEND.CD_ATENDIMENTO = RF.CD_ATENDIMENTO
INNER JOIN PACIENTE PCT ON PCT.CD_PACIENTE = ATEND.CD_PACIENTE
WHERE TRUNC(RF.DT_INICIO)BETWEEN '01/01/2021' AND SYSDATE
AND RF.CD_MULTI_EMPRESA = 7
AND CONV.TP_CONVENIO NOT IN ('P')
AND RF.SN_FECHADA = 'S'
AND RF.CD_REMESSA IS NULL
AND RF.TP_CLASSIFICACAO_CONTA NOT IN ('O')

UNION ALL

SELECT 
DISTINCT
'AMBULATORIAL'TIPO_CONTA,
IRAMB.CD_ATENDIMENTO,
PCT1.NM_PACIENTE,
RAMB.CD_REG_AMB CONTA,
IRAMB.CD_CONVENIO,
CONV1.NM_CONVENIO,
RAMB.VL_TOTAL_CONTA
FROM
ITREG_AMB IRAMB 
INNER JOIN REG_AMB RAMB ON RAMB.CD_REG_AMB = IRAMB.CD_REG_AMB
INNER JOIN CONVENIO CONV1 ON CONV1.CD_CONVENIO = IRAMB.CD_CONVENIO
INNER JOIN ATENDIME ATEND1 ON ATEND1.CD_ATENDIMENTO = IRAMB.CD_ATENDIMENTO
INNER JOIN PACIENTE PCT1 ON PCT1.CD_PACIENTE = ATEND1.CD_PACIENTE
WHERE TRUNC(IRAMB.HR_LANCAMENTO) BETWEEN '01/01/2021' AND SYSDATE
AND RAMB.CD_MULTI_EMPRESA = 7
AND CONV1.TP_CONVENIO NOT IN ('P')
AND IRAMB.SN_FECHADA = 'S'
AND RAMB.VL_TOTAL_CONTA <> '0'
)X
ORDER BY  X.NM_CONVENIO
;
----------------------------------------NOTA_EMITIDA--------------------------------------------------
SELECT 
*
FROM
(
SELECT
'HOSPITALAR'TIPO_CONTA,
RF.CD_ATENDIMENTO,
PCT.NM_PACIENTE,
RF.CD_REG_FAT CONTA,
RF.CD_REMESSA,
RF.CD_CONVENIO,
CONV.NM_CONVENIO,
SUM(ITF.VL_ITFAT_NF) VL_TOTAL_CONTA,
NF.DT_EMISSAO,
NF.VL_TOTAL_NOTA VL_TOTAL_NF_REMESSA


FROM 
REG_FAT RF
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = RF.CD_CONVENIO
INNER JOIN ATENDIME ATEND ON ATEND.CD_ATENDIMENTO = RF.CD_ATENDIMENTO
INNER JOIN PACIENTE PCT ON PCT.CD_PACIENTE = ATEND.CD_PACIENTE
INNER JOIN REMESSA_FATURA REM ON REM.CD_REMESSA = RF.CD_REMESSA
INNER JOIN ITFAT_NOTA_FISCAL ITF ON ITF.CD_REMESSA = RF.CD_REMESSA AND RF.CD_REG_FAT = ITF.CD_REG_FAT
INNER JOIN NOTA_FISCAL NF ON NF.CD_NOTA_FISCAL = ITF.CD_NOTA_FISCAL
WHERE TRUNC(NF.DT_EMISSAO)BETWEEN '01/01/2021' AND SYSDATE
AND CONV.TP_CONVENIO NOT IN ('P')
AND RF.CD_MULTI_EMPRESA = 7
AND RF.SN_FECHADA = 'S'
GROUP BY 
RF.CD_ATENDIMENTO,
PCT.NM_PACIENTE,
RF.CD_REG_FAT,
RF.CD_REMESSA,
RF.CD_CONVENIO,
CONV.NM_CONVENIO,
RF.VL_TOTAL_CONTA,
NF.VL_TOTAL_NOTA,
NF.DT_EMISSAO

UNION ALL 

SELECT 
DISTINCT
'AMBULATORIAL'TIPO_CONTA,
IRAMB.CD_ATENDIMENTO,
PCT1.NM_PACIENTE,
IRAMB.CD_REG_AMB CONTA,
RAMB.CD_REMESSA,
IRAMB.CD_CONVENIO,
CONV1.NM_CONVENIO,
RAMB.VL_TOTAL_CONTA,
NF1.DT_EMISSAO,
NF1.VL_TOTAL_NOTA


FROM 
ITREG_AMB IRAMB
INNER JOIN REG_AMB RAMB ON RAMB.CD_REG_AMB = IRAMB.CD_REG_AMB
INNER JOIN CONVENIO CONV1 ON CONV1.CD_CONVENIO = IRAMB.CD_CONVENIO
INNER JOIN ATENDIME ATEND1 ON ATEND1.CD_ATENDIMENTO = IRAMB.CD_ATENDIMENTO
INNER JOIN PACIENTE PCT1 ON PCT1.CD_PACIENTE = ATEND1.CD_PACIENTE 
INNER JOIN REMESSA_FATURA RM1 ON RM1.CD_REMESSA = RAMB.CD_REMESSA
INNER JOIN ITFAT_NOTA_FISCAL ITF1 ON ITF1.CD_REMESSA = RM1.CD_REMESSA AND IRAMB.CD_REG_AMB = ITF1.CD_REG_AMB
INNER JOIN NOTA_FISCAL NF1 ON NF1.CD_NOTA_FISCAL = ITF1.CD_NOTA_FISCAL
WHERE TRUNC(NF1.DT_EMISSAO)BETWEEN '01/01/2021' AND SYSDATE
AND CONV1.TP_CONVENIO NOT IN ('P')
AND RAMB.CD_MULTI_EMPRESA = 7
AND IRAMB.SN_FECHADA = 'S'
)X
ORDER BY X.CD_REMESSA, X.NM_CONVENIO







