SELECT
ECONV.CD_MULTI_EMPRESA,
CONV.NM_CONVENIO,
NF.CD_ATENDIMENTO,
PCT.NM_PACIENTE,
NF.NM_CLIENTE RESP_PAGAMENTO,
ATEND.CD_PACIENTE,
CASE WHEN NF.CD_STATUS = 'E' THEN 'EMITIDA' ELSE 'CANCELADA' END STATUS_NF,
NF.DT_EMISSAO,
NF.NR_ID_NOTA_FISCAL NR_RPS,
NF.NR_NOTA_FISCAL_NFE NR_NFE,
CASE 
  WHEN ATEND.TP_ATENDIMENTO = 'I' 
       THEN 'HOSPITAL'
  WHEN ATEND.TP_ATENDIMENTO = 'U'
       THEN 'URGENCIA'
  WHEN ATEND.TP_ATENDIMENTO = 'A'    
       THEN 'AMBULATORIO'   
  WHEN ATEND.TP_ATENDIMENTO = 'E'
       THEN 'EXTERNO'
END TIPO_ATENDIMENTO,                     
NF.CD_REG_FAT||NF.CD_REG_AMB NR_CONTA,
NF.CD_REMESSA,
CR.VL_PREVISTO VL_BRUTO_NOTA,
NF.VL_TOTAL_NOTA VL_LIQ_NOTA,
NF.DT_CANCELAMENTO,
CR.CD_CON_REC,
ICR.VL_SOMA_RECEBIDO VL_RECEBIDO,
CASE 
  WHEN ICR.TP_QUITACAO = 'C'
    THEN 'COMPROMETIDO'
  WHEN ICR.TP_QUITACAO = 'L'
    THEN 'CANCELADO'
  WHEN ICR.TP_QUITACAO = 'P'
    THEN 'PARC_RECEBIDO'
  WHEN ICR.TP_QUITACAO = 'Q'
    THEN'QUITADO'    
  END TP_RECEBIMENTO  
FROM
CONVENIO CONV 
INNER JOIN EMPRESA_CONVENIO ECONV ON ECONV.CD_CONVENIO = CONV.CD_CONVENIO
INNER JOIN NOTA_FISCAL NF ON NF.CD_CONVENIO = ECONV.CD_CONVENIO 
INNER JOIN ATENDIME ATEND ON ATEND.CD_ATENDIMENTO = NF.CD_ATENDIMENTO
INNER JOIN PACIENTE PCT ON PCT.CD_PACIENTE = ATEND.CD_PACIENTE
INNER JOIN CON_REC CR ON CR.CD_NOTA_FISCAL = NF.CD_NOTA_FISCAL
INNER JOIN ITCON_REC ICR ON ICR.CD_CON_REC = CR.CD_CON_REC
WHERE NF.DT_EMISSAO BETWEEN '01/01/2018' AND SYSDATE
AND ECONV.CD_MULTI_EMPRESA = 3 
AND CONV.TP_CONVENIO = 'P'
AND NF.CD_STATUS IN ('E','C')
--AND NF.CD_REG_FAT = 307591 
--AND NF.NR_ID_NOTA_FISCAL IN (146788,146825)
ORDER BY NF.DT_EMISSAO, NF.NR_ID_NOTA_FISCAL


