SELECT 
DISTINCT 
PCT.CD_PACOTE ,
PF.DS_PRO_FAT,
CONV.CD_CONVENIO||' - '||CONV.NM_CONVENIO NM_CONVENIO,
PEXC.CD_GRU_PRO CD_GRU_PRO_EXC,
GP.CD_GRU_PRO,
CASE WHEN GP.CD_GRU_PRO = PEXC.CD_GRU_PRO THEN 'SIM' ELSE 'NÃO' END FORA_PACOTE,
PEXC.CD_PRO_FAT CD_PRO_FAT_EXC



FROM 
DBAMV.PACOTE PCT 
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = PCT.CD_CONVENIO
INNER JOIN EMPRESA_CONVENIO ECONV ON ECONV.CD_CONVENIO = CONV.CD_CONVENIO
LEFT JOIN  CON_PLA CPLA ON CPLA.CD_CON_PLA = PCT.CD_CON_PLA
INNER JOIN PACOTE_EXCECAO PEXC ON PEXC.CD_PACOTE = PCT.CD_PACOTE
INNER JOIN PRO_FAT PF ON PF.CD_PRO_FAT = PCT.CD_PRO_FAT_PACOTE
INNER JOIN GRU_PRO GP ON GP.CD_GRU_PRO = (SELECT  XG.CD_GRU_PRO FROM GRU_PRO XG WHERE GP.CD_GRU_PRO = XG.CD_GRU_PRO)
WHERE GP.CD_GRU_PRO = (SELECT XG.CD_GRU_PRO FROM GRU_PRO XG WHERE XG.CD_GRU_PRO = GP.CD_GRU_PRO)
AND PCT.CD_PACOTE = 15849 
AND PCT.DT_VIGENCIA_FINAL IS NULL
ORDER BY 
         GP.CD_GRU_PRO


