
SELECT 
CD_GRU_PRO,
DS_GRU_PRO,
CASE WHEN CD_PACOTE_EXCECAO IS NULL THEN 'PERT_GRU_PRO' ELSE 'CONST_EXC_PACOTE' END GRU_PRO_POS 
FROM
(
SELECT 
DISTINCT
A.CD_GRU_PRO,
A.DS_GRU_PRO DS_GRU_PRO,
(SELECT NULL FROM GRU_PRO B WHERE B.CD_GRU_PRO = A.CD_GRU_PRO)CD_PACOTE_EXCECAO
FROM 
GRU_PRO A

union all

SELECT 
DISTINCT
PEXC.CD_GRU_PRO,
GPEX1.DS_GRU_PRO,
PEXC.CD_PACOTE_EXCECAO
FROM 
DBAMV.PACOTE PCT 
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = PCT.CD_CONVENIO
INNER JOIN EMPRESA_CONVENIO ECONV ON ECONV.CD_CONVENIO = CONV.CD_CONVENIO
LEFT JOIN  CON_PLA CPLA ON CPLA.CD_CON_PLA = PCT.CD_CON_PLA
INNER JOIN PACOTE_EXCECAO PEXC ON PEXC.CD_PACOTE = PCT.CD_PACOTE
INNER JOIN GRU_PRO GPEX1 ON GPEX1.CD_GRU_PRO = PEXC.CD_GRU_PRO
WHERE PCT.CD_PACOTE = 15849 
AND PCT.DT_VIGENCIA_FINAL IS NULL
AND PEXC.CD_GRU_PRO IS NOT NULL
ORDER BY 1
)
