----  
SELECT 
DISTINCT
PCT.CD_PACOTE,
PF.DS_PRO_FAT DS_PACOTE, 
CONV.CD_CONVENIO||' - '||CONV.NM_CONVENIO NM_CONVENIO

FROM 
DBAMV.PACOTE PCT 
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = PCT.CD_CONVENIO
INNER JOIN EMPRESA_CONVENIO ECONV ON ECONV.CD_CONVENIO = CONV.CD_CONVENIO
LEFT JOIN  CON_PLA CPLA ON CPLA.CD_CON_PLA = PCT.CD_CON_PLA
INNER JOIN PACOTE_EXCECAO PEXC ON PEXC.CD_PACOTE = PCT.CD_PACOTE
INNER JOIN PRO_FAT PF ON PF.CD_PRO_FAT = PCT.CD_PRO_FAT_PACOTE
INNER JOIN GRU_PRO GP ON GP.CD_GRU_PRO = (SELECT  XG.CD_GRU_PRO FROM GRU_PRO XG WHERE GP.CD_GRU_PRO = XG.CD_GRU_PRO)
WHERE GP.CD_GRU_PRO = (SELECT XG.CD_GRU_PRO FROM GRU_PRO XG WHERE XG.CD_GRU_PRO = GP.CD_GRU_PRO)
AND PCT.CD_PACOTE = 15849 -- FILTRO 
AND PCT.DT_VIGENCIA_FINAL IS NULL

;

SELECT 
CD_GRU_PRO,
DS_GRU_PRO DS_GRU_PRO_FATURAMENTO
FROM 
GRU_PRO
ORDER BY CD_GRU_PRO

;
SELECT 
DISTINCT
PCT.CD_PACOTE,
PEXC.CD_GRU_PRO,
GPEX1.DS_GRU_PRO
FROM 
DBAMV.PACOTE PCT 
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = PCT.CD_CONVENIO
INNER JOIN EMPRESA_CONVENIO ECONV ON ECONV.CD_CONVENIO = CONV.CD_CONVENIO
LEFT JOIN  CON_PLA CPLA ON CPLA.CD_CON_PLA = PCT.CD_CON_PLA
INNER JOIN PACOTE_EXCECAO PEXC ON PEXC.CD_PACOTE = PCT.CD_PACOTE
INNER JOIN GRU_PRO GPEX1 ON GPEX1.CD_GRU_PRO = PEXC.CD_GRU_PRO
WHERE  PCT.CD_PACOTE = 15849 
AND PCT.DT_VIGENCIA_FINAL IS NULL
AND PEXC.CD_GRU_PRO IS NOT NULL
ORDER BY PEXC.CD_GRU_PRO

------ TRAZER COLUNA SN_PERTENCE_PACOTE ----
   --- (QUANDO CD_GRU_PRO = CD_GRU_PRO  TRAZER VALOR "SIM")
   ----( QUANDO CD_GRU_PRO <> CD_GRU_PRO TRAZER VALOR "NÃO")
;


SELECT 
PEXC.CD_PACOTE,
PEXC.CD_PRO_FAT||' - '||(SELECT EXC.DS_PRO_FAT FROM PRO_FAT EXC WHERE EXC.CD_PRO_FAT = PEXC.CD_PRO_FAT)PRO_FAT_EXCECAO
FROM 
DBAMV.PACOTE PCT 
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = PCT.CD_CONVENIO
INNER JOIN EMPRESA_CONVENIO ECONV ON ECONV.CD_CONVENIO = CONV.CD_CONVENIO
LEFT JOIN  CON_PLA CPLA ON CPLA.CD_CON_PLA = PCT.CD_CON_PLA
INNER JOIN PACOTE_EXCECAO PEXC ON PEXC.CD_PACOTE = PCT.CD_PACOTE
WHERE  PCT.CD_PACOTE = 15849 
AND PCT.DT_VIGENCIA_FINAL IS NULL

