SELECT A.CD_MVTO_ESTOQUE , B.CD_PRODUTO, C.DS_PRODUTO, C.CD_PRO_FAT, E.TP_PROIBICAO, E.TP_ATENDIMENTO FROM MVTO_ESTOQUE A --WHERE 
INNER JOIN ITMVTO_ESTOQUE B ON B.CD_MVTO_ESTOQUE = A.CD_MVTO_ESTOQUE
INNER JOIN PRODUTO C ON C.CD_PRODUTO = B.CD_PRODUTO
INNER JOIN ATENDIME D ON D.CD_ATENDIMENTO = A.CD_ATENDIMENTO
INNER JOIN PROIBICAO E ON E.CD_CONVENIO = D.CD_CONVENIO
                       AND E.CD_CON_PLA = D.CD_CON_PLA
                       AND E.CD_PRO_FAT = C.CD_PRO_FAT
                       AND (E.TP_ATENDIMENTO = D.TP_ATENDIMENTO OR E.TP_ATENDIMENTO = 'T')
WHERE A.CD_AVISO_CIRURGIA = 216052
AND E.TP_PROIBICAO = 'FC'
--AND E.TP_PROIBICAO IN ('T','E')
--AND E.DT_FIM_PROIBICAO IS NULL
