
SELECT 
/*PB.CD_MULTI_EMPRESA,
PB.CD_PRO_FAT,
PB.CD_CONVENIO,
PB.CD_CON_PLA,
PB.TP_PROIBICAO,
PB.TP_ATENDIMENTO,
PB.DT_INICIAL_PROIBICAO
*/
PB.CD_CONVENIO,
CONV.NM_CONVENIO,
COUNT(*)QTD
FROM 
PROIBICAO PB
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = PB.CD_CONVENIO
WHERE PB.CD_PRO_FAT IN
(
SELECT 
A.CD_PRO_FAT
FROM 
PRO_FAT A 
INNER JOIN GRU_PRO B ON B.CD_GRU_PRO = A.CD_GRU_PRO
WHERE B.TP_GRU_PRO = 'MT'
AND A.SN_ATIVO = 'S' 
)AND PB.CD_MULTI_EMPRESA = 7
AND PB.TP_PROIBICAO = 'AG'
AND PB.DT_FIM_PROIBICAO IS NULL
AND CONV.TP_CONVENIO = 'C'
GROUP BY PB.CD_CONVENIO,
CONV.NM_CONVENIO
ORDER BY PB.CD_CONVENIO


