SELECT * FROM DBAMV.VW_OVMD_GUIA_SADT_ELETIVO A WHERE A.ID LIKE '1550607%'---A.dh_solicitado = '27/10/2021'

SELECT * FROM IT_AGENDA_CENTRAL X WHERE X.CD_IT_AGENDA_CENTRAL = 22398822
SELECT * FROM ITEM_AGENDAMENTO

SELECT * FROM MOVIMENTO_AGENDA_CENTRAL WHERE CD_MOVIMENTO_AGENDA_CENTRAL = 1550607
SELECT * FROM IT_MOVIMENTO_AGENDA_CENTRAL WHERE CD_MOVIMENTO_AGENDA_CENTRAL = 1550607
SELECT * FROM IT_AGENDA_CENTRAL X WHERE X.CD_IT_AGENDA_CENTRAL = 22398822


SELECT * FROM GUIA

SELECT * FROM ALL_TAB_COLUMNS Z WHERE Z.column_name like '%CD_MOVIMENTO_AGENDA_CENTRAL%'
