-- AQUI SÃO OS PACOTES ATIVOS PARA EMPREAS 7 
SELECT 
PCT.CD_PACOTE,
PCT.CD_PRO_FAT_PACOTE,
PF.DS_PRO_FAT,
PCT.CD_CONVENIO,
CONV.NM_CONVENIO 
FROM 
DBAMV.PACOTE PCT
INNER JOIN DBAMV.PRO_FAT PF ON PF.CD_PRO_FAT = PCT.CD_PRO_FAT_PACOTE
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = PCT.CD_CONVENIO
WHERE PCT.CD_MULTI_EMPRESA = 7
AND PCT.DT_VIGENCIA_FINAL IS NULL
AND PCT.CD_PACOTE = 14500
ORDER BY PCT.CD_CONVENIO

;
-- AQUI SÃO AS EXCECÕES DO PACOTE CONTENDO OS GRUPOS DE PROCEDIMENTO QUE ESTA NA EXCEÇÃO
SELECT 
PCE.CD_PACOTE,
PCE.CD_GRU_PRO,
GP1.DS_GRU_PRO

FROM 
DBAMV.PACOTE_EXCECAO PCE
INNER JOIN GRU_PRO GP1 ON GP1.CD_GRU_PRO = PCE.CD_GRU_PRO
WHERE PCE.CD_PACOTE = 14500
ORDER BY PCE.CD_GRU_PRO
; 
-- AQUI SÃO AS EXCECÕES DO PACOTE CONTENDO OS PROCEDIMENTO QUE ESTA NA EXCEÇÃO
SELECT 
PCE.CD_PACOTE,
PCE.CD_PRO_FAT,
PF1.DS_PRO_FAT
FROM 
DBAMV.PACOTE_EXCECAO PCE
INNER JOIN DBAMV.PRO_FAT PF1 ON PF1.CD_PRO_FAT = PCE.CD_PRO_FAT
WHERE PCE.CD_PACOTE = 14500
ORDER BY PCE.CD_GRU_PRO

;
-- AQUI SÃO OS GRUPOS DE PROCEDIMENTOS QUE POSSUEM NO SISTEMA 
-- OBS: NO PAINEL DEVERÁ SER APENAS APRESENTADOS OS GRUPO PROCEDIMENTOS  QUE NÃO ESTÃO NA EXCECÃO DO PACOTE 
SELECT 
GP.CD_GRU_PRO,
GP.DS_GRU_PRO
FROM 
DBAMV.GRU_PRO GP
ORDER BY GP.CD_GRU_PRO
         


-- 19,23,24,27,10



