SELECT 

DECODE (C.CD_MULTI_EMPRESA,3,'CSSJ',4,'HST',7,'HSC',10,'HSJ',25,'HCNSC')EMPRESA,
CASE WHEN TO_CHAR(C.DT_ATENDIMENTO,'MON') = 'JAN' THEN 'JAN'
     WHEN TO_CHAR(C.DT_ATENDIMENTO,'MON') = 'FEB' THEN 'FEV'
     WHEN TO_CHAR(C.DT_ATENDIMENTO,'MON') = 'MAR' THEN 'MAR'
     WHEN TO_CHAR(C.DT_ATENDIMENTO,'MON') = 'APR' THEN 'ABR'
     WHEN TO_CHAR(C.DT_ATENDIMENTO,'MON') = 'MAY' THEN 'MAI'
     WHEN TO_CHAR(C.DT_ATENDIMENTO,'MON') = 'JUN' THEN 'JUN'
     WHEN TO_CHAR(C.DT_ATENDIMENTO,'MON') = 'JUL' THEN 'JUL'
     WHEN TO_CHAR(C.DT_ATENDIMENTO,'MON') = 'AUG' THEN 'AGO'
     WHEN TO_CHAR(C.DT_ATENDIMENTO,'MON') = 'SEP' THEN 'SET'
     WHEN TO_CHAR(C.DT_ATENDIMENTO,'MON') = 'OCT' THEN 'OUT'
     WHEN TO_CHAR(C.DT_ATENDIMENTO,'MON') = 'NOV' THEN 'NOV'
     WHEN TO_CHAR(C.DT_ATENDIMENTO,'MON') = 'DEC' THEN 'DEZ'
     END CMPT,
C.CD_ATENDIMENTO,
A.CD_REG_FAT,
C.DT_ATENDIMENTO,
CASE WHEN C.TP_ATENDIMENTO = 'I' THEN 'INTERNACAO' END TP_ATENDIMENTO,
E.NM_CONVENIO,
CASE WHEN B.CD_REG_FAT IS NOT NULL THEN 'INTERNADO' END CONTA,
B.VL_TOTAL_CONTA VL_FATURADO,
B.VL_TOTAL_CONTA ,
B.DT_INICIO DT_ABERTURA,
B.DT_FINAL DT_FECHAMENTO,
C.DT_ALTA,
CASE WHEN B.TP_CLASSIFICACAO_CONTA = 'P' THEN 'PARCIAL'
   WHEN B.TP_CLASSIFICACAO_CONTA = 'N'  THEN 'SEM_CLASSIFICACAO'
    END CLASSIFICACAO ,
B.SN_FECHADA,
D.SN_FECHADA REMESSA_FECHADA,
CASE WHEN I.CD_CON_REC IS NOT NULL THEN 'S' ELSE 'N' END CONTAS_RECEBER,
A.SN_PERTENCE_PACOTE POSSUI_PACOTE,
B.CD_REMESSA,
D.DT_ABERTURA,
D.DT_FECHAMENTO,
D.DT_ENTREGA_DA_FATURA,
D.DT_PREVISTA_PARA_PGTO,
H.NR_ID_NOTA_FISCAL RPS,
H.DT_EMISSAO,
H.VL_TOTAL_NOTA,
H.CD_NOTA_FISCAL,
J.DS_GRU_FAT,
A.CD_LANCAMENTO,
A.DT_LANCAMENTO,
A.CD_PRO_FAT,
PF.DS_PRO_FAT,
A.QT_LANCAMENTO,
A.VL_TOTAL_CONTA VL_ITEM,
A.CD_PRESTADOR,
(SELECT X.NM_PRESTADOR FROM PRESTADOR X WHERE X.CD_PRESTADOR = A.CD_PRESTADOR)NM_PRESTADOR
FROM 
DBAMV.ITREG_FAT A 
INNER JOIN DBAMV.REG_FAT B ON B.CD_REG_FAT = A.CD_REG_FAT
INNER JOIN ATENDIME C ON C.CD_ATENDIMENTO = B.CD_ATENDIMENTO
INNER JOIN REMESSA_FATURA D ON D.CD_REMESSA = B.CD_REMESSA
INNER JOIN CONVENIO E ON E.CD_CONVENIO = B.CD_CONVENIO
INNER JOIN FATURA F ON F.CD_FATURA = D.CD_FATURA
LEFT JOIN ITFAT_NOTA_FISCAL G ON G.CD_REMESSA = D.CD_REMESSA  AND G.CD_LANCAMENTO_FAT = A.CD_LANCAMENTO
AND G.CD_REG_FAT = A.CD_REG_FAT and g.id_it_envio = a.id_it_envio
LEFT JOIN NOTA_FISCAL H ON H.CD_NOTA_FISCAL = G.CD_NOTA_FISCAL
LEFT JOIN CON_REC I ON I.CD_NOTA_FISCAL = H.CD_NOTA_FISCAL
INNER JOIN GRU_FAT J ON J.CD_GRU_FAT = A.CD_GRU_FAT
INNER JOIN PRO_FAT PF ON PF.CD_PRO_FAT = A.CD_PRO_FAT
INNER JOIN PRESTADOR PR ON PR.CD_PRESTADOR = C.CD_PRESTADOR
WHERE TO_DATE(C.DT_ATENDIMENTO,'DD/MM/RRRR') BETWEEN TO_DATE('01/11/2021','DD/MM/RRRR') AND TO_DATE('31/12/2021','DD/MM/RRRR')
AND  C.CD_MULTI_EMPRESA = 3
--and c.cd_atendimento = 2943576
--AND A.CD_REG_FAT IN (188932)
--AND A.CD_LANCAMENTO IN (622,610)
AND A.SN_PERTENCE_PACOTE = 'N'
ORDER BY 
     C.DT_ATENDIMENTO,
      C.CD_ATENDIMENTO , 
      B.CD_REG_FAT , 
      A.CD_LANCAMENTO


--select * from empresa_prestador where cd_prestador = 25371---
--select * from prestador where cd_prestador = 25371
---select * from reg_repasse where cd_reg_repasse = 345

--SELECT * FROM itfat_nota_fiscal nf where nf.cd_remessa = 124877 and nf.cd_reg_fat = 164500
--select * from itreg_fat where cd_reg_Fat = 164500

--select * from remessa_Fatura xx where xx.cd_remessa = 130154
--select * from fatura where cd_fatura = 16774

