SELECT * FROM (
SELECT P.CD_PACIENTE || ' - ' || UPPER(P.NM_PACIENTE) CD_PACIENTE,
       R.CD_REG_FAT CONTA,
       R.NR_GUIA,
       NVL(TO_CHAR(A.DT_ATENDIMENTO, 'DD/MM/YYYY'), '') DT_INTERN,
       NVL(TO_CHAR(A.DT_ALTA, 'DD/MM/YYYY'), '') DT_ALTA,
       A.CD_LEITO || ' - ' || L.DS_LEITO CD_LEITO,
       R.CD_CONVENIO || ' - ' || C.NM_RAZAO_SOCIAL CD_CONVENIO,
       R.DT_INICIO,
       R.DT_FINAL,
       R.VL_TOTAL_CONTA,
       AC.CD_MOTIVO_AUDITORIA,
       M.DS_MOTIVO_AUDITORIA,
       AC.CD_PRO_FAT,
       PR.DS_PRO_FAT,
       MIN(AC.CD_LANCAMENTO_FAT) CD_LANCAMENTO,
       MIN(AC.CD_AUDITORIA_CONTA) CD_AUDITORIA_CONTA_I,
       MIN(AC.CD_AUDITORIA_CONTA) CD_AUDITORIA_CONTA_F,
       A.CD_ATENDIMENTO,
    --   P.NM_PACIENTE,


        CASE WHEN P.SN_UTILIZA_NOME_SOCIAL = 'S' 
     AND P.NM_SOCIAL_PACIENTE IS NOT NULL THEN 'SOCIAL: '||P.NM_SOCIAL_PACIENTE 
ELSE P.NM_PACIENTE END NM_PACIENTE,


       C.NM_CONVENIO,
       G.DS_GRU_PRO,
       G.CD_GRU_PRO,
       INITCAP(S.NM_SETOR) NM_SETOR,
       S.CD_SETOR,
       SUM(AC.VL_TOTAL_CONTA_ANT) VL_FATURA,
       SUM(NVL(AC.VL_TOTAL_CONTA, 0) -
           (NVL(AC.VL_TOTAL_CONTA, 0) -
            (NVL(AC.VL_TOTAL_CONTA, 0) *
             (NVL(AC.QT_LANCAMENTO, 0) /
              DECODE(NVL(AC.QT_LANCAMENTO_ANT, 1),
                     0,
                     1,
                     NVL(AC.QT_LANCAMENTO_ANT, 1))) *
             (NVL(AC.VL_PERCENTUAL_MULTIPLA, 0) /
              DECODE(NVL(AC.VL_PERCENTUAL_MULTIPLA_ANT, 1),
                     0,
                     1,
                     NVL(AC.VL_PERCENTUAL_MULTIPLA_ANT, 1)))))) VL_LIBERADO,
       SUM(NVL(AC.VL_TOTAL_CONTA, 0) -
           (NVL(AC.VL_TOTAL_CONTA, 0) *
            (NVL(AC.QT_LANCAMENTO, 0) /
             DECODE(NVL(AC.QT_LANCAMENTO_ANT, 1),
                    0,
                    1,
                    NVL(AC.QT_LANCAMENTO_ANT, 1))) *
            (NVL(AC.VL_PERCENTUAL_MULTIPLA, 0) /
             DECODE(NVL(AC.VL_PERCENTUAL_MULTIPLA_ANT, 1),
                    0,
                    1,
                    NVL(AC.VL_PERCENTUAL_MULTIPLA_ANT, 1))))) VL_GLOSA,
       SUM(NVL(AC.VL_TOTAL_CONTA, 0)) VL_ATUAL,
       SUM(AC.QT_LANCAMENTO) QT_LANCAMENTO_ITEM,
       SUM(AC.QT_LANCAMENTO_ANT) QTD_FATURADO,
       MIN(NVL(AC.VL_UNITARIO, 0)) VL_UNITARIO_AUDITADO,
       MIN(NVL(AC.VL_UNITARIO_ANT, 0)) VL_UNITARIO_AUDITADO_ANT,
       MIN((NVL(AC.VL_TOTAL_CONTA_ANT, 0) - NVL(AC.VL_ACRESCIMO_ANT, 0) +
           NVL(AC.VL_DESCONTO_ANT, 0)) /
           DECODE(NVL(AC.QT_LANCAMENTO_ANT, 1),
                  0,
                  1,
                  NVL(AC.QT_LANCAMENTO_ANT, 1))) VL_UNITARIO_FAT,
       SUM(NVL(AC.VL_TOTAL_CONTA, 0) - NVL(AC.VL_TOTAL_CONTA_ANT, 0)) DIFERENCA_VALOR_TOTAL,
       TO_CHAR(AC.DT_AUDITORIA, 'DD/MM/YYYY HH24:MI') DT_AUDITORIA,
       AC.SN_ACORDO
  FROM DBAMV.PACIENTE         P,
       DBAMV.REG_FAT          R,
       DBAMV.ITREG_FAT        IRF, ---- TABELA ADICIONADA PARA LOCALIZAR COLUNA SN_PERTENCE_PACOTE
       DBAMV.ATENDIME         A,
       DBAMV.LEITO            L,
       DBAMV.GRU_PRO          G,
       DBAMV.CONVENIO         C,
       DBAMV.AUDITORIA_CONTA  AC,
       DBAMV.SETOR            S,
       DBAMV.MOTIVO_AUDITORIA M,
       DBAMV.PRO_FAT          PR
 WHERE A.CD_ATENDIMENTO = R.CD_ATENDIMENTO
   AND R.CD_MULTI_EMPRESA = '{cdMultiEmpresa}'
   AND L.CD_LEITO(+) = A.CD_LEITO
   AND C.CD_CONVENIO = R.CD_CONVENIO                 
   AND AC.CD_REG_FAT = R.CD_REG_FAT
   AND R.CD_REG_FAT = IRF.CD_REG_FAT  -- ADICIONADO PARA CHAMAR A COUNA SN_PERTENCE_PACOTE
   AND AC.CD_LANCAMENTO_FAT = IRF.CD_LANCAMENTO  ---- ADICIONADO ONDE NÃO SERÁ APRESENTADO O LANÇAMENTO QUE CONTEM SN_PERTENCE A PACOTE
   AND AC.CD_ATENDIMENTO = A.CD_ATENDIMENTO
   AND M.CD_MOTIVO_AUDITORIA = AC.CD_MOTIVO_AUDITORIA
   AND P.CD_PACIENTE = A.CD_PACIENTE
   AND PR.CD_PRO_FAT = AC.CD_PRO_FAT
   AND G.CD_GRU_PRO = PR.CD_GRU_PRO
   AND AC.DT_CANCELOU IS NULL
   AND AC.CD_SETOR = S.CD_SETOR
   AND M.TP_MOTIVO_AUDITORIA = 'A'
   AND IRF.SN_PERTENCE_PACOTE = 'N' ---- COLUNA ONDE INFORMA SE O PROCEDIMENTO PERTENCE Á PACOTE 
 
--   AND R.CD_REG_FAT = {V_CD_REG}
 GROUP BY P.CD_PACIENTE || ' - ' || UPPER(P.NM_PACIENTE),
          R.CD_REG_FAT,
          R.NR_GUIA,
          NVL(TO_CHAR(A.DT_ATENDIMENTO, 'DD/MM/YYYY'), ''),
          NVL(TO_CHAR(A.DT_ALTA, 'DD/MM/YYYY'), ''),
          A.CD_LEITO || ' - ' || L.DS_LEITO,
          R.CD_CONVENIO || ' - ' || C.NM_RAZAO_SOCIAL,
          R.DT_INICIO,
          R.DT_FINAL,
          R.VL_TOTAL_CONTA,
          AC.CD_MOTIVO_AUDITORIA,
          M.DS_MOTIVO_AUDITORIA,
          AC.CD_PRO_FAT,
          PR.DS_PRO_FAT,
          A.CD_ATENDIMENTO,
          P.NM_PACIENTE,
          P.NM_SOCIAL_PACIENTE, 
          P.SN_UTILIZA_NOME_SOCIAL,
          C.NM_CONVENIO,
          G.DS_GRU_PRO,
          S.CD_SETOR,
          G.CD_GRU_PRO,
          INITCAP(S.NM_SETOR),
          TO_CHAR(AC.DT_AUDITORIA, 'DD/MM/YYYY HH24:MI'),
          AC.SN_ACORDO
                 
UNION ALL
SELECT DISTINCT
       P.CD_PACIENTE || ' - ' || UPPER(P.NM_PACIENTE) CD_PACIENTE,
       R.CD_REG_AMB CONTA,
       '' NR_GUIA,
       NVL(TO_CHAR(A.DT_ATENDIMENTO, 'DD/MM/YYYY'), '') DT_INTERN,
       NVL(TO_CHAR(A.DT_ALTA, 'DD/MM/YYYY'), '') DT_ALTA,
       A.CD_LEITO || ' - ' || L.DS_LEITO CD_LEITO,
       R.CD_CONVENIO || ' - ' || C.NM_RAZAO_SOCIAL CD_CONVENIO,
       R.DT_LANCAMENTO DT_INICIO,
       R.DT_LANCAMENTO_FINAL DT_FINAL,
       R.VL_TOTAL_CONTA,
       AC.CD_MOTIVO_AUDITORIA,
       M.DS_MOTIVO_AUDITORIA,
       AC.CD_PRO_FAT,
       PR.DS_PRO_FAT,
       MIN(AC.CD_LANCAMENTO_FAT) CD_LANCAMENTO,
       MIN(AC.CD_AUDITORIA_CONTA) CD_AUDITORIA_CONTA_I,
       MIN(AC.CD_AUDITORIA_CONTA) CD_AUDITORIA_CONTA_F,
       A.CD_ATENDIMENTO,
    --   P.NM_PACIENTE,

       CASE WHEN P.SN_UTILIZA_NOME_SOCIAL = 'S' 
     AND P.NM_SOCIAL_PACIENTE IS NOT NULL THEN 'SOCIAL: '||P.NM_SOCIAL_PACIENTE 
ELSE P.NM_PACIENTE END NM_PACIENTE,


       C.NM_CONVENIO,
       G.DS_GRU_PRO,
       G.CD_GRU_PRO,
       INITCAP(S.NM_SETOR) NM_SETOR,
       S.CD_SETOR,
       SUM(AC.VL_TOTAL_CONTA_ANT) VL_FATURA,
       SUM(NVL(AC.VL_TOTAL_CONTA, 0) -
           (NVL(AC.VL_TOTAL_CONTA, 0) -
            (NVL(AC.VL_TOTAL_CONTA, 0) *
             (NVL(AC.QT_LANCAMENTO, 0) /
              DECODE(NVL(AC.QT_LANCAMENTO_ANT, 1),
                     0,
                     1,
                     NVL(AC.QT_LANCAMENTO_ANT, 1))) *
             (NVL(AC.VL_PERCENTUAL_MULTIPLA, 0) /
              DECODE(NVL(AC.VL_PERCENTUAL_MULTIPLA_ANT, 1),
                     0,
                     1,
                     NVL(AC.VL_PERCENTUAL_MULTIPLA_ANT, 1)))))) VL_LIBERADO,
       SUM(NVL(AC.VL_TOTAL_CONTA, 0) -
           (NVL(AC.VL_TOTAL_CONTA, 0) *
            (NVL(AC.QT_LANCAMENTO, 0) /
             DECODE(NVL(AC.QT_LANCAMENTO_ANT, 1),
                    0,
                    1,
                    NVL(AC.QT_LANCAMENTO_ANT, 1))) *
            (NVL(AC.VL_PERCENTUAL_MULTIPLA, 0) /
             DECODE(NVL(AC.VL_PERCENTUAL_MULTIPLA_ANT, 1),
                    0,
                    1,
                    NVL(AC.VL_PERCENTUAL_MULTIPLA_ANT, 1))))) VL_GLOSA,
       SUM(AC.VL_TOTAL_CONTA) VL_ATUAL,
       SUM(AC.QT_LANCAMENTO) QT_LANCAMENTO_ITEM,
       SUM(AC.QT_LANCAMENTO_ANT) QTD_FATURADO,
       MIN(NVL(AC.VL_UNITARIO, 0)) VL_UNITARIO_AUDITADO,
       MIN(NVL(AC.VL_UNITARIO_ANT, 0)) VL_UNITARIO_AUDITADO_ANT,
       MIN((NVL(AC.VL_TOTAL_CONTA_ANT, 0) - NVL(AC.VL_ACRESCIMO_ANT, 0) +
           NVL(AC.VL_DESCONTO_ANT, 0)) /
           DECODE(NVL(AC.QT_LANCAMENTO_ANT, 1),
                  0,
                  1,
                  NVL(AC.QT_LANCAMENTO_ANT, 1))) VL_UNITARIO_FAT,
       SUM(NVL(AC.VL_TOTAL_CONTA, 0) - NVL(AC.VL_TOTAL_CONTA_ANT, 0)) DIFERENCA_VALOR_TOTAL,
       TO_CHAR(AC.DT_AUDITORIA, 'DD/MM/YYYY HH24:MI') DT_AUDITORIA,
       AC.SN_ACORDO
  FROM DBAMV.PACIENTE         P,
       DBAMV.REG_AMB          R,
       DBAMV.ATENDIME         A,
       DBAMV.LEITO            L,
       DBAMV.CONVENIO         C,
       DBAMV.GRU_PRO          G,
       DBAMV.AUDITORIA_CONTA  AC,
       DBAMV.MOTIVO_AUDITORIA M,
       DBAMV.SETOR            S,
       DBAMV.PRO_FAT          PR,
       DBAMV.EMPRESA_CONVENIO,
       DBAMV.ITREG_AMB        IRAMB --- TABELA ADICIONADA PARA CHAMNAR COLUNA SN_PERTENCE_PACOTE
 WHERE EMPRESA_CONVENIO.CD_CONVENIO = C.CD_CONVENIO
   AND EMPRESA_CONVENIO.CD_MULTI_EMPRESA = '{cdMultiEmpresa}'
   --AND R.CD_REG_AMB = {V_CD_REG}
   AND L.CD_LEITO(+) = A.CD_LEITO
   AND C.CD_CONVENIO = R.CD_CONVENIO
   AND AC.CD_ATENDIMENTO = A.CD_ATENDIMENTO
   AND M.CD_MOTIVO_AUDITORIA = AC.CD_MOTIVO_AUDITORIA
   AND P.CD_PACIENTE = A.CD_PACIENTE
   AND R.CD_REG_AMB = AC.CD_REG_AMB
   AND AC.CD_REG_AMB = IRAMB.CD_REG_AMB --- ADICIONADO PARA CHAMAR A COUNA SN_PERTENCE_PACOTE
   AND IRAMB.CD_LANCAMENTO = AC.CD_LANCAMENTO_AMB  --ADICIONADO ONDE NÃO SERÁ APRESENTADO O LANÇAMENTO QUE CONTEM SN_PERTENCE A PACOTE
   AND PR.CD_PRO_FAT = AC.CD_PRO_FAT
   AND G.CD_GRU_PRO = PR.CD_GRU_PRO
   AND AC.DT_CANCELOU IS NULL
   AND AC.CD_SETOR = S.CD_SETOR
   AND M.TP_MOTIVO_AUDITORIA = 'A'
   AND IRAMB.SN_PERTENCE_PACOTE = 'N' ---- COLUNA ONDE INFORMA SE O PROCEDIMENTO PERTENCE Á PACOTE 
 GROUP BY P.CD_PACIENTE || ' - ' || UPPER(P.NM_PACIENTE),
          R.CD_REG_AMB,
          NVL(TO_CHAR(A.DT_ATENDIMENTO, 'DD/MM/YYYY'), ''),
          NVL(TO_CHAR(A.DT_ALTA, 'DD/MM/YYYY'), ''),
          A.CD_LEITO || ' - ' || L.DS_LEITO,
          R.CD_CONVENIO || ' - ' || C.NM_RAZAO_SOCIAL,
          R.DT_LANCAMENTO,
          R.DT_LANCAMENTO_FINAL,
          R.VL_TOTAL_CONTA,
          AC.CD_MOTIVO_AUDITORIA,
          M.DS_MOTIVO_AUDITORIA,
          AC.CD_PRO_FAT,
          PR.DS_PRO_FAT,
          A.CD_ATENDIMENTO,
         P.NM_PACIENTE,
         P.NM_SOCIAL_PACIENTE,
         P.SN_UTILIZA_NOME_SOCIAL,
          C.NM_CONVENIO,
          G.DS_GRU_PRO,
          S.CD_SETOR,
          G.CD_GRU_PRO,
          INITCAP(S.NM_SETOR),
          TO_CHAR(AC.DT_AUDITORIA, 'DD/MM/YYYY HH24:MI'),
          AC.SN_ACORDO
 ORDER BY 1  ASC,
          2  ASC,
          3  ASC,
          4  ASC,
          5  ASC,
          6  ASC,
          7  ASC,
          8  ASC,
          9  ASC,
          20 ASC,
          19 ASC,
          18 ASC,
          10 ASC,
          21 ASC,
          22 ASC,
          24 ASC,
          23 ASC,
          21,
          22,
          32,
          16,
          13
)Q
WHERE Q.CONTA = {V_CD_REG}
