SELECT
decode(NF.CD_MULTI_EMPRESA,3,'CASA DE SAUDE SAO JOSE',
                          4,'HOSPITAL SANTA TEREZA',
                          7,'HOSPITAL SANTA CATARINA',
                          10,'HOSPITAL SAO JOSE',
                          25,'HOSPITAL DE CLINICAS NOSSA SENHORA DA CONCEICAO')CASA,
rem.cd_remessa,
rem.dt_abertura dt_criacao_remessa,
nf.cd_usuario usuario_fechamento_conta,
NF.NR_ID_NOTA_FISCAL NF_MV,
NF.NR_NOTA_FISCAL_NFE NF_PREFEITURA,
NF.CD_STATUS,
NF.CD_ATENDIMENTO,
NF.CD_REG_FAT,
NF.CD_REG_AMB,
NF.CD_REG_FAT CONTA_HOSPITALAR,
CONV.CD_CONVENIO,
CONV.NM_CONVENIO,
NF.NM_CLIENTE,
NF.NR_CGC_CPF CPF_CNPJ,
NF.DT_EMISSAO,
REM.DT_PREVISTA_PARA_PGTO,
CR.VL_PREVISTO VL_BRUTO_NOTA,
NF.VL_TOTAL_NOTA VL_LIQ_NOTA,
SUM(INF.VL_ITFAT_NF)VL_TOTAL_REMESSA
FROM
NOTA_FISCAL NF
LEFT JOIN ITFAT_NOTA_FISCAL INF ON INF.CD_NOTA_FISCAL = NF.CD_NOTA_FISCAL
LEFT JOIN REMESSA_FATURA REM ON REM.CD_REMESSA = INF.CD_REMESSA
LEFT JOIN CONVENIO CONV ON CONV.CD_CONVENIO = NF.CD_CONVENIO
LEFT JOIN CON_REC CR ON CR.CD_NOTA_FISCAL = NF.CD_NOTA_FISCAL
WHERE NF.DT_EMISSAO BETWEEN TO_DATE ('13/05/2021','dd/mm/yyyy') AND TO_DATE (sysdate)--('13/05/2021','dd/mm/yyyy')
AND NF.CD_STATUS in ('E','C')
AND NF.CD_MULTI_EMPRESA in ('3')
AND CONV.CD_CONVENIO = 261 
--AND (CONV.TP_CONVENIO = 'P' OR CONV.TP_CONVENIO IS NULL)
GROUP BY
NF.CD_MULTI_EMPRESA,
rem.cd_remessa,
rem.dt_abertura,
nf.cd_usuario,
NF.NR_ID_NOTA_FISCAL,
NF.NR_NOTA_FISCAL_NFE,
NF.CD_STATUS,
NF.CD_ATENDIMENTO,
NF.CD_REG_FAT,
NF.CD_REG_AMB,
CONV.CD_CONVENIO,
CONV.NM_CONVENIO,
NF.NM_CLIENTE,
NF.NR_CGC_CPF,
NF.DT_EMISSAO,
REM.DT_PREVISTA_PARA_PGTO,
CR.VL_PREVISTO ,
NF.VL_TOTAL_NOTA
ORDER BY 1,3
