SELECT 
ECPLA.CD_CONVENIO,
ECPLA.CD_CON_PLA,
SYSDATE DT_REFERENCIA,
''TIPO_ATENDIMENTO,  
IACOM.CD_TIP_ACOM||' - '||TACOM.DS_TIP_ACOM TIPO_ACOMODACAO ,
VP.CD_PRO_FAT||' - '||PF.DS_PRO_FAT PROCEDIMENTO,
'1'QTD,
(FT.QT_M2_FILME * VIND.VL_M2FILME)VL_FILME,   
CASE WHEN GP.TP_GRU_PRO = 'SD' THEN ROUND(((VP.VL_TOTAL * IACOM.VL_PERCENTUAL_SD)/100),2)
     WHEN GP.TP_GRU_PRO = 'SP' THEN ROUND(((VP.VL_TOTAL * IACOM.VL_PERCENTUAL_PAGO)/100),2)
     WHEN GP.TP_GRU_PRO = 'SH' THEN ROUND(((VP.VL_TOTAL * IACOM.VL_PERCENTUAL_SH)/100),2)
     END VL_TOTAL_PROC,
CASE WHEN GP.TP_GRU_PRO = 'SD' THEN ROUND((VP.VL_TOTAL * IACOM.VL_PERCENTUAL_SD)/100 + (FT.QT_M2_FILME * VIND.VL_M2FILME),2)
     WHEN GP.TP_GRU_PRO = 'SP' THEN ROUND((VP.VL_TOTAL * IACOM.VL_PERCENTUAL_PAGO)/100 + (FT.QT_M2_FILME * VIND.VL_M2FILME),2)
     WHEN GP.TP_GRU_PRO = 'SH' THEN ROUND((VP.VL_TOTAL * IACOM.VL_PERCENTUAL_SH)/100 + (FT.QT_M2_FILME * VIND.VL_M2FILME),2)
     END VL_TOTAL_PROC_REGRA,    
CASE WHEN PB.TP_PROIBICAO = 'AG' THEN 'AGUARD.AUTORIZACAO'
     WHEN PB.TP_PROIBICAO = 'FC' THEN 'FORA_DA_CONTA'
     WHEN PB.TP_PROIBICAO = 'NA' THEN 'NAO_AUTORIZADO'
     WHEN PB.TP_PROIBICAO IS NULL THEN 'SEM_PROIBICAO'  
     END TP_PROIBICAO,
GP.CD_GRU_PRO 
  

                                            
FROM 
TAB_FAT TF 
INNER JOIN ITREGRA IRG ON IRG.CD_TAB_FAT = TF.CD_TAB_FAT
INNER JOIN REGRA RG ON RG.CD_REGRA = IRG.CD_REGRA
INNER JOIN VAL_PRO VP ON VP.CD_TAB_FAT = IRG.CD_TAB_FAT
INNER JOIN FILME_TAB FT ON FT.CD_TAB_FAT = VP.CD_TAB_FAT 
                        AND FT.CD_TAB_FAT = IRG.CD_TAB_FAT
                        AND FT.CD_PRO_FAT = VP.CD_PRO_FAT
INNER JOIN EMPRESA_CON_PLA ECPLA ON ECPLA.CD_REGRA = RG.CD_REGRA 
INNER JOIN PRO_FAT PF ON PF.CD_PRO_FAT = VP.CD_PRO_FAT 
                      AND PF.CD_GRU_PRO = IRG.CD_GRU_PRO
INNER JOIN GRU_PRO GP ON GP.CD_GRU_PRO = IRG.CD_GRU_PRO   
INNER JOIN VAL_INDICE VIND ON VIND.CD_INDICE = ECPLA.CD_INDICE
INNER JOIN INDICE_ACOMODACAO IACOM ON IACOM.CD_REGRA = RG.CD_REGRA 
                                   AND RG.CD_REGRA = IRG.CD_REGRA
INNER JOIN TIP_ACOM TACOM ON TACOM.CD_TIP_ACOM = IACOM.CD_TIP_ACOM                                   
LEFT JOIN PROIBICAO PB ON PB.CD_CONVENIO = ECPLA.CD_CONVENIO 
                        AND PB.CD_CON_PLA = ECPLA.CD_CON_PLA
                        AND PB.CD_MULTI_EMPRESA = ECPLA.CD_MULTI_EMPRESA
                        AND PB.CD_PRO_FAT = PF.CD_PRO_FAT
WHERE VP.DT_VIGENCIA = (SELECT MAX(X.DT_VIGENCIA) FROM VAL_PRO X WHERE X.CD_PRO_FAT = VP.CD_PRO_FAT  AND X.CD_TAB_FAT = VP.CD_TAB_FAT) 
AND FT.NR_INCIDENCIAS IS NOT NULL                               
AND TF.CD_TAB_FAT = 560
AND RG.CD_REGRA = 99
AND VP.CD_PRO_FAT = '40801012'--'40901769'
AND ECPLA.CD_CON_PLA = 1
AND IACOM.CD_TIP_ACOM = 1
AND PF.SN_ATIVO = 'S'
ORDER BY ECPLA.CD_CON_PLA;

select * from val_pro x where x.cd_pro_fat = '40801012' and x.cd_tab_fat = 560

select * from acresc_descontos where cd_regra = 99
select * from excecao_percentual_cobranca m where m.cd_regra = 99
-- internacoa valor x 200%
-- ambulatorio valor val_pro
-- extermo  valor x 200%
-- urgenccia valor x 200%
--
--- conta 
select * from 
