SELECT 
*
FROM
(
SELECT
C.CD_ATENDIMENTO,
G.NM_CONVENIO,
'INTERNADO'TIPO_CONTA,
B.CD_REG_FAT CONTA,
A.CD_PROTOCOLO_DOC,
F.NM_PACIENTE,
D.DT_INICIO,
D.DT_FINAL,
D.VL_TOTAL_CONTA,
--B.DT_REALIZACAO,
TRUNC(A.DT_ENVIO)DT_ENVIO,
A.NM_USUARIO_ENVIO,
TRUNC(B.DT_RECEBIMENTO)DT_RECEBIMENTO,
B.NM_USUARIO_RECEBIMENTO,
TRUNC(B.DT_DEVOLUCAO)DT_DEVOLUCAO,
B.NM_USUARIO_DEVOLUCAO,
A.CD_SETOR SETOR_ORIGEM,
E.NM_SETOR,
A.CD_SETOR_DESTINO,
(SELECT X.NM_SETOR FROM SETOR X WHERE X.CD_SETOR = A.CD_SETOR_DESTINO)NM_SETOR_DESTINO,
NVL(TRUNC(B.DT_RECEBIMENTO) - TRUNC(A.DT_ENVIO),0)QT_DIAS_RECEBIMENTO,
CASE WHEN B.DT_RECEBIMENTO IS NULL THEN (TRUNC(SYSDATE) - TRUNC(A.DT_ENVIO))ELSE 0 END DIAS_AG_RECEBIMENTO
FROM
PROTOCOLO_DOC A
INNER JOIN IT_PROTOCOLO_DOC B ON B.CD_PROTOCOLO_DOC = A.CD_PROTOCOLO_DOC
INNER JOIN ATENDIME C ON C.CD_ATENDIMENTO = B.CD_ATENDIMENTO
INNER JOIN REG_FAT D ON D.CD_ATENDIMENTO = B.CD_ATENDIMENTO AND D.CD_REG_FAT = B.CD_REG_FAT
INNER JOIN PACIENTE F ON F.CD_PACIENTE = C.CD_PACIENTE
INNER JOIN SETOR E ON E.CD_SETOR = A.CD_SETOR
INNER JOIN CONVENIO G ON G.CD_CONVENIO = C.CD_CONVENIO
WHERE B.CD_DOCUMENTO_PROT = 1
AND C.CD_MULTI_EMPRESA = 3
AND (A.CD_SETOR_DESTINO IN (941,940,3078,944,937,952) OR A.CD_SETOR IN (941,940,3078,944,937,952))
--AND TRUNC(A.DT_ENVIO) BETWEEN '01/05/2021' AND sysdate
union all
SELECT
DISTINCT
C.CD_ATENDIMENTO,
G.NM_CONVENIO,
'AMBULATORIAL'TIPO_CONTA,
B.CD_REG_AMB CONTA,
A.CD_PROTOCOLO_DOC,
F.NM_PACIENTE,
D2.DT_LANCAMENTO DT_INICIO,
D2.DT_LANCAMENTO DT_FINAL,
D2.VL_TOTAL_CONTA,
--B.DT_REALIZACAO,
TRUNC(A.DT_ENVIO)DT_ENVIO,
A.NM_USUARIO_ENVIO,
TRUNC(B.DT_RECEBIMENTO)DT_RECEBIMENTO,
B.NM_USUARIO_RECEBIMENTO,
TRUNC(B.DT_DEVOLUCAO)DT_DEVOLUCAO,
B.NM_USUARIO_DEVOLUCAO,
A.CD_SETOR SETOR_ORIGEM,
E.NM_SETOR,
A.CD_SETOR_DESTINO,
(SELECT X.NM_SETOR FROM SETOR X WHERE X.CD_SETOR = A.CD_SETOR_DESTINO)NM_SETOR_DESTINO,
NVL(TRUNC(B.DT_RECEBIMENTO) - TRUNC(A.DT_ENVIO),0)QT_DIAS_RECEBIMENTO,
CASE WHEN B.DT_RECEBIMENTO IS NULL THEN (TRUNC(SYSDATE) - TRUNC(A.DT_ENVIO))ELSE 0 END DIAS_AG_RECEBIMENTO
FROM
PROTOCOLO_DOC A
INNER JOIN IT_PROTOCOLO_DOC B ON B.CD_PROTOCOLO_DOC = A.CD_PROTOCOLO_DOC
INNER JOIN ATENDIME C ON C.CD_ATENDIMENTO = B.CD_ATENDIMENTO
INNER JOIN REG_AMB D2 ON D2.CD_REG_AMB = B.CD_REG_AMB
INNER JOIN ITREG_AMB D1 ON D1.CD_REG_AMB = D2.CD_REG_AMB AND D1.CD_ATENDIMENTO = C.CD_ATENDIMENTO
INNER JOIN PACIENTE F ON F.CD_PACIENTE = C.CD_PACIENTE
INNER JOIN SETOR E ON E.CD_SETOR = A.CD_SETOR
INNER JOIN CONVENIO G ON G.CD_CONVENIO = C.CD_CONVENIO
WHERE B.CD_DOCUMENTO_PROT = 1
AND C.CD_MULTI_EMPRESA = 3
AND (A.CD_SETOR_DESTINO IN (941,940,3078,944,937,952) OR A.CD_SETOR IN (941,940,3078,944,937,952))
--AND TRUNC(A.DT_ENVIO) BETWEEN '01/05/2021' AND sysdate
)X
WHERE X.DT_ENVIO BETWEEN '01/05/2021' AND sysdate
order by X.CD_ATENDIMENTO,
         X.CONTA,
         X.TIPO_CONTA
       
         

/*ORDER BY A.DT_ENVIO,
         C.CD_ATENDIMENTO,
         B.CD_REG_FAT*/
         
/*ORDER BY A.DT_ENVIO,
         C.CD_ATENDIMENTO,
         B.CD_REG_FAT*/
         

/*pre- auditoria -  auditoria interna enfermagem
auditoria interna enfermagem  - central autorizao pós 
central autorizao pós  - auditoria de contas medicas
auditoria de contas medicas  / faturamento fechamento
aturamento / faturamento fechamento */

-- 941 PRE AUDITORIA
-- 940 AUDITORIA INTERNA DE ENFERMAGE
-- 3078 CENTRAL DE AUTORIZACOES POS
-- 944  AUDITORIA DE CONTAS MEDICAS
-- 937  FATURAMENTO FECHAMENTO
-- 952  FATURAMENTO
