SELECT
CONV.CD_CONVENIO,
CPL.CD_CON_PLA,
ECONV.CD_MULTI_EMPRESA,
SPLA.CD_SUB_PLANO,
SPLA.DS_SUB_PLANO
FROM 
CONVENIO CONV 
INNER JOIN CON_PLA CPL ON CPL.CD_CONVENIO = CONV.CD_CONVENIO
INNER JOIN EMPRESA_CONVENIO ECONV ON ECONV.CD_CONVENIO = CONV.CD_CONVENIO
INNER JOIN SUB_PLANO SPLA ON SPLA.CD_CONVENIO = CONV.CD_CONVENIO AND SPLA.CD_CON_PLA = CPL.CD_CON_PLA
WHERE CONV.CD_CONVENIO = 63
ORDER BY SPLA.DS_SUB_PLANO
