SELECT 
PD.CD_PRODUTO,
PD.DS_PRODUTO,
PD.CD_ESPECIE||' - '||ESP.DS_ESPECIE ESPECIE,
PD.CD_PRO_FAT,
PF.DS_PRO_FAT,
PF.CD_GRU_PRO||' - '||GP.DS_GRU_PRO GRU_PRO,
EPD.CD_MULTI_EMPRESA,
PD.VL_ULTIMA_ENTRADA
FROM 
GRU_PRO GP 
INNER JOIN PRO_FAT PF ON PF.CD_GRU_PRO = GP.CD_GRU_PRO
INNER JOIN PRODUTO PD ON PD.CD_PRO_FAT = PF.CD_PRO_FAT
INNER JOIN EMPRESA_PRODUTO EPD ON EPD.CD_PRODUTO = PD.CD_PRODUTO
INNER JOIN ESPECIE ESP ON ESP.CD_ESPECIE = PD.CD_ESPECIE
WHERE GP.DS_GRU_PRO LIKE '%MEDICA%'
AND EPD.CD_MULTI_EMPRESA = 7
AND PD.SN_MOVIMENTACAO = 'S'
ORDER BY 1

