SELECT 
ATD.CD_MULTI_EMPRESA,
CASE WHEN ATD.TP_ATENDIMENTO = 'I' THEN 'INTERNADO' END TIPO_ATENDIMENTO,
RF.CD_ATENDIMENTO,
RF.CD_REG_FAT CONTA,
TO_CHAR(RF.DT_INICIO,'DD/MM/RRRR')||'  Á  '||TO_CHAR(RF.DT_FINAL,'DD/MM/RRRR') PERIODO_CONTA,
RF.CD_REMESSA,
ATD.DT_ATENDIMENTO,
ATD.DT_ALTA

FROM 
REG_FAT RF 
INNER JOIN  ATENDIME ATD ON ATD.CD_ATENDIMENTO = RF.CD_ATENDIMENTO
AND ATD.CD_CONVENIO = RF.CD_CONVENIO
WHERE ATD.DT_ATENDIMENTO BETWEEN '01/01/2021' AND '31/12/2022'  
AND ATD.CD_CONVENIO in (68,152,112,313,189) 
AND RF.TP_CLASSIFICACAO_CONTA NOT IN ('O')


UNION ALL 

SELECT 
DISTINCT
ATD1.CD_MULTI_EMPRESA,
CASE WHEN ATD1.TP_ATENDIMENTO = 'E' THEN 'EXTERNO'
     WHEN ATD1.TP_ATENDIMENTO = 'U' THEN 'URGENCIA' 
     WHEN ATD1.TP_ATENDIMENTO = 'A' THEN 'AMBULATORIO'
     END TIPO_ATENDIMENTO,
ATD1.CD_ATENDIMENTO,     
IRAMB.CD_REG_AMB CONTA,
TO_CHAR(RAMB.DT_LANCAMENTO,'DD/MM/RRRR')||'  Á  '||TO_CHAR(RAMB.DT_LANCAMENTO_FINAL,'DD/MM/RRRR') PERIODO_CONTA,
RAMB.CD_REMESSA,
ATD1.DT_ATENDIMENTO,
ATD1.DT_ALTA

FROM 
ITREG_AMB IRAMB 
INNER JOIN  ATENDIME ATD1 ON ATD1.CD_ATENDIMENTO = IRAMB.CD_ATENDIMENTO
AND IRAMB.CD_CONVENIO = ATD1.CD_CONVENIO
INNER JOIN REG_AMB RAMB ON RAMB.CD_REG_AMB = IRAMB.CD_REG_AMB 
AND RAMB.CD_CONVENIO = ATD1.CD_CONVENIO
WHERE ATD1.DT_ATENDIMENTO BETWEEN '01/01/2021' AND '31/12/2022'  
AND ATD1.CD_CONVENIO in (68,152,112,313,189) 
ORDER BY CD_MULTI_EMPRESA, 
         CD_ATENDIMENTO, 
         DT_ATENDIMENTO
