SELECT 
DISTINCT
A.DT_VIGENCIA DT_VIGENCIA_PACOTE,
a.cd_pro_fat_pacote||' - '||c.ds_pro_fat ds_pacote,
b.dt_vigencia DT_VIGENCIA_VALOR,
b.vl_total,
B.CD_TAB_FAT||' - '||TF.DS_TAB_FAT DS_TABELA_FATURAMENTO

FROM 
PACOTE A 
INNER JOIN VAL_PRO B ON B.CD_PRO_FAT = A.Cd_Pro_Fat_Pacote
INNER JOIN PRO_FAT C ON C.CD_PRO_FAT = B.CD_PRO_FAT
INNER JOIN EMPRESA_CONVENIO D ON D.CD_CONVENIO = A.CD_CONVENIO AND D.CD_MULTI_EMPRESA = A.CD_MULTI_EMPRESA
INNER JOIN CON_PLA E ON E.CD_CONVENIO = D.CD_CONVENIO 
INNER JOIN ITREGRA IR ON IR.CD_REGRA = E.CD_REGRA AND IR.CD_GRU_PRO = C.CD_GRU_PRO 
INNER JOIN TAB_FAT TF ON TF.CD_TAB_FAT = IR.CD_TAB_FAT 
AND IR.CD_TAB_FAT = B.CD_TAB_FAT
WHERE  A.CD_CONVENIO = 149
AND A.DT_VIGENCIA_FINAL IS NULL
ORDER By ds_pacote,b.dt_vigencia



