INSERT INTO  ITREG_REPASSE (CD_ITREG_REPASSE,
       CD_REG_REPASSE,
       CD_CONVENIO,
       CD_ORI_ATE,
       CD_GRU_PRO,
       CD_PRO_FAT,
       VL_PERCENT_PAGO,
       VL_PERCENT_DESC,
       VL_PROCEDIMENTO,
       VL_DESCONTO,
       CD_ATI_MED,
       CD_TIP_ACOM,
       SN_PERTENCE_PACOTE,
       SN_INSIDE_NO_FILME,
       CD_SETOR,
       SN_CH_FATURADO,
       QT_CH,
       TP_ATENDIMENTO,
       SN_HORARIO_CONTRATADO,
       CD_MULTI_EMPRESA,
       SN_UCO,
       DT_VIGENCIA,
       CD_GRU_FAT,
       CD_ESPECIALID,
       VL_INDICE,
       VL_PERC_HE,
       VL_PERC_FERIADO,
       TP_REPASSE_DIF)
       (SELECT seq_itreg_repasse.nextval ,
       385, --- regra que receberá a copia 
       CD_CONVENIO,
       CD_ORI_ATE,
       CD_GRU_PRO,
       CD_PRO_FAT,
       VL_PERCENT_PAGO,
       VL_PERCENT_DESC,
       VL_PROCEDIMENTO,
       VL_DESCONTO,
       CD_ATI_MED,
       CD_TIP_ACOM,
       SN_PERTENCE_PACOTE,
       SN_INSIDE_NO_FILME,
       CD_SETOR,
       SN_CH_FATURADO,
       QT_CH,
       TP_ATENDIMENTO,
       SN_HORARIO_CONTRATADO,
       CD_MULTI_EMPRESA,
       SN_UCO,
       DT_VIGENCIA,
       CD_GRU_FAT,
       CD_ESPECIALID,
       VL_INDICE,
       VL_PERC_HE,
       VL_PERC_FERIADO,
       TP_REPASSE_DIF
       FROM ITREG_REPASSE
       WHERE CD_REG_REPASSE =   ); -- regra que será espelho 
       COMMIT;
       
        


