SELECT 
decode (row_number()over (partition by A.CD_EXA_LAB order by H.CD_LABORATORIO,B.CD_TUBO_COLETA),1,'EXAME:', null) SEQ,
A.CD_EXA_LAB||' - '||A.NM_EXA_LAB NM_EXAME,
A.CD_PRO_FAT,
E.CD_SET_EXA||' - '||F.NM_SET_EXA SETOR_EXAME,
H.CD_LABORATORIO||' - '||I.DS_LABORATORIO LABORATORIO,
H.SN_PADRAO,
B.CD_TUBO_COLETA||' - '||C.DS_TUBO_COLETA TUBO_COLETA,
B.CD_MATERIAL||' - '||D.DS_MATERIAL MATERIAL,
A.SN_REALIZA_SEGUNDA SEGUNDA,
A.SN_REALIZA_TERCA TERCA,
A.SN_REALIZA_QUARTA QUARTA,
A.SN_REALIZA_QUINTA QUINTA,
A.SN_REALIZA_SEXTA SEXTA,
A.SN_REALIZA_SABADO SABADO,
A.SN_REALIZA_DOMINGO DOMINGO

FROM
EXA_LAB A 
INNER JOIN EXA_LAB_MATERIAL B ON B.CD_EXA_LAB = A.CD_EXA_LAB
LEFT JOIN TUBO_COLETA C ON C.CD_TUBO_COLETA = B.CD_TUBO_COLETA
LEFT JOIN MATERIAL D ON D.CD_MATERIAL = B.CD_MATERIAL
INNER JOIN EXA_LAB_SET_EXA E ON E.CD_EXA_LAB = A.CD_EXA_LAB
INNER JOIN SET_EXA F ON F.CD_SET_EXA = E.CD_SET_EXA
INNER JOIN SETOR G ON  G.CD_SETOR = F.CD_SETOR
INNER JOIN EXA_LAB_LABORATORIO H ON H.CD_EXA_LAB = A.CD_EXA_LAB
INNER JOIN LABORATORIO I ON I.CD_LABORATORIO = H.CD_LABORATORIO
WHERE A.CD_EXA_LAB = 1
AND G.CD_MULTI_EMPRESA = 7
AND A.SN_ATIVO = 'S'

--SELECT * FROM EXA_LAB
