----- PRODUTOS LIBERADOS EMPRESA X TUSS 
SELECT 
PD.CD_PRODUTO,
PD.DS_PRODUTO,
LP.CD_REGISTRO ANVISA,
SUBSTR(PD.DS_PRODUTO,instr(PD.DS_PRODUTO,'REF')+4,50)REFENCIA,
PD.CD_ESPECIE||' - '||ESP.DS_ESPECIE ESPECIE,
PD.CD_PRO_FAT,
PF.CD_GRU_PRO||' - '||GP.DS_GRU_PRO GRU_PROCED,
TS.CD_TIP_TUSS,
TS.CD_TUSS,
TS.DS_TUSS,
TS.CD_MULTI_EMPRESA,
TS.CD_CONVENIO||' - '||CONV.NM_CONVENIO CONV
--COUNT(*)
FROM 
PRODUTO PD 
INNER JOIN EMPRESA_PRODUTO EPD ON EPD.CD_PRODUTO = PD.CD_PRODUTO 
INNER JOIN TUSS TS ON TS.CD_PRO_FAT = PD.CD_PRO_FAT
INNER JOIN PRO_FAT PF ON PF.CD_PRO_FAT = TS.CD_PRO_FAT
INNER JOIN ESPECIE ESP ON ESP.CD_ESPECIE = PD.CD_ESPECIE
INNER JOIN GRU_PRO GP ON GP.CD_GRU_PRO = PF.CD_GRU_PRO
LEFT JOIN CONVENIO CONV ON CONV.CD_CONVENIO = TS.CD_CONVENIO
LEFT JOIN LAB_PRO LP ON LP.CD_PRODUTO = PD.CD_PRODUTO
WHERE PD.SN_MOVIMENTACAO = 'S'
--PD.CD_PRODUTO = 21633
AND TS.CD_TIP_TUSS IN (22,00,19)
AND EPD.CD_MULTI_EMPRESA = 10 --- PRODUTOS CASA 
AND TS.CD_MULTI_EMPRESA = 10 --- TUSS CASA 
ORDER BY PD.CD_PRODUTO
--AND PD.SN_MOVIMENTACAO = 'S'
;

WITH PROD AS 
(SELECT 
PD.CD_PRODUTO,
PD.DS_PRODUTO,
LP.CD_REGISTRO ANVISA,
SUBSTR(PD.DS_PRODUTO,instr(PD.DS_PRODUTO,'REF')+4,50)REFENCIA,
PD.CD_ESPECIE||' - '||ESP.DS_ESPECIE ESPECIE,
PD.CD_PRO_FAT,
PF.CD_GRU_PRO||' - '||GP.DS_GRU_PRO GRU_PROCED,
TS.CD_TIP_TUSS,
TS.CD_TUSS,
TS.DS_TUSS,
TS.CD_MULTI_EMPRESA,
TS.CD_CONVENIO||' - '||CONV.NM_CONVENIO CONV
--COUNT(*)
FROM 
PRODUTO PD 
INNER JOIN EMPRESA_PRODUTO EPD ON EPD.CD_PRODUTO = PD.CD_PRODUTO 
INNER JOIN TUSS TS ON TS.CD_PRO_FAT = PD.CD_PRO_FAT
INNER JOIN PRO_FAT PF ON PF.CD_PRO_FAT = TS.CD_PRO_FAT
INNER JOIN ESPECIE ESP ON ESP.CD_ESPECIE = PD.CD_ESPECIE
INNER JOIN GRU_PRO GP ON GP.CD_GRU_PRO = PF.CD_GRU_PRO
LEFT JOIN CONVENIO CONV ON CONV.CD_CONVENIO = TS.CD_CONVENIO
LEFT JOIN LAB_PRO LP ON LP.CD_PRODUTO = PD.CD_PRODUTO
WHERE PD.SN_MOVIMENTACAO = 'S'
--PD.CD_PRODUTO = 21633
AND TS.CD_TIP_TUSS IN (22,00,19)
AND EPD.CD_MULTI_EMPRESA = 10 --- PRODUTOS CASA 
AND TS.CD_MULTI_EMPRESA = 10 --- TUSS CASA 
ORDER BY PD.CD_PRODUTO
--AND PD.SN_MOVIMENTACAO = 'S'
)


SELECT 
IRG.CD_PRO_FAT,
PFX.DS_PRO_FAT,
PX.ESPECIE,
COUNT(*)TOTAL
FROM 
ATENDIME ATD 
INNER JOIN REG_FAT RF ON RF.CD_ATENDIMENTO = ATD.CD_ATENDIMENTO AND RF.CD_CONVENIO = ATD.CD_CONVENIO
INNER JOIN ITREG_fAT IRG ON IRG.CD_REG_FAT = RF.CD_REG_FAT
INNER JOIN PRO_FAT PFX ON PFX.CD_PRO_FAT = IRG.CD_PRO_FAT
INNER JOIN PROD PX ON PX.CD_PRO_FAT = IRG.CD_PRO_FAT AND RF.CD_MULTI_EMPRESA = PX.CD_MULTI_EMPRESA
WHERE TO_CHAR(IRG.DT_LANCAMENTO,'MM/RRRR') BETWEEN '01/2022' AND '05/2023'
AND ATD.CD_MULTI_EMPRESA = 10 
GROUP BY 
IRG.CD_PRO_FAT,
PFX.DS_PRO_FAT,
PX.ESPECIE
ORDER BY TOTAL DESC 
