SELECT 
ATD.CD_MULTI_EMPRESA,
DP.CD_ATENDIMENTO,
RF.CD_REG_FAT,
TO_CHAR(RF.DT_INICIO,'DD/MM/RRRR')||'  Á  '||TO_CHAR(RF.DT_FINAL,'DD/MM/RRRR') PERIODO_CONTA,
RF.CD_REMESSA,
ATD.DT_ATENDIMENTO,
DP.NR_PASTA
FROM 
DOCUMENTO_PASTA_PARCIAL DP
LEFT JOIN REG_FAT RF ON RF.CD_REG_FAT = DP.CD_REG_FAT
LEFT JOIN ATENDIME ATD ON ATD.CD_ATENDIMENTO = DP.CD_ATENDIMENTO
AND ATD.CD_CONVENIO = RF.CD_CONVENIO
WHERE ATD.DT_ATENDIMENTO BETWEEN '01/01/2020' AND '31/12/2022'  
--AND RF.CD_REG_FAT = 378502
--AND DP.CD_ATENDIMENTO = 3404463
AND ATD.CD_CONVENIO in (68,152,112,313,189) 
AND RF.TP_CLASSIFICACAO_CONTA NOT IN ('O')
--and atd.cd_atendimento = 2374623
ORDER BY ATD.CD_MULTI_EMPRESA,DP.CD_ATENDIMENTO, DP.NR_PASTA


--SELECT * FROM DOCUMENTO_PASTA_PARCIAL DP WHERE DP.CD_ATENDIMENTO = 3404463
--SELECT * FROM 
--SELECT * FROM REG_FAT WHERE CD_ATENDIMENTO = 3404463
