SELECT TO_CHAR(TO_DATE('01/01/' || TO_CHAR(SYSDATE, 'YYYY'), 'DD/MM/YYYY') + LEVEL - 1, 'DD/MM/YYYY') AS DATA_ANO_ATUAL
FROM dual
CONNECT BY LEVEL <= 365 + DECODE(TO_CHAR(ADD_MONTHS(SYSDATE, 12), 'YYYY'), TO_CHAR(SYSDATE, 'YYYY'), 0, 1);
