SELECT
DECODE(EMP.CD_MULTI_EMPRESA,'3','CSSJ','4','HST','7','HSC','10','HSJ','11','HMRP','25','HCNSC')EMPRESA,
PF.CD_GRU_PRO,
GP.DS_GRU_PRO ,
PF.CD_PRO_FAT,
PF.DS_PRO_FAT,
PF.DS_UNIDADE,
PD.CD_PRODUTO,
PD.DS_PRODUTO,
PD.CD_ESPECIE,
ESP.DS_ESPECIE,
PD.CD_CLASSE,
CL.DS_CLASSE,
LT.NM_LABORATOR MARCA_LABORAT,
LB.CD_REGISTRO ANVISA


FROM
GRU_PRO GP
INNER JOIN PRO_FAT PF ON PF.CD_GRU_PRO = GP.CD_GRU_PRO
INNER JOIN PRODUTO PD ON PD.CD_PRO_FAT = PF.CD_PRO_FAT
INNER JOIN EMPRESA_PRODUTO EMP ON EMP.CD_PRODUTO = PD.CD_PRODUTO
LEFT  JOIN LAB_PRO LB ON LB.CD_PRODUTO = PD.CD_PRODUTO
INNER JOIN ESPECIE ESP ON ESP.CD_ESPECIE = PD.CD_ESPECIE
INNER JOIN CLASSE CL ON CL.CD_ESPECIE = PD.CD_ESPECIE AND CL.CD_CLASSE = PD.CD_CLASSE
LEFT JOIN LABORATOR LT ON LT.CD_LABORATOR = LB.CD_LABORATOR
WHERE GP.CD_GRU_PRO IN (07, 08, 09, 12, 15, 43, 44, 89, 92, 94, 95 , 96)
--PD.CD_ESPECIE in (60,17,18,61,19,20)/*GP.CD_GRU_PRO IN (8,89,95,96,71,7,12,92,15,43,44,94)*/
AND EMP.CD_MULTI_EMPRESA = 25
AND PF.SN_ATIVO = 'S'
AND PD.SN_MOVIMENTACAO = 'S'
--AND PD.CD_PRODUTO = 226
ORDER BY PD.CD_PRODUTO
