SELECT
ECPLA.CD_CONVENIO||' - '||CONV.NM_CONVENIO CONVENIO,
ECPLA.CD_CON_PLA||' - '||CPLA.DS_CON_PLA NM_PLANO,
A.CD_PRO_FAT,
C.CD_TAB_FAT,
C.DS_TAB_FAT,
A.DT_VIGENCIA,
A.VL_HONORARIO,
A.VL_OPERACIONAL,
A.VL_TOTAL,
IR.CD_REGRA,
IR.VL_PERCETUAL_PAGO,
((A.VL_TOTAL * IR.VL_PERCETUAL_PAGO)/100)VL_EM_CONTA
FROM
VAL_PRO A
INNER JOIN PRO_FAT B ON B.CD_PRO_FAT = A.CD_PRO_FAT
INNER JOIN TAB_FAT C ON C.CD_TAB_FAT = A.CD_TAB_FAT
INNER JOIN GRU_PRO D ON D.CD_GRU_PRO = B.CD_GRU_PRO
LEFT JOIN VAL_PORTE E ON E.CD_POR_ANE = B.CD_POR_ANE AND E.CD_TAB_FAT = A.CD_TAB_FAT
LEFT JOIN ITREGRA IR ON IR.CD_TAB_FAT = A.CD_TAB_FAT AND B.CD_GRU_PRO = IR.CD_GRU_PRO
LEFT JOIN EMPRESA_CON_PLA ECPLA ON ECPLA.CD_REGRA = IR.CD_REGRA 
LEFT JOIN CONVENIO CONV ON CONV.CD_CONVENIO = ECPLA.CD_CONVENIO 
LEFT JOIN CON_PLA CPLA ON CPLA.CD_CON_PLA = ECPLA.CD_CON_PLA AND CPLA.CD_CONVENIO = CONV.CD_CONVENIO
WHERE A.DT_VIGENCIA = (SELECT MAX(X.DT_VIGENCIA) FROM VAL_PRO X WHERE X.CD_TAB_FAT = A.CD_TAB_FAT AND X.CD_PRO_FAT = A.CD_PRO_FAT)
AND C.DS_TAB_FAT LIKE '%HSC%'
--AND A.CD_TAB_FAT IN (2967)
and A.CD_PRO_FAT IN ('00277451'
,'00299109'
,'00314824'
,'02040923'
,'00325336'
,'00332721')
AND B.SN_ATIVO = 'S'
ORDER BY 1,2,3


--, convenio , regra , percentual, 
