SELECT 
       DISTINCT
       P.CD_PACIENTE,
       P.NM_PACIENTE,
       TRUNC(P.DT_NASCIMENTO)DT_NASCIMENTO,
       TRUNC(MONTHS_BETWEEN(SYSDATE,P.DT_NASCIMENTO) / 12) AS IDADE
       
FROM ATENDIME A
INNER JOIN PACIENTE P ON P.CD_PACIENTE = A.CD_PACIENTE
LEFT OUTER JOIN AVISO_CIRURGIA AC ON AC.CD_ATENDIMENTO = A.CD_ATENDIMENTO
WHERE A.TP_ATENDIMENTO = 'I'
AND AC.DT_FIM_CIRURGIA IS NULL
AND A.CD_TIPO_INTERNACAO IN(1,2,3)  -- 1-CIRURGICA  / 2-CLINICA  / 3-OBSTETRICA
AND A.CD_CID NOT IN ('Y199','X64','F41') --CIDS REFERENTES A ATENDIMENTOS PSIQUIÁTRICOS 
AND A.DT_ALTA  BETWEEN TO_DATE('01/01/2022', 'DD/MM/RRRR')  AND TO_DATE('31/12/2022', 'DD/MM/RRRR')
AND TRUNC(MONTHS_BETWEEN(SYSDATE,P.DT_NASCIMENTO)) >= 15 AND TRUNC(MONTHS_BETWEEN(SYSDATE,P.DT_NASCIMENTO) / 12) <15 
ORDER BY TRUNC(MONTHS_BETWEEN(SYSDATE,P.DT_NASCIMENTO) / 12)

--select TRUNC(MONTHS_BETWEEN(SYSDATE, '18/04/2021') / 12) AS IDADE from dual 
