SELECT
DECODE(c.tp_tab_fat,'R','REAL','C','CH')TIPO_REFERENCIA,
C.CD_TAB_FAT,
C.DS_TAB_FAT,
A.CD_PRO_FAT,
A.DT_VIGENCIA,
A.VL_HONORARIO,
A.VL_OPERACIONAL,
A.VL_TOTAL
--E.VL_PORTE
FROM
VAL_PRO A
INNER JOIN PRO_FAT B ON B.CD_PRO_FAT = A.CD_PRO_FAT
INNER JOIN TAB_FAT C ON C.CD_TAB_FAT = A.CD_TAB_FAT
INNER JOIN GRU_PRO D ON D.CD_GRU_PRO = B.CD_GRU_PRO
LEFT JOIN VAL_PORTE E ON E.CD_POR_ANE = B.CD_POR_ANE AND E.CD_TAB_FAT = A.CD_TAB_FAT
WHERE A.DT_VIGENCIA = (SELECT MAX(X.DT_VIGENCIA) FROM VAL_PRO X WHERE X.CD_PRO_FAT = A.CD_PRO_FAT
                                                                AND X.CD_TAB_FAT = A.CD_TAB_FAT)
AND A.CD_PRO_FAT IN ('20202040')
and c.ds_tab_fat like 'HST%'
ORDER BY C.CD_TAB_FAT
