SELECT 
*
FROM
(
SELECT DISTINCT
A.CD_ATENDIMENTO,
A.DT_ATENDIMENTO,
A.CD_CONVENIO||' - '||B.NM_CONVENIO CONVENIO,
A.CD_CON_PLA||' - '||D.DS_CON_PLA PLANO,
DECODE(A.TP_ATENDIMENTO,'A','AMBULATORIO','E','EXTERNO','U','URGENCIA')TIPO_ATEND,
G.CD_REG_AMB CONTA,
G.VL_TOTAL_CONTA
FROM
ATENDIME A
INNER JOIN CONVENIO B ON B.CD_CONVENIO = A.CD_CONVENIO
INNER JOIN EMPRESA_CONVENIO C ON C.CD_CONVENIO = B.CD_CONVENIO AND C.CD_MULTI_EMPRESA = A.CD_MULTI_EMPRESA
INNER JOIN CON_PLA D ON D.CD_CON_PLA = A.CD_CON_PLA
INNER JOIN EMPRESA_CON_PLA E ON D.CD_CONVENIO = C.CD_CONVENIO AND E.CD_CON_PLA = D.CD_CON_PLA AND A.CD_MULTI_EMPRESA = E.CD_MULTI_EMPRESA
INNER JOIN ITREG_AMB F ON F.CD_ATENDIMENTO = A.CD_ATENDIMENTO
INNER JOIN REG_AMB G ON G.CD_REG_AMB = F.CD_REG_AMB
WHERE A.CD_MULTI_EMPRESA = 3
AND B.TP_CONVENIO = 'P'
--AND A.CD_ATENDIMENTO = 4481081
AND A.TP_ATENDIMENTO IN ('A','E','U')
AND A.DT_ATENDIMENTO BETWEEN '01/09/2022' AND '20/12/2022'
AND F.SN_PERTENCE_PACOTE = 'N'

UNION ALL

SELECT
DISTINCT
A1.CD_ATENDIMENTO,
A1.DT_ATENDIMENTO,
A1.CD_CONVENIO||' - '||B1.NM_CONVENIO CONVENIO,
A1.CD_CON_PLA||' - '||D1.DS_CON_PLA PLANO,
DECODE(A1.TP_ATENDIMENTO,'I','INTERNADO')TIPO_ATEND,
G1.CD_REG_FAT CONTA,
G1.VL_TOTAL_CONTA
FROM
ATENDIME A1
INNER JOIN CONVENIO B1 ON B1.CD_CONVENIO = A1.CD_CONVENIO
INNER JOIN EMPRESA_CONVENIO C1 ON C1.CD_CONVENIO = B1.CD_CONVENIO AND C1.CD_MULTI_EMPRESA = A1.CD_MULTI_EMPRESA
INNER JOIN CON_PLA D1 ON D1.CD_CON_PLA = A1.CD_CON_PLA
INNER JOIN EMPRESA_CON_PLA E1 ON D1.CD_CONVENIO = C1.CD_CONVENIO AND E1.CD_CON_PLA = D1.CD_CON_PLA AND A1.CD_MULTI_EMPRESA = E1.CD_MULTI_EMPRESA
INNER JOIN REG_FAT G1 ON G1.CD_ATENDIMENTO = A1.CD_ATENDIMENTO AND G1.CD_CONVENIO = A1.CD_CONVENIO
WHERE A1.CD_MULTI_EMPRESA = 3
AND B1.TP_CONVENIO = 'P'
AND A1.TP_ATENDIMENTO IN ('I')
AND A1.DT_ATENDIMENTO BETWEEN '01/09/2022' AND '20/12/2022'
ORDER BY DT_ATENDIMENTO
) WHERE CD_ATENDIMENTO = 4486746
-----------
------analitico
;

SELECT 
*
FROM
(
SELECT 
ATEND.CD_ATENDIMENTO,
ATEND.DT_ATENDIMENTO,
CONV.CD_CONVENIO||' - '||CONV.NM_CONVENIO CONVENIO,
ATEND.CD_CON_PLA||' - '||CPLA.DS_CON_PLA PLANO,
DECODE(ATEND.TP_ATENDIMENTO,'A','AMBULATORIO','E','EXTERNO','U','URGENCIA')TIPO_ATEND,
IRAMB.CD_REG_AMB CONTA,
IRAMB.CD_PRO_FAT||' - '||PF.DS_PRO_FAT DS_PROCEDIMENTO,
IRAMB.QT_LANCAMENTO,
IRAMB.VL_TOTAL_CONTA

FROM 
ITREG_AMB IRAMB
INNER JOIN REG_AMB  RAMB ON RAMB.CD_REG_AMB = IRAMB.CD_REG_AMB
INNER JOIN ATENDIME ATEND ON ATEND.CD_ATENDIMENTO = IRAMB.CD_ATENDIMENTO
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = IRAMB.CD_CONVENIO AND IRAMB.CD_CONVENIO = ATEND.CD_CONVENIO
INNER JOIN CON_PLA CPLA ON CPLA.CD_CON_PLA = IRAMB.CD_CON_PLA AND CPLA.CD_CONVENIO = ATEND.CD_CON_PLA
INNER JOIN PRO_FAT PF ON PF.CD_PRO_FAT = IRAMB.CD_PRO_FAT
WHERE ATEND.DT_ATENDIMENTO BETWEEN '01/12/2022' AND '20/12/2022'
--AND IRAMB.CD_ATENDIMENTO = 4458137
AND IRAMB.SN_PERTENCE_PACOTE = 'N'
AND ATEND.CD_MULTI_EMPRESA = 3
AND CONV.TP_CONVENIO = 'P'


UNION ALL 

SELECT 
G3.CD_ATENDIMENTO,
G3.DT_ATENDIMENTO,
G3.CD_CONVENIO||' - '||G5.NM_CONVENIO CONVENIO,
G3.CD_CON_PLA||' - '||G6.DS_CON_PLA PLANO,
DECODE(G3.TP_ATENDIMENTO,'I','INTERNADO')TIPO_ATEND,
G2.CD_REG_FAT CONTA,
G2.CD_PRO_FAT||' - '||G4.DS_PRO_FAT DS_PROCEDIMENTO,
G2.QT_LANCAMENTO,
G2.VL_TOTAL_CONTA
FROM 
REG_FAT G1 
INNER JOIN ITREG_FAT G2 ON G2.CD_REG_FAT = G1.CD_REG_FAT
INNER JOIN ATENDIME G3 ON G3.CD_ATENDIMENTO = G1.CD_ATENDIMENTO
INNER JOIN PRO_FAT G4 ON G4.CD_PRO_FAT = G2.CD_PRO_FAT
INNER JOIN CONVENIO G5 ON G5.CD_CONVENIO = G1.CD_CONVENIO AND G5.CD_CONVENIO = G3.CD_CONVENIO
INNER JOIN CON_PLA G6 ON G6.CD_CON_PLA = G1.CD_CON_PLA AND G6.CD_CONVENIO = G1.CD_CONVENIO
WHERE  G3.DT_ATENDIMENTO BETWEEN '01/12/2022' AND '20/12/2022'
AND G2.SN_PERTENCE_PACOTE = 'N'
AND G5.TP_CONVENIO = 'P'
AND G3.CD_MULTI_EMPRESA = 3
AND G3.TP_ATENDIMENTO IN ('I')
ORDER BY DT_ATENDIMENTO
) WHERE CD_ATENDIMENTO = 4486746
