 ------ AGENDAMENTO PARA HSC QUANDO FOR OS SEGUINTES PROFATS (10101012,10106146) PARA OS COVENIOS (QSAUDE,PREVENT,CET,CENTRAL NACIONAL UNIMED,AMIL,NOTRE DAME)
  -- C2305/8067 16/05/2023
  SELECT
                E.CD_MULTI_EMPRESA CD_MULTI_EMPRESA,
                (TO_CHAR(F.CD_MOVIMENTO_AGENDA_CENTRAL)||'.'||'1'||'-'||TO_CHAR(A.HR_AGENDA,'ddmm')) ID,
                A.CD_CONVENIO,
                G.NR_REGISTRO_OPERADORA_ANS,
                F.NM_PACIENTE,
                (SELECT DS_RESPOSTA FROM PER_PEDRX WHERE CD_IT_AGENDA_CENTRAL = A.CD_IT_AGENDA_CENTRAL AND CD_PERGUNTA = 102 AND ROWNUM = 1) NR_CARTEIRA,
                (SELECT DS_RESPOSTA FROM PER_PEDRX WHERE CD_IT_AGENDA_CENTRAL = A.CD_IT_AGENDA_CENTRAL AND CD_PERGUNTA = 100 AND ROWNUM = 1) NM_PRESTADOR,
                (SELECT DS_RESPOSTA FROM PER_PEDRX WHERE CD_IT_AGENDA_CENTRAL = A.CD_IT_AGENDA_CENTRAL AND CD_PERGUNTA = 101 AND ROWNUM = 1) DS_CODIGO_CONSELHO,
                CASE E.CD_MULTI_EMPRESA WHEN '7' THEN 'SP' ELSE 'RJ' END UF_CONSELHO,
                '225125' CD_CBOS,
                TO_DATE(A.HR_AGENDA,'dd/mm/rrrr') DH_SOLICITADO,
                (B.DS_ITEM_AGENDAMENTO || ' - ' || (SELECT DS_RESPOSTA FROM PER_PEDRX WHERE CD_IT_AGENDA_CENTRAL = A.CD_IT_AGENDA_CENTRAL AND CD_PERGUNTA = 117 AND ROWNUM = 1)) DS_INDICACAO,
                'Eletiva' DS_CARATER ,
                'Externo' CD_TIPO_INTERNACAO ,
                NULL CD_CID,
                B.CD_PRO_FAT CD_PROCEDIMENTO,
                H.DS_PRO_FAT DS_PROCEDIMENTO,
                'Não' UTI,
                1 QT_SOLICITADA,
                'Externo' TP_REGIME_INTERNACAO,
                TO_DATE(A.HR_AGENDA,'dd/mm/rrrr') DT_SUGERIDA_INTERNACAO,
                'N' SN_PREVISAO_USO_OPME,
                NULL CD_DOCUMENTO_CLINICO,
                A.CD_ATENDIMENTO,
                NULL DIARIA,
                NULL QT_DIARIAS_SOLICITADA,
                'externo' TP_ATENDIMENTO
  FROM IT_AGENDA_CENTRAL A,
       ITEM_AGENDAMENTO  B,
     --  EXA_RX            C,
     --  MODALIDADE_EXAME  D,
       AGENDA_CENTRAL    E,
      MOVIMENTO_AGENDA_CENTRAL F,
       CONVENIO          G,
       PRO_FAT           H,
       IT_MOVIMENTO_AGENDA_CENTRAL I
    --   PRESTADOR P
 WHERE A.CD_CONVENIO IN (501,464,14,13,5,34) --QSAUDE,PREVENT,CET,CENTRAL NACIONAL UNIMED,AMIL,NOTRE DAME
   AND A.CD_ITEM_AGENDAMENTO = B.CD_ITEM_AGENDAMENTO
   AND F.CD_MOVIMENTO_AGENDA_CENTRAL = I.CD_MOVIMENTO_AGENDA_CENTRAL
   AND I.CD_IT_AGENDA_CENTRAL = A.CD_IT_AGENDA_CENTRAL
   AND A.CD_CONVENIO = G.CD_CONVENIO
   AND B.CD_PRO_FAT = H.CD_PRO_FAT
   AND E.CD_AGENDA_CENTRAL = A.CD_AGENDA_CENTRAL
  -- AND I.CD_PRESTADOR = P.CD_PRESTADOR
  AND TO_DATE(A.HR_AGENDA,'DD/MM/RRRR') BETWEEN TO_DATE(SYSDATE,'DD/MM/RRRR') AND TO_DATE(SYSDATE,'DD/MM/RRRR')+10
  --AND A.CD_PACIENTE IN (2907882)
   AND   B.CD_PRO_FAT IN (SELECT CD_PRO_FAT FROM PROIBICAO WHERE TP_PROIBICAO = 'AG'
         AND TP_ATENDIMENTO IN ('T','E','A') AND DT_FIM_PROIBICAO IS NULL AND CD_CONVENIO = A.CD_CONVENIO)
   AND I.TP_STATUS IN (SELECT MAX(MAC.TP_STATUS) FROM IT_MOVIMENTO_AGENDA_CENTRAL MAC WHERE  MAC.CD_MOVIMENTO_AGENDA_CENTRAL = I.CD_MOVIMENTO_AGENDA_CENTRAL
    AND MAC.CD_IT_AGENDA_CENTRAL = I.CD_IT_AGENDA_CENTRAL AND MAC.TP_STATUS = I.TP_STATUS AND  I.TP_STATUS = 'A')
   AND F.CD_USUARIO_MOVIMENTACAO <> 'INTEGRADOR.AGENDA'
   AND E.CD_MULTI_EMPRESA = 7
   AND B.CD_PRO_FAT IN (10101012,10106146)
