SELECT 
*
FROM
(
SELECT 
DISTINCT
DECODE(ATD.TP_ATENDIMENTO,'A','AMBULATORIO','E','EXTERNO','U','URGENCIA')TP_CONTA,
ATD.DT_ATENDIMENTO,
ATD.CD_ATENDIMENTO,
IRAMB.CD_REG_AMB CONTA,
CASE WHEN IRAMB.SN_FECHADA = 'S' THEN 'SIM' ELSE 'NAO' END CONTA_FECHADA,
RAMB.VL_TOTAL_CONTA,
DECODE(ICR.TP_QUITACAO,'C','COMPROMETIDO','Q','QUITADO',NULL)TP_QUITACAO,
CR.CD_CON_REC

FROM 
ATENDIME ATD
INNER JOIN ITREG_AMB IRAMB ON IRAMB.CD_ATENDIMENTO = ATD.CD_ATENDIMENTO
INNER JOIN REG_AMB RAMB ON RAMB.CD_REG_AMB = IRAMB.CD_REG_AMB
LEFT JOIN CON_REC CR ON CR.CD_REG_AMB = RAMB.CD_REG_AMB
LEFT JOIN ITCON_REC ICR ON ICR.CD_CON_REC = CR.CD_CON_REC
LEFT JOIN NOTA_FISCAL NF ON NF.CD_ATENDIMENTO = ATD.CD_ATENDIMENTO
WHERE NF.CD_NOTA_FISCAL IS NULL 
AND IRAMB.SN_PERTENCE_PACOTE = 'N'
AND ATD.CD_CONVENIO IN (307,309)
AND RAMB.VL_TOTAL_CONTA <> '0,00'

UNION ALL

SELECT 
DECODE(ATD1.TP_ATENDIMENTO,'I','INTERNADO')TP_CONTA,
ATD1.DT_ATENDIMENTO,
ATD1.CD_ATENDIMENTO,
RF.CD_REG_FAT CONTA,
CASE WHEN RF.SN_FECHADA = 'S' THEN 'SIM' ELSE 'NAO' END CONTA_FECHADA,
RF.VL_TOTAL_CONTA,
DECODE(ICRR.TP_QUITACAO,'C','COMPROMETIDO','Q','QUITADO',NULL)TP_QUITACAO,
CRR.CD_CON_REC

FROM 
ATENDIME ATD1
INNER JOIN REG_FAT RF ON RF.CD_ATENDIMENTO = ATD1.CD_ATENDIMENTO
LEFT JOIN CON_REC CRR ON CRR.CD_REG_FAT = RF.CD_REG_FAT AND CRR.CD_ATENDIMENTO = ATD1.CD_ATENDIMENTO
LEFT JOIN ITCON_REC ICRR ON ICRR.CD_CON_REC = CRR.CD_CON_REC
LEFT JOIN NOTA_FISCAL NFF ON NFF.CD_ATENDIMENTO = ATD1.CD_ATENDIMENTO
WHERE NFF.CD_NOTA_FISCAL IS NULL 
AND ATD1.CD_CONVENIO IN (307,309)
)
ORDER BY DT_ATENDIMENTO



