SELECT 
'CABEÇALHO---->',
SP.CD_SOLSAI_PRO,
SP.CD_PRE_MED,
SP.TP_SOLSAI_PRO TIPO_SOLICITACAO,
--SP.TP_SITUACAO,
DECODE(SP.TP_SITUACAO,'A','Cancelado','S','Confirmado','P','Pedido') TIPO_SITUACAO,
ATD.CD_ATENDIMENTO,
SP.HR_SOLSAI_PRO,
'ITENS SOLIICITACAO---->',
SP.TP_ORIGEM_SOLICITACAO ORIGEM_SOLICITACAO,
ISP.CD_PRODUTO,
PRD.DS_PRODUTO,
MVT.CD_MVTO_ESTOQUE,
MVT.HR_MVTO_ESTOQUE,
ISP.QT_SOLICITADO,
ISP.QT_ATENDIDA,
'LANC EM CONTA---->',
IRF.CD_PRO_FAT,
IRF.QT_LANCAMENTO,
IRF.VL_UNITARIO,
IRF.VL_TOTAL_CONTA

FROM
ATENDIME ATD
INNER JOIN SOLSAI_PRO SP ON SP.CD_ATENDIMENTO = ATD.CD_ATENDIMENTO
INNER JOIN ITSOLSAI_PRO ISP ON ISP.CD_SOLSAI_PRO = SP.CD_SOLSAI_PRO
LEFT JOIN MVTO_ESTOQUE MVT ON MVT.CD_ATENDIMENTO = ATD.CD_ATENDIMENTO AND MVT.CD_SOLSAI_PRO = SP.CD_SOLSAI_PRO
LEFT JOIN ITMVTO_ESTOQUE IMVT ON IMVT.CD_MVTO_ESTOQUE = MVT.CD_MVTO_ESTOQUE AND ISP.CD_PRODUTO = IMVT.CD_PRODUTO
LEFT JOIN PRODUTO PRD ON PRD.CD_PRODUTO = ISP.CD_PRODUTO
LEFT JOIN REG_FAT RF ON RF.CD_ATENDIMENTO = ATD.CD_ATENDIMENTO
LEFT JOIN ITREG_FAT IRF ON IRF.CD_REG_FAT = RF.CD_REG_FAT AND IRF.CD_MVTO = MVT.CD_MVTO_ESTOQUE
WHERE ATD.CD_ATENDIMENTO = 4027106
ORDER BY SP.HR_SOLSAI_PRO,SP.CD_SOLSAI_PRO 

--AND SP.CD_SOLSAI_PRO IN (20337196)--(20343277/*,20337196*/)


--SELECT * FROM MVTO_ESTOQUE A WHERE A.CD_ATENDIMENTO = 4027106 AND A.CD_MVTO_ESTOQUE = 28938524

--SELECT * FROM ITMVTO_ESTOQUE B WHERE B.CD_MVTO_ESTOQUE = 28938524


select * from 
