SELECT
ECPLA.CD_CONVENIO||' - '||CONV.NM_CONVENIO CONVENIO,
ECPLA.CD_CON_PLA||' - '||CPLA.DS_CON_PLA NM_PLANO,
A.CD_PRO_FAT||' - '||B.DS_PRO_FAT PROCEDIMENTO,
C.CD_TAB_FAT,
C.DS_TAB_FAT,
TRUNC(A.DT_VIGENCIA)DT_VIGENCIA,
--A.VL_HONORARIO,
--A.VL_OPERACIONAL,
A.VL_TOTAL,
IR.CD_REGRA,
IR.VL_PERCETUAL_PAGO PERC_REGRA,
((A.VL_TOTAL * IR.VL_PERCETUAL_PAGO)/100)VL_COBRAR_CONTA
FROM
VAL_PRO A
INNER JOIN PRO_FAT B ON B.CD_PRO_FAT = A.CD_PRO_FAT
INNER JOIN TAB_FAT C ON C.CD_TAB_FAT = A.CD_TAB_FAT
INNER JOIN GRU_PRO D ON D.CD_GRU_PRO = B.CD_GRU_PRO
LEFT JOIN VAL_PORTE E ON E.CD_POR_ANE = B.CD_POR_ANE AND E.CD_TAB_FAT = A.CD_TAB_FAT
LEFT JOIN ITREGRA IR ON IR.CD_TAB_FAT = A.CD_TAB_FAT AND B.CD_GRU_PRO = IR.CD_GRU_PRO
LEFT JOIN EMPRESA_CON_PLA ECPLA ON ECPLA.CD_REGRA = IR.CD_REGRA 
LEFT JOIN CONVENIO CONV ON CONV.CD_CONVENIO = ECPLA.CD_CONVENIO 
LEFT JOIN CON_PLA CPLA ON CPLA.CD_CON_PLA = ECPLA.CD_CON_PLA AND CPLA.CD_CONVENIO = CONV.CD_CONVENIO
WHERE A.DT_VIGENCIA = (SELECT MAX(X.DT_VIGENCIA) FROM VAL_PRO X WHERE X.CD_TAB_FAT = A.CD_TAB_FAT AND X.CD_PRO_FAT = A.CD_PRO_FAT)
--AND C.DS_TAB_FAT LIKE '%HST%'
AND ECPLA.CD_MULTI_EMPRESA = 4
--AND A.CD_TAB_FAT IN (2967)
and A.CD_PRO_FAT IN (SELECT PF.CD_PRO_FAT FROM PRO_FAT PF WHERE PF.CD_GRU_PRO IN (73,91,55) 
AND PF.SN_ATIVO = 'S')
AND B.SN_ATIVO = 'S'
AND B.CD_GRU_PRO IN (73,91,55)
AND B.SN_ATIVO = 'S'
ORDER BY 1,2,3
