SELECT 
TO_DATE(ATD.DT_ATENDIMENTO,'DD/MM/RRRR')DT_ATENDIMENTO,
ATD.CD_ATENDIMENTO ATENDIMENTO,
ATD.CD_CONVENIO||' - '||CONV.NM_CONVENIO CONVENIO,
RF.CD_REG_FAT CONTA,
RF.CD_REMESSA,
TP.DS_TIP_ACOM TIPO_ACOMODACAO
FROM 
ATENDIME ATD
INNER JOIN REG_FAT RF ON RF.CD_ATENDIMENTO = ATD.CD_ATENDIMENTO 
AND RF.CD_CONVENIO = ATD.CD_CONVENIO
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = RF.CD_CONVENIO 
INNER JOIN TIP_ACOM TP ON TP.CD_TIP_ACOM = ATD.CD_TIP_ACOM
WHERE ATD.DT_ATENDIMENTO BETWEEN TO_DATE('01/01/2021','DD/MM/RRRR') AND TO_DATE('28/02/2023','DD/MM/RRRR')
AND RF.TP_CLASSIFICACAO_CONTA <> ('O')
AND ATD.CD_CONVENIO = 5
AND ATD.CD_MULTI_EMPRESA = 7
--AND ATD.CD_ATENDIMENTO = 3256797
ORDER BY TO_DATE(ATD.DT_ATENDIMENTO,'DD/MM/RRRR') 

