---- consultar pasta parcial
ELECT * FROM 
DOCUMENTO_PASTA_PARCIAL X --SET X.
WHERE X.CD_ATENDIMENTO = 5094299;

--- update para inserir as contas da pasta parcial 
UPDATE 
DOCUMENTO_PASTA_PARCIAL XP SET XP.CD_REG_FAT =(SELECT CD_REG_FAT FROM REG_FAT WHERE CD_ATENDIMENTO = 5094299 
AND TRUNC(DT_INICIO) = TRUNC(XP.DT_ABERTURA))
WHERE XP.CD_ATENDIMENTO = 5094299

-- consultar as contas que constam para o atendimento
SELECT CD_REG_FAT, DT_INICIO, DT_FINAL FROM REG_FAT WHERE CD_ATENDIMENTO = 5094299  
