CREATE OR REPLACE VIEW VW_ACSC_QUERY_ALT_CBOS_CONS (
CD_ATENDIMENTO,
TP_ATENDIMENTO,
CD_ESPECIALID_ATEND,
CD_CBOS_ATENDIMENTO,
CD_PRESTADOR,
CD_ESPECIALID_PRESTADOR,
CD_CBOS_PRESTADOR)
AS 
SELECT 
A.CD_ATENDIMENTO,
A.TP_ATENDIMENTO,
A.CD_ESPECIALID CD_ESPECIALID_ATEND,
B.CD_CBOS CD_CBOS_ATENDIMENTO,
C.CD_PRESTADOR CD_PRESTADOR ,
C.CD_ESPECIALID CD_ESPECIALID_PRESTADOR,
(SELECT X.CD_CBOS FROM ESPECIALID X WHERE X.CD_ESPECIALID = C.CD_ESPECIALID)CD_CBOS_PRESTADOR
from 
dbamv.atendime a 
inner join dbamv.especialid b on b.cd_especialid = a.cd_especialid
inner join dbamv.esp_med c on a.cd_prestador = c.cd_prestador
where a.cd_atendimento = a.cd_atendimento
and c.sn_especial_principal = 'S'
and a.tp_atendimento = 'A'
/

GRANT DELETE,INSERT,SELECT,UPDATE ON DBAMV.VW_ACSC_QUERY_ALT_CBOS_CONS TO DBAMV
/
GRANT DELETE,INSERT,SELECT,UPDATE ON DBAMV.VW_ACSC_QUERY_ALT_CBOS_CONS TO ACSC_AFONSO_FARIA
/
commit;
