SELECT 
   
   NM_CONVENIO,
   SUM(VL_TOTAL_NOTA)TOTAL_VL_TOTAL_NOTA,
   SUM(VL_RECEBIDO)TOTAL_VL_TOTAL_RECEBIDO,
   SUM(VL_GLOSA)TOTAL_VL_TOTAL_GLOSA
FROM
(
SELECT 
FT.DT_COMPETENCIA,
CONV.CD_CONVENIO,
CONV.NM_CONVENIO,
CR.CD_FORNECEDOR,
NF.NM_CLIENTE,
NF.NR_ID_NOTA_FISCAL RPS,
NF.NR_NOTA_FISCAL_NFE NFE,
TRUNC(NF.HR_EMISSAO_NFE) DT_EMISSAO_NFE,
CR.CD_CON_REC,
SUM(INF.VL_ITFAT_NF)VL_TOTAL_NOTA,
NVL(RCR.VL_RECEBIDO,0)VL_RECEBIDO,    
RCR.DT_RECEBIMENTO,
CASE WHEN RCR.DT_RECEBIMENTO IS NULL THEN 'Pendente em:'
     ELSE 'Recebido em:'
     END ||' '||
CASE WHEN TRUNC(RCR.DT_RECEBIMENTO) - TRUNC(NF.HR_EMISSAO_NFE) IS NOT NULL 
     THEN TRUNC(RCR.DT_RECEBIMENTO) - TRUNC(NF.HR_EMISSAO_NFE)  
     ELSE ROUND(SYSDATE - TRUNC(NF.HR_EMISSAO_NFE))
     END||''||'Dias'TEMPO_RECEBIMENTO,

ICR.VL_GLOSA,
CASE WHEN ICR.TP_QUITACAO = 'G' THEN 'QUITADO_COM_GLOSA'
     WHEN ICR.TP_QUITACAO = 'C' THEN 'COMPROMETIDO'
     WHEN ICR.TP_QUITACAO = 'Q' THEN 'QUITADO'
     WHEN ICR.TP_QUITACAO = 'P' THEN 'PARC_RECEBIDO'
     ELSE ICR.TP_QUITACAO
     END TP_QUITACAO

FROM 
REMESSA_FATURA REM
INNER JOIN REG_FAT RF ON RF.CD_REMESSA = REM.CD_REMESSA
INNER JOIN CONVENIO CONV ON CONV.CD_CONVENIO = RF.CD_CONVENIO 
INNER JOIN FATURA FT ON FT.CD_FATURA = REM.CD_FATURA
INNER JOIN ITFAT_NOTA_FISCAL INF ON INF.CD_REG_FAT = RF.CD_REG_FAT 
                                 AND INF.CD_REMESSA = REM.CD_REMESSA 
INNER JOIN NOTA_FISCAL NF  ON NF.CD_NOTA_FISCAL = INF.CD_NOTA_FISCAL                                 
INNER JOIN CON_REC CR ON CR.CD_NOTA_FISCAL = NF.CD_NOTA_FISCAL   
LEFT JOIN ITCON_REC ICR ON ICR.CD_CON_REC = CR.CD_CON_REC    
LEFT JOIN RECCON_REC RCR ON RCR.CD_ITCON_REC = ICR.CD_ITCON_REC                          
WHERE CONV.TP_CONVENIO = 'C'
AND FT.DT_COMPETENCIA = to_date('01/11/2021','DD/MM/YYYY')
AND REM.DT_FECHAMENTO IS NOT NULL
--AND CR.CD_CON_REC = 1150995
GROUP BY
FT.DT_COMPETENCIA,
CONV.CD_CONVENIO,
CONV.NM_CONVENIO,
CR.CD_FORNECEDOR,
NF.NM_CLIENTE,
NF.NR_ID_NOTA_FISCAL,
NF.NR_NOTA_FISCAL_NFE,
NF.HR_EMISSAO_NFE,
CR.CD_CON_REC,
NF.CD_FORNECEDOR,
RCR.VL_RECEBIDO,
RCR.DT_RECEBIMENTO,
ICR.TP_QUITACAO,
ICR.VL_GLOSA,
CONV.NR_DIAS_PAGTO_REMESSA
ORDER BY CD_CONVENIO
)
GROUP BY NM_CONVENIO
ORDER BY 1
