SELECT OWNER,
       CONSTRAINT_NAME,
       CONSTRAINT_TYPE,
       TABLE_NAME,
       R_OWNER,
       R_CONSTRAINT_NAME
  FROM ALL_CONSTRAINTS
 WHERE CONSTRAINT_TYPE = 'R'
   AND R_CONSTRAINT_NAME IN
       (SELECT CONSTRAINT_NAME
          FROM ALL_CONSTRAINTS
         WHERE CONSTRAINT_TYPE IN ('P', 'U')
           AND TABLE_NAME = 'EXP_ARQUIVO_REMESSA')
