------- VALORES A FATURAR (CONTAS ABERTAS)
------- INTERNADOS ------
SELECT 
A.CD_REG_FAT,
B.TP_ATENDIMENTO,
B.CD_ORI_ATE,
D.DS_ORI_ATE,
NVL(SUM(C.VL_TOTAL_CONTA),0)VL_TOTAL_CONTA
FROM 
DBAMV.REG_FAT A
INNER JOIN ITREG_FAT C ON C.CD_REG_FAT = A.CD_REG_FAT
INNER JOIN ATENDIME B ON B.CD_ATENDIMENTO = A.CD_ATENDIMENTO
INNER JOIN ORI_ATE D ON D.CD_ORI_ATE = B.CD_ORI_ATE
WHERE A.CD_CONVENIO = 40
--AND B.DT_ATENDIMENTO BETWEEN '01/04/2022' AND '18/04/2022'
AND A.SN_FECHADA = 'N'
AND B.CD_MULTI_EMPRESA = 1
AND C.SN_PERTENCE_PACOTE = 'N'
and a.cd_reg_fat = 253429
GROUP BY
A.CD_REG_FAT,
B.TP_ATENDIMENTO,
B.CD_ORI_ATE,
D.DS_ORI_ATE
ORDER BY 2
;

--- PA -----
SELECT 
A1.CD_REG_AMB,
A3.TP_ATENDIMENTO,
--A1.CD_REG_AMB,
A3.CD_ORI_ATE,
A4.DS_ORI_ATE,
NVL(SUM(A2.VL_TOTAL_CONTA),0)VL_TOTAL_CONTA
FROM
DBAMV.REG_AMB A1
INNER JOIN ITREG_AMB A2 ON A2.CD_REG_AMB = A1.CD_REG_AMB
INNER JOIN ATENDIME A3 ON A3.CD_ATENDIMENTO = A2.CD_ATENDIMENTO
INNER JOIN Ori_ATE A4 ON A4.CD_ORI_ATE = A3.CD_ORI_ATE
WHERE A2.SN_FECHADA = 'N'
AND A3.CD_CONVENIO = 40
AND A3.DT_ATENDIMENTO BETWEEN '01/04/2022' AND '18/04/2022'
AND A2.SN_PERTENCE_PACOTE = 'N'
--AND A1.CD_REG_AMB = 7673999
GROUP BY 
A1.CD_REG_AMB,
A3.TP_ATENDIMENTO,
A3.CD_ORI_ATE,
A4.DS_ORI_ATE
ORDER BY 2
;


--------- CONTAS FECHADAS -----------------
--- INTERNADOS -----
SELECT 
B.TP_ATENDIMENTO,
B.CD_ORI_ATE,
D.DS_ORI_ATE,
NVL(SUM(C.VL_TOTAL_CONTA),0)VL_TOTAL_CONTA
FROM 
DBAMV.REG_FAT A
INNER JOIN ITREG_FAT C ON C.CD_REG_FAT = A.CD_REG_FAT
INNER JOIN ATENDIME B ON B.CD_ATENDIMENTO = A.CD_ATENDIMENTO
INNER JOIN ORI_ATE D ON D.CD_ORI_ATE = B.CD_ORI_ATE
WHERE A.CD_CONVENIO = 40
--AND B.DT_ATENDIMENTO BETWEEN '01/04/2022' AND '18/04/2022'
AND A.SN_FECHADA = 'S'
AND B.CD_MULTI_EMPRESA = 1
AND C.SN_PERTENCE_PACOTE = 'N'
AND A.CD_REG_FAT = 253429
GROUP BY 
B.TP_ATENDIMENTO,
B.CD_ORI_ATE,
D.DS_ORI_ATE
;
----- PA ------------
SELECT 
A3.TP_ATENDIMENTO,
--A1.CD_REG_AMB,
A3.CD_ORI_ATE,
A4.DS_ORI_ATE,
SUM(A2.VL_TOTAL_CONTA)VL_TOTAL_CONTA
FROM
DBAMV.REG_AMB A1
INNER JOIN ITREG_AMB A2 ON A2.CD_REG_AMB = A1.CD_REG_AMB
INNER JOIN ATENDIME A3 ON A3.CD_ATENDIMENTO = A2.CD_ATENDIMENTO
INNER JOIN Ori_ATE A4 ON A4.CD_ORI_ATE = A3.CD_ORI_ATE
WHERE A2.SN_FECHADA = 'S'
AND A3.CD_CONVENIO = 40
AND A3.DT_ATENDIMENTO BETWEEN '01/04/2022' AND '18/04/2022'
AND A2.SN_PERTENCE_PACOTE = 'N'
--AND A1.CD_REG_AMB = 7673999
GROUP BY A3.TP_ATENDIMENTO,
A3.CD_ORI_ATE,
A1.CD_REG_AMB,
A4.DS_ORI_ATE
;


----- VALORES Á RECEBER E RECEBIDOS ------------
------- INTERNADOS ------------
SELECT 
B.TP_ATENDIMENTO,
B.CD_ORI_ATE,
D.DS_ORI_ATE,
C.VL_TOTAL_CONTA,
E.CD_CON_REC,
E.VL_PREVISTO,
F.TP_QUITACAO,
NVL(F.VL_SOMA_RECEBIDO,0)VL_RECEBIDO,
NVL(F.VL_SOMA_RECEBIDO,0) - E.VL_PREVISTO VL_A_RECEBER
FROM 
DBAMV.REG_FAT A
INNER JOIN ITREG_FAT C ON C.CD_REG_FAT = A.CD_REG_FAT
INNER JOIN ATENDIME B ON B.CD_ATENDIMENTO = A.CD_ATENDIMENTO
INNER JOIN ORI_ATE D ON D.CD_ORI_ATE = B.CD_ORI_ATE
INNER JOIN CON_REC E ON E.CD_REG_FAT = A.CD_REG_FAT
INNER JOIN ITCON_REC F ON F.CD_CON_REC = E.CD_CON_REC
--LEFT JOIN RECCON_REC G ON G.CD_ITCON_REC = F.CD_ITCON_REC
WHERE A.CD_CONVENIO = 40
AND B.DT_ATENDIMENTO BETWEEN '01/04/2022' AND '18/04/2022'
AND A.SN_FECHADA = 'S'
AND B.CD_MULTI_EMPRESA = 1
AND C.SN_PERTENCE_PACOTE = 'N'
--AND A.CD_REG_FAT = 253893

;
---------- PA -------------
SELECT 
A3.TP_ATENDIMENTO,
--A1.CD_REG_AMB,
A3.CD_ORI_ATE,
A4.DS_ORI_ATE,
A6.CD_CON_REC,
A6.VL_PREVISTO,
A7.TP_QUITACAO,
A7.VL_SOMA_RECEBIDO,
(A7.VL_SOMA_RECEBIDO) - A6.VL_PREVISTO VL_A_RECEBER
FROM
DBAMV.REG_AMB A1
INNER JOIN ITREG_AMB A2 ON A2.CD_REG_AMB = A1.CD_REG_AMB
INNER JOIN ATENDIME A3 ON A3.CD_ATENDIMENTO = A2.CD_ATENDIMENTO
INNER JOIN Ori_ATE A4 ON A4.CD_ORI_ATE = A3.CD_ORI_ATE
INNER JOIN CON_REC A6 ON A6.CD_REG_AMB = A1.CD_REG_AMB
INNER JOIN ITCON_REC A7 ON A7.CD_CON_REC = A6.CD_CON_REC 
WHERE A2.SN_FECHADA = 'S'
AND A3.CD_CONVENIO = 40
AND A3.DT_ATENDIMENTO BETWEEN '01/04/2022' AND '18/04/2022'
AND A2.SN_PERTENCE_PACOTE = 'N'
--AND A1.CD_REG_AMB = 7673999
GROUP BY A3.TP_ATENDIMENTO,
A3.CD_ORI_ATE,
A1.CD_REG_AMB,
A4.DS_ORI_ATE,
A6.CD_CON_REC,
A6.VL_PREVISTO,
A7.TP_QUITACAO,
A7.VL_SOMA_RECEBIDO
;

