--- ALTERAR COMPETENCIA REMESSA 
----1º LOCALIZAR CD_FATURA
SELECT   A.CD_REMESSA,
         A.CD_FATURA ,
         FT.CD_CONVENIO,
         CV.NM_CONVENIO,
         FT.DT_COMPETENCIA,
        A.DT_ENTREGA_DA_FATURA,
         A.DT_PREVISTA_PARA_PGTO
FROM REMESSA_FATURA A 
LEFT JOIN FATURA FT ON FT.CD_FATURA = A.CD_FATURA
LEFT JOIN CONVENIO CV ON CV.CD_CONVENIO = FT.CD_CONVENIO
WHERE A.CD_REMESSA in(501797,
501601,
501254,
501223,
500790,
500790,
499405,
501854,
498848,
498522,
498170,
498045,
497793,
497792,
491262)
-- 2º CONSULTAR O CD_FATURA EM QUAL COMPETENCIA SE ENCONTRA 
SELECT B.CD_CONVENIO,B.DS_FATURA ,B.DT_COMPETENCIA, B.CD_MULTI_EMPRESA FROM FATURA B WHERE B.CD_FATURA = 19470
-- 3º LOCALIZAR  CD_FATURA QUE CONSTA NA COMPETENCIA SOLICITADA 
SELECT * FROM FATURA B1 WHERE B1.CD_CONVENIO = 19 AND B1.CD_MULTI_EMPRESA = 1  AND B1.DT_COMPETENCIA = '01/01/2023'

-- 4º ALTERAR PARA O CD_FATURA DA COMPETENCIA SOLICITADA
UPDATE REMESSA_FATURA C2 SET C2.CD_FATURA = 19187
WHERE C2.CD_REMESSA in()
----------------------------------------------------------------------------
----------------------------------------------------------------------------
----- ALTERAR DATA DE PAGAMENTO -----
SELECT A.CD_FATURA ,
        A.DT_ENTREGA_DA_FATURA,
         A.DT_PREVISTA_PARA_PGTO,
         A.DT_FECHAMENTO ---
FROM REMESSA_FATURA A WHERE A.CD_REMESSA in (508628,509308,509286);


UPDATE REMESSA_FATURA A SET A.DT_PREVISTA_PARA_PGTO = '05/09/2022' , A.DT_ENTREGA_DA_FATURA = '05/08/2022'
WHERE A.CD_REMESSA in (493667,493573)

-------------  ( ALTERACAO DATA DE ENTREGA E VENCIMENTO DA REMESSA )------

---- ###   PARA DESCOBRIR SE A REMESSA JA ESTEJA NA NOTA FISCAL ###---------

SELECT IFNF.CD_REMESSA, NF.CD_NOTA_FISCAL,NF.NR_ID_NOTA_FISCAL , VA.VCTO
FROM DBAMV.ITFAT_NOTA_FISCAL IFNF
INNER JOIN DBAMV.NOTA_FISCAL NF ON NF.CD_NOTA_FISCAL = IFNF.CD_NOTA_FISCAL
LEFT OUTER JOIN DBAMV.HNB_SNAP_SALDO_REC_VENC_ANAL VA ON VA.NF LIKE NF.NR_ID_NOTA_FISCAL
--where nf.nr_id_nota_fiscal = 812497
WHERE IFNF.CD_REMESSA IN (
504732,503086
)

GROUP BY IFNF.CD_REMESSA, NF.CD_NOTA_FISCAL,NF.NR_ID_NOTA_FISCAL ,VA.VCTO

-------------- CORRIGIR DA DATA VENCIMENTO  NA ITCON_REC ( CONTA A RECEBER )  ---------------

select rowid,icr.* from dbamv.itcon_rec icr where icr.cd_con_rec in (
--Update dbamv.itcon_rec icr set icr.dt_prevista_recebimento = '29/08/2022' , icr.dt_vencimento = '29/08/2022' where icr.cd_con_rec in (
  select distinct(cr.cd_con_rec) --,cr.cd_nota_fiscal,cr.dt_emissao 
  from dbamv.con_rec cr 
  inner join dbamv.itfat_nota_fiscal ifnf on ifnf.cd_nota_fiscal = cr.cd_nota_fiscal
  where ifnf.cd_remessa in (509212,507274))
  



SELECT * FROM REMESSA_FATURA WHERE CD_REMESSA IN (507376,507278)
SELECT * FROM REG_AMB WHERE CD_REMESSA = 507376
