SELECT * FROM REMESSA_FATURA WHERE CD_REMESSA = 242234; 
SELECT * FROM FATURA WHERE CD_FATURA = 12007
SELECT * FROM AGRUPAMENTO WHERE CD_AGRUPAMENTO = 2;

/*SELECT DISTINCT SUM(A.VL_TOTAL_CONTA) FROM REG_AMB A
INNER JOIN ITREG_AMB B ON B.CD_REG_AMB = A.CD_REG_AMB
WHERE CD_REMESSA = 242234
AND B.SN_PERTENCE_PACOTE = 'S';
*/
SELECT DISTINCT SUM(A.VL_TOTAL_CONTA) FROM REG_AMB A
INNER JOIN ITREG_AMB B ON B.CD_REG_AMB = A.CD_REG_AMB
WHERE CD_REMESSA = 242234
AND B.SN_PERTENCE_PACOTE = 'N'

SELECT * FROM ITFAT_NOTA_FISCAL WHERE CD_REMESSA = 242234
SELECT * FROM NOTA_FISCAL WHERE CD_NOTA_FISCAL = 472386

SELECT * FROM CON_REC WHERE CD_CON_REC = 704786;
SELECT * FROM ITCON_REC WHERE CD_CON_REC = 704786;
SELECT * FROM RECCON_REC WHERE CD_ITCON_REC = 708584
