/*SELECT 
ANO_RECEB,
SUM(TOTAL_VL_DESCONTO)TOTAL_VL_DESCONTO,
SUM(TOTAL_RECEBIDO)TOTAL_RECEBIDO
FROM
(
SELECT 
TO_CHAR(E.DT_RECEBIMENTO,'YYYY')ANO_RECEB,
NVL(SUM(E.VL_DESCONTO),0)TOTAL_VL_DESCONTO,
SUM(E.VL_RECEBIDO)TOTAL_RECEBIDO
FROM 
CON_REC C 
INNER JOIN ITCON_REC D ON D.CD_CON_REC = C.CD_CON_REC
INNER JOIN RECCON_REC E ON E.CD_ITCON_REC = D.CD_ITCON_REC
WHERE C.CD_FORNECEDOR = 8
AND E.DT_RECEBIMENTO BETWEEN '01/01/2018' AND SYSDATE 
AND C.CD_MULTI_EMPRESA = 1
--AND C.CD_CON_REC = 664730
GROUP BY 
E.DT_RECEBIMENTO
)
GROUP BY 
ANO_RECEB
--TOTAL_VL_DESCONTO
ORDER BY 1 
*/

--;

SELECT 
E.CD_RECCON_REC,
C.CD_CON_REC,
C.CD_FORNECEDOR,
F.NM_CLIENTE,
C.DT_EMISSAO,
C.DT_LANCAMENTO,
C.NR_DOCUMENTO NR_RPS,
F.NR_NOTA_FISCAL_NFE NR_NFE,
D.DT_VENCIMENTO,
TO_CHAR(E.DT_RECEBIMENTO,'YYYY')ANO_RECEB,
D.DT_PREVISTA_RECEBIMENTO,
DECODE(D.TP_QUITACAO,'Q','Quitado','P','Parc.Recebido','C','Comprometido','G','Quitado com Glosa')Tipo_quitacao,
D.VL_DUPLICATA,
NVL(SUM(E.VL_DESCONTO),'0')VALOR_DESCONTO,
NVL(SUM(D.VL_GLOSA),'0')VL_GLOSA,
D.VL_GLOSA_ACEITA VL_ACEITE,
E.DT_RECEBIMENTO,
SUM(E.VL_RECEBIDO) VL_RECEBIDO
FROM 
CON_REC C 
INNER JOIN ITCON_REC D ON D.CD_CON_REC = C.CD_CON_REC
INNER JOIN RECCON_REC E ON E.CD_ITCON_REC = D.CD_ITCON_REC
INNER JOIN NOTA_FISCAL F ON F.CD_NOTA_FISCAL = C.CD_NOTA_FISCAL
WHERE C.CD_FORNECEDOR = 8
AND E.DT_RECEBIMENTO BETWEEN '01/01/2022' AND SYSDATE 
AND C.CD_MULTI_EMPRESA = 1
AND C.CD_CON_REC = 1220875
GROUP BY 
E.CD_RECCON_REC,
C.CD_CON_REC,
C.CD_FORNECEDOR,
F.NM_CLIENTE,
C.DT_EMISSAO,
C.DT_LANCAMENTO,
C.NR_DOCUMENTO,
F.NR_NOTA_FISCAL_NFE,
D.DT_VENCIMENTO,
D.VL_GLOSA,
D.VL_GLOSA_ACEITA,
D.DT_PREVISTA_RECEBIMENTO,
D.TP_QUITACAO,
E.DT_RECEBIMENTO,
D.VL_DUPLICATA
ORDER BY 1 
;
SELECT * FROM IT_RECEBIMENTO RECB WHERE RECB.CD_RECCON_REC IN (1555659);
SELECT /*SUM(GL.VL_GLOSA), SUM(GL.VL_GLOSA_PRE_ACEITA)*/* FROM GLOSAS GL WHERE GL.CD_ITFAT_NF IN (SELECT RECB.CD_ITFAT_NF FROM IT_RECEBIMENTO RECB WHERE RECB.CD_RECCON_REC IN (1555659))
