SELECT * FROM CIDADE WHERE CD_CIDADE = 20607
SELECT * FROM CEP_BAIRROS X ORDER BY 1 DESC --WHERE X.CD_BAIRRO = 
SELECT * FROM CEP_BAIRROS X WHERE X.CD_BAIRRO = 31721 --FOR UPDATE
SELECT * FROM CEP_LOGRADOUROS ORDER BY 1 DESC 
SELECT * FROM CEP_LOGRADOUROS WHERE CD_LOGRADOURO = 1344579 FOR UPDATE 
81119 -- SEQ_BAIRRRO
1344581 - SEQ_LOGRADOURO
81 - LOGRADOURO RUA 
22756 - LOCALIDADE 
SELECT * FROM TIPO_LOGRADOURO


