SELECT
A.CD_ATENDIMENTO,
A.CD_CONVENIO,
fnc_hnb_iniciais_nome(P.NM_PACIENTE)NM_PACIENTE_ABREVIADO,
P.NM_PACIENTE,
fnc_hnb_iniciais_nomE(P.NM_MAE)NM_MAE_ABREVIADO,
P.NM_MAE,
P.NR_CNS,
O.CD_ORI_ATE,
O.DS_ORI_ATE,
O.TP_ORIGEM,
O.CD_SETOR,
O.CD_MULTI_EMPRESA
--COUNT(*)

FROM ATENDIME A 
INNER JOIN PACIENTE P ON P.CD_PACIENTE = A.CD_PACIENTE
INNER JOIN ORI_ATE O ON O.CD_ORI_ATE = A.CD_ORI_ATE AND O.CD_MULTI_EMPRESA = A.CD_MULTI_EMPRESA
INNER JOIN SETOR S ON S.CD_SETOR = O.CD_SETOR
WHERE O.CD_MULTI_EMPRESA = 13
AND A.DT_ATENDIMENTO BETWEEN '01/08/2021' AND SYSDATE
--AND A.CD_ATENDIMENTO = 8472564
ORDER BY P.NM_PACIENTE
