select  --cd_pacote,--nextval.seq_pacote
'null'cd_pacote,
',',
cd_multi_empresa,
',',
cd_convenio,
',',
cd_con_pla,
',',
cd_pro_fat,
',',
cd_pro_fat_pacote,
',',
dt_vigencia,
',',
cd_tip_acom,
',',
cd_setor,
',',
tp_atendimento,
',',
qt_diarias,
',',
vl_perc_pac_secund,
',',
tp_extra,
',',
sn_guia,
',',
qt_parcelas,
',',
sn_automatico,
',',
ds_observacao,
',',
dt_vigencia_final,
',',
nr_idade_maxima,
',',
tp_cobranca_pac_secund,
',',
vl_perc_pac_secund_2,
',',
vl_perc_pac_secund_3,
',',
vl_perc_pac_secund_4,
',',
cd_tipo_internacao,
',',
sn_valida_autorizacao,
',',
sn_day_clinic,
',',
vl_perc_acres_gemelares,
',',
vl_perc_desc_rn_uti,
',',
nr_imc_inicial,
',',
nr_imc_final,
',',
sn_obito,
',',
sn_gemelar,
',',
sn_diaria_gabarito,
',',
tp_dispercao,
',',
sn_considera_hora,
',',
sn_profat_descaracteriza,
',',
sn_nao_intervencionista,
',',
sn_lanca_no_fechamento,
',',
sn_pacote_pro_fat,
',',
sn_proc_fora_pacote,
',',
cd_contrato,
',',
vl_perc_limite_opme,
',',
sn_protocolo_de_pacote
from pacote a where a.cd_multi_empresa = 1 and A.CD_PACOTE = 4446 --a.cd_pro_fat = 31303315-- and a.cd_convenio = 6
;


SELECT b.cd_pacote_excecao,--nextval.seq_pacote_excecao 
',',
b.cd_pacote , 
',',
b.cd_gru_pro, 
',',
b.cd_pro_fat, 
',',
b.cd_setor, 
',',
b.cd_tip_acom,
');'
FROM PACOTE_EXCECAO B WHERE B.CD_PACOTE = 4443



--INSERT INTO DBAMV.PACOTE (CD_PACOTE,CD_MULTI_EMPRESA,CD_CONVENIO,CD_CON_PLA,CD_PRO_FAT,CD_PRO_FAT_PACOTE,DT_VIGENCIA,CD_TIP_ACOM,CD_SETOR,TP_ATENDIMENTO,QT_DIARIAS,VL_PERC_PAC_SECUND,TP_EXTRA,SN_GUIA,QT_PARCELAS,SN_AUTOMATICO,DS_OBSERVACAO,DT_VIGENCIA_FINAL,NR_IDADE_MAXIMA,TP_COBRANCA_PAC_SECUND,VL_PERC_PAC_SECUND_2,VL_PERC_PAC_SECUND_3,VL_PERC_PAC_SECUND_4,CD_TIPO_INTERNACAO,SN_VALIDA_AUTORIZACAO,SN_DAY_CLINIC,VL_PERC_ACRES_GEMELARES,VL_PERC_DESC_RN_UTI,NR_IMC_INICIAL,NR_IMC_FINAL,SN_OBITO,SN_GEMELAR,SN_DIARIA_GABARITO,TP_DISPERCAO,SN_CONSIDERA_HORA,SN_PROFAT_DESCARACTERIZA,SN_NAO_INTERVENCIONISTA,SN_LANCA_NO_FECHAMENTO,SN_PACOTE_PRO_FAT,SN_PROC_FORA_PACOTE,CD_CONTRATO,VL_PERC_LIMITE_OPME,SN_PROTOCOLO_DE_PACOTE)VALUES(nextval.seq_pacote,'1','3', null, '31303315', '10000366', '01/01/2022', null, null, 'T' ,  '1' , 100,00, null,'N', '1' , 'S' , null, null, null, 'G ', '100.00', '100.00', '100.00', null,'N','N', null, null, null, null,'N','N','N', 'CE', null,'N','N','N','N','N', null, null,'N');
INSERT INTO DBAMV.PACOTE (CD_PACOTE,CD_MULTI_EMPRESA,CD_CONVENIO,CD_CON_PLA,CD_PRO_FAT,CD_PRO_FAT_PACOTE,DT_VIGENCIA,CD_TIP_ACOM,CD_SETOR,TP_ATENDIMENTO,QT_DIARIAS,VL_PERC_PAC_SECUND,TP_EXTRA,SN_GUIA,QT_PARCELAS,SN_AUTOMATICO,DS_OBSERVACAO,DT_VIGENCIA_FINAL,NR_IDADE_MAXIMA,TP_COBRANCA_PAC_SECUND,VL_PERC_PAC_SECUND_2,VL_PERC_PAC_SECUND_3,VL_PERC_PAC_SECUND_4,CD_TIPO_INTERNACAO,SN_VALIDA_AUTORIZACAO,SN_DAY_CLINIC,VL_PERC_ACRES_GEMELARES,VL_PERC_DESC_RN_UTI,NR_IMC_INICIAL,NR_IMC_FINAL,SN_OBITO,SN_GEMELAR,SN_DIARIA_GABARITO,TP_DISPERCAO,SN_CONSIDERA_HORA,SN_PROFAT_DESCARACTERIZA,SN_NAO_INTERVENCIONISTA,SN_LANCA_NO_FECHAMENTO,SN_PACOTE_PRO_FAT,SN_PROC_FORA_PACOTE,CD_CONTRATO,VL_PERC_LIMITE_OPME,SN_PROTOCOLO_DE_PACOTE)VALUES(seq_pacote.nextval,1,3,null,31303315,10000366,'01/01/2022',null,null,'T',1,100.00,null,'N',1,'S',null,null,null,'G',100.00,100.00,100.00,null,'S','N',null,null,null,null,'N','N','N','CE',null,'N','N','N','N','N',null,null,'N');
commit;


INSERT INTO DBAMV.PACOTE_EXCECAO (CD_PACOTE_EXCECAO,CD_PACOTE,CD_GRU_PRO,CD_PRO_FAT,CD_SETOR,CD_TIP_ACOM) values (seq_pacote_excecao.nextval,4446,0,null,null,null);
INSERT INTO DBAMV.PACOTE_EXCECAO (CD_PACOTE_EXCECAO,CD_PACOTE,CD_GRU_PRO,CD_PRO_FAT,CD_SETOR,CD_TIP_ACOM) values ( seq_pacote_excecao.nextval,4446,9,null,null,null);
commit


