SELECT 
/*x1.cd_mov_concor,
X6.NR_DOCUMENTO_IDENTIFICACAO,
X3.DT_PREVISTA_RECEBIMENTO DT_LANCAMENTO,
X6.CD_CON_COR,
X6.VL_MOVIMENTACAO VALOR,
X3.CD_CON_REC,
x4.nr_documento,
X2.CD_RECCON_REC,
X2.NR_DOCUMENTO,
X2.DT_RECEBIMENTO,
X2.DS_RECCON_REC,
NVL(LTRIM(TO_CHAR(SUBSTR(X2.NR_DOCUMENTO,1,7),'9999999')),0)LOTE_XML,
NVL(LTRIM(TO_CHAR(SUBSTR(X2.NR_DOCUMENTO,10,20),'999999999999999')),0)PROTOCOLO,
X2.VL_RECEBIDO,
X3.TP_QUITACAO*/


--sum(x2.vl_recebido)
*


FROM REC_MOV_CON x1
INNER JOIN RECCON_REC X2 ON X2.CD_RECCON_REC = X1.CD_RECCON_REC
INNER JOIN ITCON_REC X3 ON X3.CD_ITCON_REC = X2.CD_ITCON_REC
INNER JOIN CON_REC X4 ON X4.CD_CON_REC = X3.CD_CON_REC
INNER JOIN NOTA_FISCAL X5 ON X5.CD_NOTA_FISCAL = X4.CD_NOTA_FISCAL
INNER JOIN MOV_CONCOR X6 ON X6.CD_MOV_CONCOR = X1.CD_MOV_CONCOR
WHERE x1.cd_mov_concor = 1520534
--AND  X4.CD_CON_REC = 1210382
ORDER BY 1
;

SELECT 
x4.cd_con_rec,
x4.vl_previsto,
sum(x2.vl_recebido)vl_recebido,
x3.vl_glosa,
(sum(x2.vl_recebido) + x3.vl_glosa) - x4.vl_previsto vl_a_receber

FROM REC_MOV_CON x1
INNER JOIN RECCON_REC X2 ON X2.CD_RECCON_REC = X1.CD_RECCON_REC
INNER JOIN ITCON_REC X3 ON X3.CD_ITCON_REC = X2.CD_ITCON_REC
INNER JOIN CON_REC X4 ON X4.CD_CON_REC = X3.CD_CON_REC
INNER JOIN NOTA_FISCAL X5 ON X5.CD_NOTA_FISCAL = X4.CD_NOTA_FISCAL
INNER JOIN MOV_CONCOR X6 ON X6.CD_MOV_CONCOR = X1.CD_MOV_CONCOR
WHERE x1.cd_mov_concor = 1520534
--AND  X4.CD_CON_REC = 1210382
group by x4.cd_con_rec,
         x3.vl_glosa,
         x4.vl_previsto
         

ORDER BY 1

--SELECT * FROM IT_RECEBIMENTO 

--DBAMV.HNB_VDIC_NF_REMESSA_CONSOL
