SELECT * FROM (
SELECT VDIC_HNB_FFCV_RPX_X_NFE.EMISSAO, 
       VDIC_HNB_FFCV_RPX_X_NFE.CLIENTE, 
       VDIC_HNB_FFCV_RPX_X_NFE.RPS, 
       VDIC_HNB_FFCV_RPX_X_NFE.NFE, 
       VDIC_HNB_FFCV_RPX_X_NFE.
       VDIC_HNB_FFCV_RPX_X_NFE.EMPRESA
FROM 
     DBAMV.VDIC_HNB_FFCV_RPX_X_NFE VDIC_HNB_FFCV_RPX_X_NFE

) Q
WHERE Q.EMISSAO  BETWEEN '01/02/2022' AND '28/02/2022'---@P_EMISSAO_FIM
AND Q.EMPRESA  IN (1)
AND Q.NFE = 'SEM CONVERTER'
