SELECT 
*--SUM(GLOSA)
FROM
(
SELECT VDIC_FNFI_GLOSAS_FINANCEIRO.REMESSA, 
       VDIC_FNFI_GLOSAS_FINANCEIRO.NF, 
       VDIC_FNFI_GLOSAS_FINANCEIRO.ATENDIMENTO, 
       VDIC_FNFI_GLOSAS_FINANCEIRO.PACIENTE, 
       VDIC_FNFI_GLOSAS_FINANCEIRO.PROCEDIMENTO, 
       VDIC_FNFI_GLOSAS_FINANCEIRO.VALOR, 
       VDIC_FNFI_GLOSAS_FINANCEIRO.GLOSA, 
       VDIC_FNFI_GLOSAS_FINANCEIRO.DT_RECEBIDO, 
       VDIC_FNFI_GLOSAS_FINANCEIRO.USUARIO
FROM 
     DBAMV.VDIC_FNFI_GLOSAS_FINANCEIRO VDIC_FNFI_GLOSAS_FINANCEIRO
WHERE 
      ( VDIC_FNFI_GLOSAS_FINANCEIRO.REMESSA IN (233277) )
       AND ( VDIC_FNFI_GLOSAS_FINANCEIRO.NF IN ('679119') )
       AND (VDIC_FNFI_GLOSAS_FINANCEIRO.atendimento IN (5063484))

)

--SELECT * FROM REMESSA_fATURA  WHERE CD_REMESSA IN (472248,233277)-- for update
---SELECT * FROM ITFAT_NOTA_FISCAL WHERE CD_REMESSA = 472248
--SELECT * FROM NOTA_FISCAL WHERE CD_NOTA_FISCAL = 696472

-- 05/01/2202
